### PR TITLE
feat: Experiment List comparison view should show hyperparameters chart [WEB-991]

### PR DESCRIPTION
**Pull request by julian-determined-ai**
## Description

The "compare" view now shows the hyperparameters parallel coordinates chart for each experiment. A few things to note:

1. We are not showing the "trials table" underneath the chart like we do elsewhere in the application. 
2. Only the experiments that have a value for **all** of the selected Hyperparameters and for the selected metric will be shown in the chart. 

**Notes about an issue with the user selectable "Scale"**:
While implementing this PR I came to the realization that the `log` argument no longer behaves as expected, it is clear from the backend code: https://github.com/determined-ai/determined/blob/main/master/internal/api_trials.go#L660

that the log argument no longer has any effect on the data returned from the `time-series` endpoint. The `logScale` argument previously was used to determine the behavior of downsampling and return the log value of metric data: https://github.com/determined-ai/determined/pull/6317/files#diff-b12c0f954792a2c30a89f05a1e7feee604255a0e4ed97569ec05786fd62d1bdbL57

however that is no longer the case and requesting both `linear` and `log` data will return the same result. I will create a bug ticket for the time being.

## Test Plan
1. Navigate to the new experiment listing page and click the "Compare" button
2. Without selecting any experiments, click the hyperparameters tab, no data should be shown.
3. Select an experiment, the "HP", and "Metric" dropdowns should be populated with values from the experiment, and the chart should show data. 
4. Select more experiments, the dropdowns should show the available metrics and hyperparameters from the new experiment salso. 
5. Choose HPs, and a Metric from the dropdown menu. Only experiments with values for all selected HPs and the selected metric should be shown. 
6. Ensure that color of the lines on the chart also match the fill color of the selected experiments. 

## Commentary (optional)

I filed the bug ticket: https://hpe-aiatscale.atlassian.net/browse/WEB-1338 to address the "scale" issue mentioned above.

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

WEB-991

### CODE REVIEW

**Comment by gt2345** [comment]
https://github.com/determined-ai/determined/assets/40620519/d4859dc9-ff8e-4764-8c04-bab3fc8fe4ba

This might be related to my local data, but as you can see, the row I selected seems to be a valid experiment with some hyper parameter values, however, the tab does not show anything. Then after close the Compare section, dis-select, then select again, the error shows up. 


Also I noticed that dis-selecting everything does not reset hyper parameter tab's header. And with the compare section open, selecting more experiments (with addition hyper parameters) does not change the "HP" dropdown.
 Screenshot 2023-06-07 at 12 03 49 PM

One more thing may worth looking into is that the old experiment list seems to lost it's style..
Screenshot 2023-06-07 at 12 25 20 PM


One more general question:
Why did we decide to not show the "trials table" underneath the chart like we do elsewhere in the application? I think that table can be helpful sometime.

**Comment by julian-determined-ai** [comment]
I believe the two bugs that you found should be fixed now. The styling error however is not due to this PR. 

Also, in response to the trial table being moved, @alexjdetermined mentioned that this hyperparameters view is undergoing more design changes in the future so we may decide to include a table in the future.

**Review by gt2345 — APPROVED** [review]
LGTM. 
One thing I'm not sure is, should we store hyper parameters setting respective to each projects? When user switch projects, do they usually expect to use different set of hyper parameters or not.

**Comment by julian-determined-ai** [comment]
@gt2345 I agree with what you said, I have made the settings project specific.

**Pull request merged**
