### PR TITLE
feat: add labels to GCP instances created with det deploy gcp [MLG-170]

### PR DESCRIPTION
**Pull request by drh-determined-ai**
## Description

This feature allows Determined users to apply a key-value pair called a "label" to the master GCP instance created by a command such as the following:
`det deploy gcp up --cluster-id labeltest --project-id determined-ai --add-label foo=bar --add-label key=value`

This is analogous to the existing feature in deploying Determined to a AWS:
`det deploy aws up ... --add-tag foo=bar --add-tag key=value`

Note that what GCP and AWS call "labels" and "tags" are essentially the same thing: key-value pairs that can be used to filter lists of instances (and can be understood as meaningful by users). Also note that GCP instances have "tags", but these are qualitatively different.

## Test Plan

Manually run `det deploy gcp up ... --add-label foo=bar --add-label key=value` and note the label in the Google Cloud console.

## Commentary (optional)

1. CHANGED: The parameter names are subject to change (e.g., we could change `--master-labels` to `--add-label[s]`). 
2. CHANGED: Internally, AWS tags are a list of tuples, whereas GCP labels are a dictionary (corresponding to the `map` object type in Terraform).
3. Only the master instance of a Determined deployment on GCP is labeled. An attempt was made to label agent instances the same way as masters (taking Python parameters and putting the values into Terraform), but this didn't work: agents are brought up by the master instance, not the local machine.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by ioga** [comment]
I'd suggest this flag should follow the same style as `add-tag`, i.e. be `action="append"`.

also cc @loksonarius

**Review by loksonarius — COMMENTED** [review]
I'm totally down for this feature, but I agree with ioga: this flag should use the same name and parse behavior (append) as the AWS flag.
As an aside, I might not understand the third comment on the PR description, so to clarify: what specific resources will and won't have this label applied to them?

**Comment by azhou-determined** [comment]
adding just `master-label` seems weird. does GCP not have a concept of "stacks" like AWS? adding labels to AWS lives on the stack and propagates to all the instances.

**Comment by drh-determined-ai** [comment]
Screenshot 2023-03-06 at 4 08 50 PM

**Comment by drh-determined-ai** [comment]
The argument name and parse behavior now match those for our AWS CLI.

**Comment by drh-determined-ai** [comment]
These GCP instance labels get applied to the _master only_; they do not proliferate to agents. Before this PR, I had attempted a similar feature for labeling agent instances by putting `labels = var.labels` in `resource "google_compute_instance" "agent_instance"` in `harness/determined/deploy/gcp/terraform/modules/compute/main.tf`, but this didn't seem to work: I created an experiment and noticed that the temporary agent instance in the Google Cloud console (y'know, the kind with names like `*-herniated-coconut-trailer`) only had the usual, such as `determined-master-host` and `managed-by` (screenshot to follow).
Screenshot 2023-03-06 at 4 43 54 PM
I don't know whether my dictionary of (agent) labels was overwritten or lost along the way.

**Review by loksonarius — APPROVED** [review]

**Pull request merged**
