### PR TITLE
chore: remove stale install extras from harness python package.

### PR DESCRIPTION
**Pull request by ioga**
## Description

Install extras are stale and see little use. Instead of keeping this extra maintenance burden, let's get rid of them.

## Test Plan

The python package can still be installed.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by mackrorysd** [comment]
I personally have no objection. This feature requires a user to basically specify a minor version of dependencies to have us install them, when they could also have the package manager install them by specifying the same minor version. Unless the combination of Determined and specific versions of these libraries triggers OTHER dependencies where we do want to be more involved, I see no benefit. These have gotten out of date multiple times and no one has, as far as I can tell, ever actually noticed unless they were doing a search / replace to bump dependencies.

I would like to give @rb-determined-ai and @hamidzr a chance to weigh in because I know they have some context too.

**Review by mackrorysd — APPROVED** [review]
+1 (unless Ryan or Hamid has something to add)

**Review by hamidzr — APPROVED** [review]
LGTM. This could potentially break user's use cases but I don't see use advertising for this use anywhere. Should we add a release note?

**Review by azhou-determined — APPROVED** [review]

**Comment by rb-determined-ai** [comment]
I'm totally ok with this.  I have never heard of a customer telling me they've installed determined with one of these extras.  

What would an amle say?  @katport, do people actually use these?

**Review by katport — APPROVED** [review]

**Pull request merged**
