### PR TITLE
docs: update aria labelling for sidebar toggles and toctree groups

### PR DESCRIPTION
**Pull request by ashtonG**
## Description

This updates the docs to fix the accessibility issues highlighted in the levelaccess tool.

- The sidebar toggles as well as the labels controlling the expansion and collapse of the table of contents have been given screenreader labels
- the inputs controlling the sidebar visibility have been updated to indicate that they control the primary/secondary sidebars as well as a pointer to a descriptive label

In order to do this properly, we fork the pydata-sphinx-theme python package and make the changes there. The changes to the package can be seen in https://github.com/determined-ai/pydata-sphinx-theme/pull/1 -- once approved, we can change the branch this PR is pointing to to main.

## Test Plan

Docs site should not have any 10 severity accessibility issues in levelaccess.

## Checklist

- [X] Changes have been manually QA'd
- [X] User-facing API changes need the "User-facing API Change" label.
- [X] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [X] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

WEB-1292

### CODE REVIEW

**Review by hkang1 — COMMENTED** [review]
I did a `make clean && make get-deps && make build && make live` and it looks like it is building and serving without a hitch. But when I look at the targeted `toctree-checkbox` areas based on the report, they haven't changed as shown in the screenshot below. Maybe the changes are not coming through?

Screenshot 2023-07-19 at 10 08 07 AM

For the `toctree-checkbox` issues, they are basically invisible checkboxes to keep track of collapsible state of the sidebar menu. It might be best to apply the following attribute instead?

```
aria-hidden="true"
```

UPDATE: I'm not seeing your changes in the forked branch in the new build. What do you typically do for your local build? It seems like it's pulling in the right dependency but the changes in the branch don't seem to be in the newly built doc...

```
❯ make get-deps
pip install -r requirements.txt
Collecting pydata-sphinx-theme@ git+https://github.com/determined-ai/pydata-sphinx-theme@chore/WEB-1292/hpe-accessibility-patches
  Cloning https://github.com/determined-ai/pydata-sphinx-theme (to revision chore/WEB-1292/hpe-accessibility-patches) to /private/var/folders/ws/1f9qnqy5543c1ymspl1bkgnr0000gp/T/pip-install-8sto9o42/pydata-sphinx-theme_ff07c9aff8ff479f9604f1dc1b0e6e05
  Running command git clone --filter=blob:none --quiet https://github.com/determined-ai/pydata-sphinx-theme /private/var/folders/ws/1f9qnqy5543c1ymspl1bkgnr0000gp/T/pip-install-8sto9o42/pydata-sphinx-theme_ff07c9aff8ff479f9604f1dc1b0e6e05
  Running command git checkout -b chore/WEB-1292/hpe-accessibility-patches --track origin/chore/WEB-1292/hpe-accessibility-patches
  Switched to a new branch 'chore/WEB-1292/hpe-accessibility-patches'
  branch 'chore/WEB-1292/hpe-accessibility-patches' set up to track 'origin/chore/WEB-1292/hpe-accessibility-patches'.
  Resolved https://github.com/determined-ai/pydata-sphinx-theme to commit e3a365c78e79f10923d3a46c001fa3bef8833550
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
```

**Comment by ashtonG** [comment]
i run with `make -C docs get-deps` and then `make -C docs clean live`. I'm wondering if there's something cached locally somewhere, because the docs changes are being picked up on the docs preview:
image

I did have to run `make -C examples` once in order to get the build to succeed?

I don't think `aria-hidden=true` is the right approach for these checkboxes because they aren't decorative -- the user interacts with the inputs via the labels in the html.

**Review by hkang1 — COMMENTED** [review]
Ok sweet was able to get it to build with your fork and changes!

There's just the final complaint (severity level 6) of having two input with the same `id` value of `search-input`.

Screenshot 2023-07-20 at 2 22 13 PM

**Review by hkang1 — APPROVED** [review]
LGTM thanks for the changes!

**Pull request merged**
