### PR TITLE
fix: Single-point tooltip closes when mouse exits chart [WEB-1541]

### PR DESCRIPTION
**Pull request by mapmeld**
## Description

Turns on the `closeOnMouseExit` option on chart tooltip. This is especially helpful for single-point charts where the tooltip never closed.

## Test Plan

Using latest-main backend,
- Go to `/det/projects/1/experiments` , with the new glide table
- Filter name to include `trees`, this includes experiments which end by reporting a validation metric one time
- Select one of the tree experiments

Screen Shot 2023-08-08 at 3 54 50 PM

- Confirm there is a single validation metric point
- Confirm tooltip appears when mouse enters, and disappears when mouse exits the chart

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by mapmeld** [comment]
Can you also verify this resolves WEB-1540, where the tooltip stayed when exiting chart by moving the mouse up or down

**Review by keita-determined — COMMENTED** [review]
its better than before, but still see the issue

https://github.com/determined-ai/determined/assets/109113616/e113cda4-cb16-46c1-a95b-1fb3723710b9

**Comment by mapmeld** [comment]
I think this is showing that hovering over any plot in a ChartGrid shows the tooltip on all plots. I think this is what we intended for the metrics ChartGrid.
We have two possible fixes:
- onmouseout any LineChart should hide tooltip on all plots of a ChartGrid
- the ChartGrid should have an option not to share tooltips between LineCharts

**Comment by mapmeld** [comment]
alright latest commit goes with "onmouseout any LineChart should hide tooltip on all plots of a ChartGrid"

**Review by keita-determined — COMMENTED** [review]
> ~~Confirm tooltip appears when mouse enters, and disappears when mouse exits the chart~~

~~A tooltip disappears when cursor is out of chart but not all tooltip disappear. 
If its an expected behavior, let me know~~

commit was deprecated

https://github.com/determined-ai/determined/assets/109113616/b38a0532-3bd9-4479-a919-af9cff96525a

**Review by keita-determined — APPROVED** [review]
LGTM

**Pull request merged**
