### PR TITLE
chore: break apart WorkloadManager [DET-4716]

### PR DESCRIPTION
**Pull request by rb-determined-ai**
## Description

The new layer structure in the harness pipeline is:
 - SocketManager:    reads and writes to websocket (unchanged)
 - TimerLayer:       injects start_time/end_time into responses
 - TensorboardLayer: writes and syncs tensorboard metrics
 - StorageLayer:     prepares and uploads checkpoints
 - WorkloadManager:  sanity-checks and augments metrics responses

Previously, the last four responsibilities were all coded into the
WorkloadManager, even though they have little-to-nothing to do with each
other.

This also deletes the now-pointless Callback interface.

## Test Plan

Previously-existing tests were refactored and should still pass.

Another test was added.

### CODE REVIEW

**Comment by rb-determined-ai** [comment]
@shiyuann has let me know that he wants to review this next week before it is allowed to land.

**Review by dzhu — COMMENTED** [review]
Looks solid, though I'll defer to @shiyuann for the approval, given how little I've looked at the harness lately.

**Comment by shiyuann** [comment]
@rb-determined-ai Since we are switch to pushing architecture, is this PR necessary to the future design? Or does it help clean up the code?

**Comment by rb-determined-ai** [comment]
This PR is unlikely to land; the layers abstraction is near EOL in our harness and the separation will happen but it will look different.

**Pull request closed without merging**
