### PR TITLE
feat: homebrew package.

### PR DESCRIPTION
**Pull request by ioga**
## Description

Experimental homebrew formulas for `determined-master` and `determined-agent`.

## Test Plan

To install the formulas locally, build everything and then use these incantations:
- in `master/`: `make package && cp dist/determined-master_0.19.11-dev0_darwin_amd64.tar.gz $(brew --cache dist/determined-master.rb) && brew reinstall dist/determined-master.rb`
- in `agent/`: `make package && cp dist/determined-agent_0.19.11-dev0_darwin_amd64.tar.gz $(brew --cache dist/determined-agent.rb) && brew reinstall dist/determined-agent.rb`
(probably swap amd64 -> arm64 on apple silicon)

Then, setup postgres (following the `caveats` from `determined-master` installation.

Then start the services:
```
brew services restart determined-master
brew services restart determined-agent
```

## Commentary (optional)

TBD:
- [x] Documentation
- [x] Remove `skip_upload`, make a repo for the formulas
- [ ] Test the release process
- [ ] Test arm64
- [x] Semantics of config modification / install / post_install are not very well documented, so I am not sure if upgrades will be working as expected. Test if upgrades blow away the modified configs.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by erikwilson** [comment]
While testing this out I ran into a weird issue where docker for mac is adding `/host_mnt` to some Volumes (see https://github.com/docker/for-mac/issues/6375), after getting past that by changing the file sharing implementation the trial then errors with:
```
[2023-01-05 23:21:08] [d2bdd881] [23] root: detected 0 gpus (nvidia-smi not found)
<info> [2023-01-05 23:21:08] [d2bdd881] [23] root: rocm-smi not found
<info> [2023-01-05 23:21:08] [d2bdd881] [23] root: detected 0 gpu processes (nvidia-smi not found)
<none> [2023-01-05 23:21:08] [d2bdd881] Traceback (most recent call last):
<none> [2023-01-05 23:21:08] [d2bdd881]   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
<none> [2023-01-05 23:21:08] [d2bdd881]     return _run_code(code, main_globals, None,
<none> [2023-01-05 23:21:08] [d2bdd881]   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
<none> [2023-01-05 23:21:08] [d2bdd881]     exec(code, run_globals)
<none> [2023-01-05 23:21:08] [d2bdd881]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/prep_container.py", line 328, in <module>
<none> [2023-01-05 23:21:08] [d2bdd881]     do_rendezvous(sess, info.allocation_id)
<none> [2023-01-05 23:21:08] [d2bdd881]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/prep_container.py", line 213, in do_rendezvous
<none> [2023-01-05 23:21:08] [d2bdd881]     rendezvous_info = do_rendezvous_rm_provided(sess, allocation_id, r_id)
<none> [2023-01-05 23:21:08] [d2bdd881]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/prep_container.py", line 71, in do_rendezvous_rm_provided
<none> [2023-01-05 23:21:08] [d2bdd881]     resp = bindings.get_AllocationRendezvousInfo(
<none> [2023-01-05 23:21:08] [d2bdd881]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/common/api/bindings.py", line 11863, in get_AllocationRendezvousInfo
<none> [2023-01-05 23:21:08] [d2bdd881]     _resp = session._do_request(
<none> [2023-01-05 23:21:08] [d2bdd881]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/common/api/_session.py", line 36, in _do_request
<none> [2023-01-05 23:21:08] [d2bdd881]     return request.do_request(
<none> [2023-01-05 23:21:08] [d2bdd881]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/common/api/request.py", line 182, in do_request
<none> [2023-01-05 23:21:08] [d2bdd881]     raise errors.APIException(r)
<none> [2023-01-05 23:21:08] [d2bdd881] determined.common.api.errors.APIException: {"error":{"code":13,"reason":"Internal","error":"1 error occurred:\n\t* found 0 rendezvous addresses instead of 1 for container d2bdd881-f48b-4dc6-90db-ecda4418cfd5; dropping rendezvous addresses []\n\n"}}
<none> [2023-01-05 23:21:08] [d2bdd881]
<error> [2023-01-05 23:21:08] || ERROR: Trial (Experiment 11) was terminated: allocation failed: resources failed with non-zero exit code: container failed with non-zero exit code: 1 (exit code 1)

```

**Comment by erikwilson** [comment]
Another interesting thing that I found is that `devcluster` will use the homebrew version of postgresql rather than the containerized version which is launched.  This is probably a bug which should be fixed in `devcluster`.

**Review by tara-det-ai — COMMENTED** [review]
applied one commit to fix some grammar and capitalization

**Comment by erikwilson** [comment]
Looks good, you probably want to rebase to work around the `test-e2e-managed-devcluster` test failure, and looks like the docs might need reformatting.

**Review by erikwilson — APPROVED** [review]

**Comment by ioga** [comment]
will merge this over unrelated lint-python failure.

**Pull request merged**
