### PR TITLE
fix: workspace list pagination [WEB-664]

### PR DESCRIPTION
**Pull request by julian-determined-ai**
## Description

fix: workspace list pagination [WEB-664]

Adds a listener to the `fetchWorkspaces` function in order to immediately trigger updates when table settings are changed. 

## Test Plan

1. Navigate to the workspace list page. 
2. Change the table page number and ensure the table immediately and correctly updates.
3. Change the table "/ page"  number and ensure the table immediately and correctly updates.

## Checklist
- [x] Changes have been manually QA'd
~- [ ] User-facing API changes need the "User-facing API Change" label.~
~- [ ] Release notes should be added as a separate file under `docs/release-notes/`.~
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
~- [ ] Licenses should be included for new code which was copied and/or modified from any external code.~

[WEB-664]: https://determinedai.atlassian.net/browse/WEB-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by keita-determined — COMMENTED** [review]
it works good as non-admin user.
but i dont see anything as admin
image

API errorr
```
{error: {code: 3, reason: "InvalidArgument", error: "offset out of bounds"}}
{code: 3, reason: "InvalidArgument", error: "offset out of bounds"}
```

**Comment by ClaireNeveu** [comment]
This only works because `fetchWorkspaces` isn't a stable reference but that won't be true if this is switched to a store. Why not subscribe to the offset since that's the value that's changing?

**Comment by julian-determined-ai** [comment]
@keita-determined I am unable to recreate your issue. Can you give me any steps to reproduce this? Does it simple happen for you whenever you try to access the workspace list page as a non admin user for any user you try? Does it simply never load?

**Comment by keita-determined** [comment]
> @keita-determined I am unable to recreate your issue. Can you give me any steps to reproduce this? Does it simple happen for you whenever you try to access the workspace list page as a non admin user for any user you try? Does it simply never load?

I tested on Chrome with private mode. before i tested it, i ran `make all` just in case.

https://user-images.githubusercontent.com/109113616/205396643-d4a5ce23-69dd-4e47-990b-468ebdb850cd.mov

i could reproduce it on Netlify as well. 
On netlify,
- login as admin
- Go to workspace
- click list view
- change pagination
- refresh page

**Review by keita-determined — APPROVED** [review]

**Pull request merged**
