### PR TITLE
build: remove unneeded build-bindings dependencies

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

since we now commit our generated code for WebUI tests don't need to depend on `build-bindings`
anymore

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by hamidzr** [comment]
> if we commit the generated code, can we rip out build-bindings altogether from everywhere in ci? perhaps except for lint-react which intentionally builds them to check they've been rebuilt

yeah good catch. we can probably do that let me see.

**Comment by hamidzr** [comment]
leaving on in build-e2e to test that we can build bindings.
this is tested in lint-react but it's cheap and might be good
to have its own representation.

We also want to testing bindings out of react and into the bindings
module in a separate pr.

**Comment by ioga** [comment]
> 
> 
> leaving on in build-e2e to test that we can build bindings.
> this is tested in lint-react but it's cheap and might be good
> to have its own representation.
> 
> We also want to testing bindings out of react and into the bindings
> module in a separate pr.

I'd remove it from `test-e2e`, I really think having them in `lint` is sufficient. `lint` runs on every commit as well, why burn extra circleci hours.

**Comment by hamidzr** [comment]
hmm if we had a "build to make sure it builds" workflow I'd put it there alongside build storybook

**Comment by ioga** [comment]
the lint requirement "make sure the build is up to date" ends up being strictly stronger than "make sure it builds".

**Review by ioga — APPROVED** [review]

**Pull request merged**
