### PR TITLE
feat: Replace useModal with updated Modal component [WEB-1828] [WEB-1891]

### PR DESCRIPTION
**Pull request by mapmeld**
## Description

Use the updated Modal component ( https://github.com/determined-ai/hew/pull/77 ) to replace Checkpoint and HyperparameterSearch modals

The HyperparameterSearch modal is easier; we just send a custom footer and update CSS.

Checkpoint modal has a few issues:
- in latest-main, creating a new model closes the previous form and doesn't register the MV to this new model, so it should be updated
- in some locations the Modal is being redrawn when the table updates
- the model fetch code is moved to the outside, but we would prefer it to be inside the modal code

WEB-1891: hparam max slots can be 0 without flagging an error

## Test Plan

- In an experiment, create a new hyperparameter search
- In a completed experiment with checkpoints, register the checkpoint to a model

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by julian-determined-ai — CHANGES_REQUESTED** [review]
Could we update the footer styling on the hyper parameter search modal so that it is more in line with our usual styling?

Screen Shot 2023-12-18 at 9 51 11 AM

**Comment by mapmeld** [comment]
Oh, that comes from the updates we made to the footer in Hew. Was able to remove some antd and CSS now that we can use the default Hew CSS.
Screen Shot 2023-12-18 at 11 26 01 AM

**Comment by julian-determined-ai** [comment]
@mapmeld 

what do we expect to happen when this "New Model" button is pressed? 

BF68F6DD-CF09-4889-8DAB-96FE84A283D1_4_5005_c

**Comment by mapmeld** [comment]
ok I added some callbacks so the Checkpoint Flag -> Register Checkpoint -> New Model -> register to new model works

**Review by julian-determined-ai — APPROVED** [review]
LGTM!

**Pull request merged**
