### PR TITLE
fix: jq error changing ntbcs priority

### PR DESCRIPTION
**Pull request by eecsliu**
## Description
Because notebooks, tensorboards, commands, and shells are not persisted, we'll prevent users from modifying them for now and instead ask them to terminate the instances if they wish to modify the priority.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by eecsliu** [comment]
There are other priority change messages being addressed here that are not affected by the job queue. Should I catch those as well?

**Comment by eecsliu** [comment]
This is the cleanest way of erroring out on submission because any deeper and we lose information on whether or not the job is an experiment or command.

**Review by hamidzr — CHANGES_REQUESTED** [review]
Thanks for putting this up. I added some comments below

- messaging: "not supported" instead of unable to? and a smaller comment on whether we want to include instructions on what they should do as an api response.
- it'd be more changes but we might want to return an error and leave responding to the caller as it would probably double respond this way
```
	case *apiv1.SetNotebookPriorityRequest:
		c.setPriority(ctx, int(msg.Priority))
		ctx.Respond(&apiv1.SetNotebookPriorityResponse{Notebook: c.toNotebook(ctx)})
```
- as is it'll still go ahead and set the priority, notify the rm, etc

**Comment by eecsliu** [comment]
my bad, didn't test after the refactor. Refactoring again

**Review by hamidzr — APPROVED** [review]

**Pull request merged**
