### PR TITLE
feat: Add remote user settings to Users table [WEB-1798]

### PR DESCRIPTION
**Pull request by mapmeld**
## Description

In an EE/RBAC environment,
- Adds a sortable "Remote" column to Users table
- Create/edit user modal has a Remote toggle
- Remote users do not have option to change their password in WebUI (message is: "Remote user cannot change password from WebUI")

## Test Plan

In an EE/RBAC environment,

As an admin, visit `/det/admin/user-management` and see the Remote column (most rows say Local)
Create a new user. Set the "Remote" toggle on. Create another user with the "Remote" toggle off.
Check that both users appear in the users table with correct Local/Remote values
Change Remote status on a user
Test sort on the Remote column

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by stoksc — APPROVED** [review]
backend +1

**Review by gt2345 — COMMENTED** [review]
Overall works as expected!

Could you please look into why the order in the table is different from the order from the API response? Note that user `remote1` should be the first but instead it's last.
Screenshot 2023-11-13 at 12 18 47 PM

Should we change the success message when creating a remote user?
Screenshot 2023-11-13 at 12 23 26 PM

At the group tab, should we somehow denote an user is remote or not? 

I don't have a personal preference, but the ticket mentioned a checkbox for selecting remote in the modal?

**Comment by mapmeld** [comment]
OK I made 2 fixes: reversed local sort order, and updated the toast message for remote users.
I think the toggle is the right way for remote users instead of checkbox. The same modal has an Admin on/off toggle on OSS

**Review by gt2345 — APPROVED** [review]
LGTM

**Pull request merged**
