### PR TITLE
docs: clarify k8s default pod spec behavior

### PR DESCRIPTION
**Pull request by eecsliu**
## Description
Added a short blurb clarifying the behavior of custom pod specs.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Review by vishnu2kmohan — APPROVED** [review]

**Review by neilconway — COMMENTED** [review]
I'm still a bit confused here -- what is the set of "necessary" fields, and what values will Determined use for them?

**Comment by eecsliu** [comment]
> I'm still a bit confused here -- what is the set of "necessary" fields, and what values will Determined use for them?

There are a bunch of fields that Determined, most of them can be described as environment variables and pod metadata.

**Review by neilconway — APPROVED** [review]

**Comment by eecsliu** [comment]
@neilconway I thought about the wording a little more - what do you think about something like this instead: 

"Fields that are not specified will remain at their default Determined values."

Do you think maybe this an easier way of breaking it to the user?

**Comment by neilconway** [comment]
@eecsliu sgtm!

**Pull request merged**
