### PR TITLE
fix: fix det e describe on parsing old experiment labels [DET-5487]

### PR DESCRIPTION
**Pull request by hamidzr**
If the config has a key name "labels" and the value is
None det e describe would fail.

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by hamidzr** [comment]
release notes: not sure if this existed in the previous releases

**Comment by hamidzr** [comment]
I confirmed that it shows up in `CLI version 0.14.5`

**Comment by rb-determined-ai** [comment]
re release notes: I expect that it didn't exist before.

**Comment by rb-determined-ai** [comment]
> I confirmed that it shows up in CLI version 0.14.5

You mean, that the cli 0.14.5 fails against a 0.14.5 master?  Or the old cli fails against a new master?  I think the only path where labels can marshal to `none` is with the new expconf version of `labels`.

**Comment by hamidzr** [comment]
> > I confirmed that it shows up in CLI version 0.14.5
> 
> You mean, that the cli 0.14.5 fails against a 0.14.5 master? Or the old cli fails against a new master? I think the only path where labels can marshal to `none` is with the new expconf version of `labels`.

aah yeah I only downgraded the cli

**Comment by hamidzr** [comment]
It did not fail against a matching 0.14.5 master

**Pull request merged**
