### PR TITLE
feat: display workspace icon in ProjectCard

### PR DESCRIPTION
**Pull request by johnkim-det**
## Description

WEB-949

Display icon for workspace below project name on ProjectCards on the dashboard.

Screen Shot 2023-03-03 at 12 10 18 PM

## Test Plan

On dashboard:
- [ ] Project Cards should display a workspace icon
- [ ] Icon should display tooltip on hover
- [ ] The "Uncategorized" project should not display a workspace icon

On workspace details page:
- [ ] Project Cards should not display a workspace icon here

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by ClaireNeveu** [comment]
@EmilyBonar Is there existing code that will do the UI you propose?

**Comment by EmilyBonar** [comment]
@ClaireNeveu No, not completely. However, if I were to point it I'd say that it's a 0 engineering day solution. I threw together that screenshot in the browser inspector in ~10 minutes, and I think recreating it in code should take an hour at the absolute max.

**Comment by ClaireNeveu** [comment]
Another option is the workspace sqircle in the bottom right, that seems pretty straightforward

**Comment by ClaireNeveu** [comment]
Okay, let's do this for now. We'll just put the sqircle underneath the project name with a tooltip showing the workspace name.
Screen Shot 2023-03-02 at 13 02 04

**Comment by EmilyBonar** [comment]
While I agree that that's better than the current state on master or the initial proposed solution, I'm failing to see it as an improvement over my suggestion. It requires 90% of the same work but requires more effort to learn the workspace name, and also adds a bunch of blank space to the right of the squircle. Finally, while this might just be me, I feel that the workspace information being above the project name flows better given the hierarchical relationship between workspaces and projects.

**Comment by ClaireNeveu** [comment]
We'll have a proper design for this eventually, for now I just want to drop an existing component into the card. This isn't a permanent design.

**Review by ClaireNeveu — CHANGES_REQUESTED** [review]
See above comment

**Review by ClaireNeveu — APPROVED** [review]

**Pull request merged**
