### PR TITLE
fix: missing `key` for rows

### PR DESCRIPTION
**Pull request by keita-determined**
## Description

[DET-7827]

## Test Plan
- Check if there is no key warning in  project list in workspace tab

## Commentary (optional)
When I tried to a make duplicate name project, I got an error that says I can't make duplicate name. I believe name is a good candidate for key

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-7827]: https://determinedai.atlassian.net/browse/DET-7827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by trentwatt — COMMENTED** [review]
I agree that we don't allow duplicate names, but `project.id` seems a more natural fit.

**Comment by keita-determined** [comment]
> I agree that we don't allow duplicate names, but `project.id` seems a more natural fit.

I think `project.id` isn't available for `InteractiveTable` in this case.

**Comment by trentwatt** [comment]
using `project.id` would correspond to passing `rowKey="id"` since the individual row records are the projects themselves. does that not work?

**Comment by keita-determined** [comment]
It worked with `id`. id wasnt in the columns, so I assumed I cant use it...

**Pull request merged**
