### PR TITLE
fix: Wrap older modals in theme class [WEB-1824]

### PR DESCRIPTION
**Pull request by mapmeld**
## Description

Applies system/light/dark theme to hyperparameter, notebook, or any old-style modal still inside `src/hooks/useModal`

## Test Plan

Switch to dark mode.
In a single-trial experiment, open the Hyperparameter tab, then click the Hyperparameter Search button
The background should be solid, and the title font-family should come from a CSS variable

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by julian-determined-ai — COMMENTED** [review]
Could you also update the GalleryModal?

**Comment by johnkim-det** [comment]
This fixes the Hyperparameter Search modal, but it actually looks like the "Use in Notebook" modal doesn't use the `useModal` hook, it just imports and uses the antd `Modal` directly. 

So I think we either need to apply the theme class to any direct imports of antd Modals, or replace those with hew Modals.

**Comment by johnkim-det** [comment]
I think we want to think about the long-term solution, but probably the simplest fix for release is to just import `useTheme` and apply `themeClass` to all of these:

Screen Shot 2023-11-16 at 11 14 27 AM

**Comment by mapmeld** [comment]
@johnkim-det I think we had the same idea to search - the latest commit extends this to other uses of Antd Modal except for the Omnibar help (because it's not a function component and can't call useTheme...)

**Comment by ClaireNeveu** [comment]
@mapmeld Can you make a ticket to migrate these?

**Comment by mapmeld** [comment]
@ClaireNeveu ok I made 3 tickets, because some are more complex than others

**Pull request merged**
