### PR TITLE
fix: add fp16 flags to hf ds examples

### PR DESCRIPTION
**Pull request by garrett361**
## Description
Adds `--fp16` flags to the entrypoints of our HuggingFace Trainer examples when using DeepSpeed, in order to use the more-efficient mixed-precision training.

## Test Plan

`cd` into both examples under `/examples/hf_trainer_api/` and verify that the experiments will run without erroring via `det e create deepspeed.yaml .`. If a CUDA out-of-memory error is hit, try reducing the `--per_device_train_batch_size 8` value in the `entrypoint`.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by ighodgao** [comment]
Vision example works fine, but getting CUDA OOM with the language example

`RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 1; 14.62 GiB total capacity; 13.15 GiB already allocated; 20.00 MiB free; 13.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by ighodgao** [comment]
Language modeling example works with batch size 2, maybe we should update the file? Otherwise good to go

**Review by ighodgao — CHANGES_REQUESTED** [review]
The only change that I think is needed is setting batch size to a lower value (e.g. 2) in the language model example. Otherwise looks good

**Comment by garrett361** [comment]
What GPUs were you using?

**Comment by garrett361** [comment]
Yeah, the current `--per_device_train_batch_size 8` value are just the HF defaults and would run fine on more recent GPUs. So, if you think it's ok, I would leave those args unchanged.

**Review by ighodgao — APPROVED** [review]

**Pull request merged**
