### PR TITLE
test: fix local time tests [DET-7449]

### PR DESCRIPTION
**Pull request by hkang1**
## Description

PROBLEM:
tests dealing with local time is failing because the local time conversion doesn't take Daylight Savings Time difference into account.

SOLUTION:
use native `dayjs.local()` to automatically handle DST

## Test Plan

- [ ] check that the datetime tests pass locally
- [ ] check that the datetime tests pass in CI

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hamidzr** [comment]
hmm, so it was an issue with the test and not our utility?

**Review by hamidzr — APPROVED** [review]
thanks for taking this on. tests pass locally for me. as long as [this is a correct assumption](https://github.com/determined-ai/determined/pull/4503#issuecomment-1179341494) ship it! 🚀

**Review by gt2345 — APPROVED** [review]
Works great

**Comment by hkang1** [comment]
> hmm, so it was an issue with the test and not our utility?

I wrote this test a while back when writing a bunch of utility tests, but I'm not sure why this is coming up now. DST being the issue and failing locally, this should have failed a while ago. 🤷

**Pull request merged**
