### PR TITLE
chore: revert "fix: use theme var in Avatar stylesheet [DET-8237] (#5109)"

### PR DESCRIPTION
**Pull request by hamidzr**
This reverts commit 21e29b8dbb8119baea9d53a800d34cd3b4e97177.

https://determined-ai.slack.com/archives/C03H5KZPU30/p1665091019418839

## Checklist
- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [x] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

### CODE REVIEW

**Comment by hamidzr** [comment]
on upstream: https://github.com/determined-ai/determined/tree/rev-avatar-text-color

**Comment by keita-determined** [comment]
Rebasing the latest master will fix the test case failing

**Review by trentwatt — APPROVED** [review]

**Comment by hamidzr** [comment]
wait did I not rebase?

**Comment by hamidzr** [comment]
failed test passed locally I'll merge this in the morning.

**Pull request merged**
