### PR TITLE
feat: remove clientside salting and hashing [DET-4215]

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

this removes salting and hashing from webui. 
the accompanying backend change will be added here

## Commentary (optional)

https://github.com/determined-ai/determined/pull/1333 will get merged into this branch

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by hamidzr** [comment]
e2e tests should break.

**Comment by armandmcqueen** [comment]
I feel like I'm missing some context here. This code looks like we would be sending a plaintext password to the master? That doesn't sound right.

**Comment by stoksc** [comment]
@armandmcqueen
> This code looks like we would be sending a plaintext password to the master?
Yes it would, this standard practice [1]. If you were to hash it on the client side and send that instead, someone can just as easily intercept the hash and use it to login instead, just as now they can intercept the password.

[1] https://security.stackexchange.com/questions/53594/why-is-client-side-hashing-of-a-password-so-uncommon

**Review by armandmcqueen — APPROVED** [review]

**Comment by stoksc** [comment]
@hamidzr want to close this for now?

**Pull request closed without merging**
