### PR TITLE
fix: Properly set log viewer height

### PR DESCRIPTION
**Pull request by gt2345**
## Description

Since we use `LogViewer` at multiple places, we should be able to set the height for each of them individually.
Based off Hew [changes](https://github.com/determined-ai/hew/pull/67).

## Test Plan

Master Log:
before:
Screenshot 2023-11-30 at 1 36 26 PM

After:
Screenshot 2023-11-30 at 1 35 42 PM

Trial Log:
before:
Screenshot 2023-11-30 at 1 36 14 PM

After:
Screenshot 2023-11-30 at 1 35 55 PM

Task Log:
before:
Screenshot 2023-11-30 at 1 36 39 PM

After:
Screenshot 2023-11-30 at 1 35 33 PM

## Checklist

- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

WEB-1864

### CODE REVIEW

**Comment by ashtonG** [comment]
is there a way to do this that doesn't require us knowing the height of the page header ahead of time? Otherwise we'll have to know to update these when the related header changes and causes this issue again.

**Comment by keita-determined** [comment]
Looks like https://github.com/determined-ai/hew/pull/69 is the pr to fix the issue.

**Comment by ashtonG** [comment]
@gt2345 @keita-determined that's a good point. that said, we do have

1) a way to ensure an element fills the remaining space of its parent (flexbox, grid, etc)
2) a way to report the current size of an element (useResize)

can we combine the two?

**Comment by keita-determined** [comment]
Possibly? Do you mean combining these two in OSS side or hew side? If thats in OSS, we might need to implement the similar things in some places that use logviewer, so probably switching library is more straightforward overall?

**Comment by ashtonG** [comment]
I was thinking of combining the layout and hooks in OSS. I agree that long-term, switching the windowing library to something that handles dynamic dimensions better is the right solution, but the switch should be its own work, because there are knock on questions an effects to address that will make the hew PR more complicated (i.e. ChartGrid also uses react-window -- do we change that as well? are tests affected? are these changes backwards compatible or do we need to block other updates?). We're already addressing the issue at all the call points in OSS, this is just using a different method to calculate the height we pass through to the logviewer.

**Pull request closed without merging**
