### PR TITLE
fix: reflect data immediately in model page and model version page

### PR DESCRIPTION
**Pull request by keita-determined**
## Description
[WEB-1016]
- Data will be reflected immediately after editting name and/or description
- Description is now in modal to edit

## Test Plan
- Check if data is reflected immediately after editting name and/or description
- Check if description in edit modal works in model and model version page

## Checklist

- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

[WEB-1016]: https://hpe-aiatscale.atlassian.net/browse/WEB-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mapmeld** [comment]
I think it's good to change these inputs to work like before,
but I thought the main idea was to use a store / observable for models and model versions?

**Comment by keita-determined** [comment]
> I think it's good to change these inputs to work like before, but I thought the main idea was to use a store / observable for models and model versions?

in #6082, we've decided to move name and description into modal. i dont think the main idea is not about store in this case so far because we dont have store for models yet afaik. I believe the change should reflect immediately with the current implementation.

**Review by mapmeld — APPROVED** [review]
LGTM then ✅

**Comment by ClaireNeveu** [comment]
@keita-determined Can you make a ticket to create a matching store if you don't want to do it in this ticket?

**Pull request merged**
