### PR TITLE
fix wrong spelling in _index.rst

### PR DESCRIPTION
**Pull request by simonyangcj**
## Description

Just fix a simple spelling issue on index page

### CODE REVIEW

**Comment by simonycj** [comment]
FYI

￼

￼

￼

Simon Yang

**Comment by ighodgao** [comment]
Hi @simonycj, please start the Contributor License Agreement process before we can merge this. Please go [here](https://www.determined.ai/cla/) and sign the form, then email it to determined-cla@hpe.com. Then we can add you to the contributor list and merge this PR.

**Comment by simonyangcj** [comment]
> Hi @simonycj, please start the Contributor License Agreement process before we can merge this. Please go [here](https://www.determined.ai/cla/) and sign the form, then email it to [determined-cla@hpe.com](mailto:determined-cla@hpe.com). Then we can add you to the contributor list and merge this PR.

Of course I do it now

**Comment by tara-det-ai** [comment]
replaced by #8768

**Comment by rb-determined-ai** [comment]
@cla-bot[bot] check

**Comment by rb-determined-ai** [comment]
@simonyangcj I'm sorry, it looks like we dropped the ball after you submitted your CLA.  That wasn't intentional.  We appreciate your contribution and we've adjusted our internal processes so it shouldn't happen again.

Also, for next time, it looks like you submitted your CLA as @simonyangcj but the commit you submitted was authored by @simonycj.  That's why the cla-bot still is rejecting this PR.  You'll either need to commit as @simonyangcj or submit a CLA as @simonycj next time.

Thank you for taking the time to contribute!

**Pull request closed without merging**
