### PR TITLE
chore: add DatePicker to UI Kit [WEB-1674]

### PR DESCRIPTION
**Pull request by mapmeld**
## Description

Moves `components/DatePicker` to our UI Kit. Mostly a wrapper around Antd DatePicker (adds a label)

Benefits
- limits the expanse of options to the component
- removes some complexity where some pages used Antd directly and some used `components/DatePicker`

## Test Plan

- Confirm all DatePicker uses go through UI Kit
- DatePicker appears correctly on `/det/design` with a good set of options- 
- While logged in as admin, in Cluster page, CSV export modal has a usable DatePicker (this is one area we replace minWidth with width)

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by keita-determined** [comment]
since this is UIKit related PR, i'll assign someone who is more familiar with it

**Review by ClaireNeveu — CHANGES_REQUESTED** [review]
The picker needs to support Dates and DateTimes. In the preview I see Dates, Months, and Years.

**Comment by mapmeld** [comment]
Added `showTime` prop and demo 
Screen Shot 2023-10-02 at 4 03 15 PM

**Review by ClaireNeveu — CHANGES_REQUESTED** [review]
You can get rid of the month and year variations, we don't need those.

**Comment by mapmeld** [comment]
In `ClusterHistoricalUsageFilters` we do have a month picker. I could make that a flag or continue using antd's picker prop.

**Comment by ClaireNeveu** [comment]
Ok, let's just remove the year then.

**Review by ClaireNeveu — APPROVED** [review]

**Pull request merged**
