### PR TITLE
chore: Reduce default RDS capacity and enable auto pause. [DET-4220] [DET-4219]

### PR DESCRIPTION
**Pull request by justin-determined-ai**
## Test Plan

I tested using `det-deploy` and confirmed it set the minimum to 2 and maximum to 8. The idle timeout works, and when the DB is scaled to 0, it takes ~30s-1m for the first master request to return as the DB spins backup.

## Commentary (optional)

Many of our development instances don't need a large-sized RDS minimum, and I've added an auto-pause timeout of one hour.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by justin-determined-ai** [comment]
I'm still in the process of testing this

**Comment by justin-determined-ai** [comment]
I tested it, aside from an unrelated bug that may keep DB connections open, this works. When reconnecting, there's a period of ~30s-1m where the master is unresponsive, but then the app resumes as normal.

**Comment by davidhershey** [comment]
It would be nice if this was configurable via the CLI.  Otherwise I'm cool with this change.

**Comment by justin-determined-ai** [comment]
@davidhershey yeaaaah I'm gonna need a ship it if you're cool with it :)

**Review by davidhershey — APPROVED** [review]

**Pull request merged**
