### PR TITLE
fix: filter out crazy trials [DET-4782]

### PR DESCRIPTION
**Pull request by hkang1**
## Description

Extremely large metric values found in learning curve trials causes the uplot charts to break. Filter out any trials that have metric values that exceed 100,000 in value.

## Test Plan

check to make sure experiment 725 on the latest-master loads ok when the metric is set to `[Training] loss`

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by hamidzr** [comment]
does this come after https://github.com/determined-ai/determined/pull/1796 ? this is deleting the experiment details pages

**Review by hamidzr — APPROVED** [review]
Code LGTM. Assuming users are not going to find real value in metric points with values outside the `ALLOWED_METRIC_VLAUE` range and won't really get confused with not seeing those here, this would be a good and easy improvement to make the charts more usable. cc @vishnu2kmohan 

for a more complicated, less performant solution, employing outlier detection could be an option for the future :thinking:

**Comment by vishnu2kmohan** [comment]
> Assuming users are not going to find real value in metric points with values outside the `ALLOWED_METRIC_VALUE` range

Might we please log a console warning that we've encountered such an outlier (and also capture such instances via Telemetry, if it makes sense)?

I'm still a little concerned that there may arise a situation where a metric may genuinely lie outside and that we are dropping it due to an implementation constraint.

cc @ahj-determined

**Comment by hkang1** [comment]
> Might we please log a console warning that we've encountered such an outlier (and also capture such instances via Telemetry, if it makes sense)?
> 
> I'm still a little concerned that there may arise a situation where a metric may genuinely lie outside and that we are dropping it due to an implementation constraint.

@vishnu2kmohan this is only the reporting end when displaying the learning curve. We're not actually dropping metric values from the experiment. If we want to log such a case, it would make sense for the backend to capture this when it encounters it there. uPlot does not render numbers in the billions either, and talking with @katport, if the metric values are exceeding such a high value, it's more likely that something went wrong.

**Comment by hkang1** [comment]
> does this come after #1796 ? this is deleting the experiment details pages

rebased to remove all those intersecting commits

**Comment by leeoniya** [comment]
> uPlot does not render numbers in the billions either

this sounds odd; it can certainly render values that high: https://jsfiddle.net/0mvdktqf/

if you want to squash spikes, you can tweak y scale auto-ranging (e.g. set soft max / hard max): https://leeoniya.github.io/uPlot/demos/soft-minmax.html

or use log scales: https://leeoniya.github.io/uPlot/demos/log-scales2.html

might also want to check out these recent discussions:

https://github.com/grafana/grafana/issues/979
https://github.com/grafana/grafana/pull/30326

cheers!

**Comment by hkang1** [comment]
> > uPlot does not render numbers in the billions either
> 
> this sounds odd; it can certainly render values that high: https://jsfiddle.net/0mvdktqf/
> 
> if you want to squash spikes, you can tweak y scale auto-ranging (e.g. set soft max / hard max): https://leeoniya.github.io/uPlot/demos/soft-minmax.html
> 
> or use log scales:
> https://leeoniya.github.io/uPlot/demos/log-scales2.html
> 
> might also want to check out these recent discussions:
> 
> [grafana/grafana#979](https://github.com/grafana/grafana/issues/979)
> [grafana/grafana#30326](https://github.com/grafana/grafana/pull/30326)
> 
> cheers!

Hey @leeoniya thanks for the comment and the suggestions! Looks like it rendered just fine with the single digits and the billion+ values. I'll try to nail down exactly what the issue is, but introduction of time series with these giant numbers among "normal" series with values between 0 ~ 10 is triggering a blank chart without an error.

**Pull request closed without merging**
