### PR TITLE
fix: logs shouldn't overlap when switching tabs [WEB-1915]

### PR DESCRIPTION
**Pull request by EmilyBonar**
## Description
Previously, if you switched between a tab container a LogViewer and another tab, the logs would sometimes overlap on a single line until new logs streamed in. By destroying the tab contents on switching, this doesn't happen anymore, at the cost of an additional API call to refetch the logs.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by julian-determined-ai** [comment]
@EmilyBonar one thing I am seeing is an infinite "no logs to show" message: 


https://github.com/determined-ai/determined/assets/103522725/0f7e8905-3089-4a34-b265-a2f8e927a4c4

**Comment by julian-determined-ai** [comment]
I can't seem to reproduce the issue anywhere else so looks like it was introduced here.

**Review by julian-determined-ai — CHANGES_REQUESTED** [review]
I can't seem to reproduce the issue elsewhere, so looks like it was introduced here.

**Comment by EmilyBonar** [comment]
Investigated further bug didn't come up with a solution. Recorded notes in ticket.

**Pull request closed without merging**
