### PR TITLE
fix: allocation rekill shouldn't use time.UTC in fine time checks [DET-9149]

### PR DESCRIPTION
**Pull request by stoksc**
## Description
`time.Now().UTC()` internally calls `t.stripMono()` which makes this check susceptible to clock resets.

## Test Plan
- [???] reproducing this is very hard

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by jerryharrow — APPROVED** [review]
Reason for halving killCoolDown constant and then doubling it in the wait?

**Comment by rcorujo** [comment]
I suppose this is worth a try, but I don't see how the existing behavior would account for Determined not sending anymore Kill messages, unless the system time somehow went back in time significantly.

**Review by rcorujo — APPROVED** [review]

**Comment by jerryharrow** [comment]
> I suppose this is worth a try, but I don't see how the existing behavior would account for Determined not sending anymore Kill messages, unless the system time somehow went back in time significantly.

See Bradley's description of the details here https://determined-ai.slack.com/archives/C04FMDK85U3/p1679420883853279

**Comment by stoksc** [comment]
> I suppose this is worth a try, but I don't see how the existing behavior would account for Determined not sending anymore Kill messages, unless the system time somehow went back in time significantly.

Based on your logs, we definitely entered `a.kill` - and the only way I can see that we enter `a.kill`, don't retry a kill and don't exit is this.

**Comment by stoksc** [comment]
> Reason for halving killCoolDown constant and then doubling it in the wait?

it was just too sensitive. this doesn't change the behavior at all. unless a user is sending kills every 15s.

**Comment by jerryharrow** [comment]
> > Reason for halving killCoolDown constant and then doubling it in the wait?

> it was just too sensitive. this doesn't change the behavior at all. unless a user is sending kills every 15s.

You mean  that it makes the .BeforeCheck too sensitive to timing and it might incorrectly terminate the kill loop?

**Comment by stoksc** [comment]
> > > Reason for halving killCoolDown constant and then doubling it in the wait?

> > it was just too sensitive. this doesn't change the behavior at all. unless a user is sending kills every 15s.

> You mean that it makes the .BeforeCheck too sensitive to timing and it might incorrectly terminate the kill loop?

I mean, it _shouldn't_ now, but idk, figured it didn't hurt, yah.

**Pull request merged**
