### PR TITLE
feat: Add quota limits for helm

### PR DESCRIPTION
**Pull request by fideltak**
## Description
#6431 

## Test Plan
Deploying onth k8s with this helm chart. (HPE Ezmeral Runtime 5.6)

## Checklist

- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Title
User-facing change types:

- feat: new user-facing feature

### CODE REVIEW

**Review by ioga — COMMENTED** [review]
hello, for the sake of the chart usability I'd suggest these entries in `values.yaml` should be optional. 
That is, if they're specified in `values.yaml`, we set `limits` on master and db pods them. if they aren't, we don't.

**Comment by fideltak** [comment]
@ioga 
Yeah, agree with that. I make it optional.

**Review by ioga — APPROVED** [review]
The code is looking good for me. 

Legal aspect: seems like you are an employee of HPE, can you please submit your commits with your `@hpe.com` or `@cray.com` email? This should address the CLA bot complaints.

**Comment by fideltak** [comment]
I changed the author and comitter email address to **hpe.com**.
But it seems cla-bot is strill rejecting...

**Pull request merged**
