### PR TITLE
test: collect det task logs as artifacts for ci jobs

### PR DESCRIPTION
**Pull request by hamidzr**
## Ticket

https://hpe-aiatscale.atlassian.net/browse/RM-237

## Description

collect and save tasks (currently just first trial of an experiment's) logs as ci artifacts for e2e tests.
adds about 4s to each job.

a quick log size estimate as is: looks like each run the total of all the logs collected today is <10MB
we have about 1300 test-e2e workflow runs each 30 days that adds up to about 13GB of storage use that should auto clear as the artifacts age out

## Test Plan

samples: https://app.circleci.com/pipelines/github/determined-ai/determined/56392/workflows/04457f70-98f8-407c-835f-e5bca81a481b/jobs/2630701/artifacts
sample with task logs https://app.circleci.com/pipelines/github/determined-ai/determined/56396/workflows/24e85025-e118-4dd6-b095-301aa6e15dee/jobs/2631032/artifacts
https://app.circleci.com/pipelines/github/determined-ai/determined/56392/workflows/04457f70-98f8-407c-835f-e5bca81a481b/jobs/2630703/artifacts
https://app.circleci.com/pipelines/github/determined-ai/determined/56392/workflows/04457f70-98f8-407c-835f-e5bca81a481b/jobs/2630711/artifacts

I recycled some old code I had to do this. there's probably a better way to authenticate now
## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by davidfluck-hpe — APPROVED** [review]
Approving with some general observations/questions. I won't request any of these changes, but I want to make a note of them (in no particular order).

1. I'm not sure which Determined library functions return errors or throw exceptions, but as it is, I don't see a lot of error handling. How likely is the happy path, and how informative will the resultant error messages be if they break CI?

2. I see a lot of string interpolation/manipulation for paths. Consider Python's [pathlib](https://docs.python.org/3/library/pathlib.html#module-pathlib) for a higher-level interface for working with OS paths.

3. What is the expected log volume?

4. Is there a way to use an existing Determined venv in CircleCI instead of installing `fire` and `determined` each time? The compute cycles add up, and I'd rather install a package once ahead of time instead of on every build.

**Comment by hamidzr** [comment]
Thanks, all good points

> I'm not sure which Determined library functions return errors or throw exceptions, but as it is, I don't see a lot of error handling. How likely is the happy path, and how informative will the resultant error messages be if they break CI?

This one I'm not sure I'm understanding correctly.

> log volume

two optimizations:
- compress the output which is all txt but would take away the browser usability
- only upload on failures

I added a bit to the cmd to make a report on the size.  They only stay around for 30 days afaik

> Is there a way to use an existing Determined venv in CircleCI instead of installing fire and determined each time? The compute cycles add up, and I'd rather install a package once ahead of time instead of on every build.

probably? but also that adds a bit of complexity and reduces the portability of this command. I think it already runs as part of the venv that the parent job sets up and if the pkg is found, it should skip it eg here it doesn't download determined https://app.circleci.com/pipelines/github/determined-ai/determined/56582/workflows/f1305a3a-cd98-4741-a914-6b621ccd0448/jobs/2645863/parallel-runs/0/steps/0-128

**Comment by hamidzr** [comment]
a quick log size estimate as is: looks like each run the total of all the logs collected today is <10MB
we have about 1300 test-e2e workflow runs each 30 days that adds up to about 13GB of storage use that should auto clear as the artifacts age out

**Comment by davidfluck-hpe** [comment]
> This one I'm not sure I'm understanding correctly.

How likely are those Determined library functions to return errors/raise exceptions? Is it possible for any of them to fail and raise an unhandled exception? I don't see much error handling, so I'm wondering if those Determined library functions are always going to succeed, or if there's a possibility that we're not handling errors. For example: `resp = b.get_GetExperiments(self.session, archived=False, states=states)`. Can `get_GetExperiments()` fail? If so, how do we handle it?

**Comment by hamidzr** [comment]
> > This one I'm not sure I'm understanding correctly.
> 
> How likely are those Determined library functions to return errors/raise exceptions? Is it possible for any of them to fail and raise an unhandled exception? I don't see much error handling, so I'm wondering if those Determined library functions are always going to succeed, or if there's a possibility that we're not handling errors. For example: `resp = b.get_GetExperiments(self.session, archived=False, states=states)`. Can `get_GetExperiments()` fail? If so, how do we handle it?

thanks for explaining, I get it now : ) outside of unexpected bugs that I might be adding here the usual network failures should be covered by our default retry logic that all the API calls via our Session gets https://github.com/determined-ai/determined/blob/da9820ea8de6bed43f19d8f4073247e28bffe6e2/harness/determined/common/api/_session.py#L18-L23

**Pull request merged**
