### PR TITLE
chore: add ee helm chart changes to oss

### PR DESCRIPTION
**Pull request by salonig23**
## Description
Add EE helm chart changes to OSS

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by dannysauer — APPROVED** [review]
Looks good either way, but should the release notes from determined-ai/determined-ee#1186 be moved or duplicated to OSS as well?

**Review by carolinaecalderon — CHANGES_REQUESTED** [review]
Needs release note

**Comment by salonig23** [comment]
> Needs release note

Done

**Review by carolinaecalderon — APPROVED** [review]
LGTM, thanks for taking the initiative on this

**Pull request merged**
