### PR TITLE
feat: add `TransferRoles` api

### PR DESCRIPTION
**Pull request by keita-determined**
## Description

WEB-973

Add `TransferRoles` for OSS part

Currently, when a user changes roles, 2 APIs are called which are `v1/roles/remove-assignments` and `v1/roles/add-assignments`. It is not an issue if user changes roles of someone else, but it becomes the issue if the user changes own roles. This PR introduce a new API called `TransferRoles` (we can change name). The API switches to the new role if user has permissions to `add/remove` roles.

If there is a better approach, im open to it

### Plan

```mermaid
gantt
    title Fix Role changing issue
    dateFormat  YYYY-MM-DD
    section TransferRoles
    Add `TransferRoles` for OSS                          :crit, a1, 2023-03-09, 3d
    Implement `TransferRoles` in EE                   :a2, after a1 , 3d
    Fix web and CLI                                               :a3, after a2 , 3d
```

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by ioga** [comment]
can the user add the new role for themselves first, and then remove the old role?

**Comment by keita-determined** [comment]
> can the user add the new role for themselves first, and then remove the old role?

i think this would work, but if `remove-assignments` API fails after `add-assignments`, there would be 2 rows with the same user and different roles. That might lead to a different bug.

**Comment by ioga** [comment]
> i think this would work, but if `remove-assignments` API fails after `add-assignments`, there would be 2 rows with the same user and different roles. That might lead to a different bug.

backend & CLI support having multiple roles per user per scope.

**Comment by keita-determined** [comment]
> 

i didnt know that, then the approach sounds good. i close this PR

**Pull request closed without merging**
