### PR TITLE
chore: updated master location hint

### PR DESCRIPTION
**Pull request by pankaj-mandal**
## Description
Updated hint by referring to check port as well.

## Test Plan

visual inspection of changes.

### CODE REVIEW

**Review by stoksc — APPROVED** [review]

**Comment by pankaj-mandal** [comment]
@stoksc @jerryharrow  How does this PR get merged?

**Comment by stoksc** [comment]
@cla-bot check

**Comment by stoksc** [comment]
@cla-bot check

**Comment by stoksc** [comment]
@cla-bot check

**Pull request merged**
