### PR TITLE
chore: add Toggle component to UI Kit [WEB-841]

### PR DESCRIPTION
**Pull request by EmilyBonar**
## Description
[WEB-841](https://determinedai.atlassian.net/browse/WEB-841?atlOrigin=eyJpIjoiYTYzMjIxYTVkMjUyNGM5Mzg0NWI2ZTU1MzIzNzMyZGUiLCJwIjoiaiJ9)

Adds Toggle component to UI Kit. Also removes `suffixLabel` prop, since this wasn't used in our app.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

[WEB-841]: https://determinedai.atlassian.net/browse/WEB-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ClaireNeveu — APPROVED** [review]
Design looks good

**Review by johnkim-det — APPROVED** [review]
Code lgtm, but this did bring up a question for me: does it make sense to have props/examples for variations that we don't currently have in the app but are somewhat likely to come up in the future (like `disabled`, `size`, `loading` from antd `<Switch>`, or label position)? or would it be better to just add those as we need them?

**Comment by EmilyBonar** [comment]
In general we want to limit variations to what is strictly necessary and only add new ones when required. I would even be open to removing the label entirely and handling it separately when needed, but then you run into a tradeoff between consistency and separation of concerns, and I think that's a topic for another day.

**Comment by ClaireNeveu** [comment]
I do think a standard set of props like `disabled` is good.

**Pull request merged**
