### PR TITLE
feat: remove the conflicting rule

### PR DESCRIPTION
**Pull request by thiagodallacqua-hpe**
## Description

Removes conflicting rule from eslint.

## Checklist
- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [ ] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ClaireNeveu — APPROVED** [review]

**Comment by hamidzr** [comment]
I wonder how did this not happen in the main pr that formatted the whole repo

**Review by keita-determined — CHANGES_REQUESTED** [review]
you don't need to change the rule.
I think you can close this PR

**Comment by keita-determined** [comment]
@ClaireNeveu 
listing and formatting work fine. Thiago just forgot to run `npm install`.

**Comment by hamidzr** [comment]
> @hamidzr I don't get why tests are failing on a PR that just removes an eslint rule. Do you have any insight here?

https://determined-ai.slack.com/archives/CKQ3EV0G6/p1658782829606369

**Comment by ClaireNeveu** [comment]
@hamidzr Ah, so this is because @thiagodallacqua-hpe was working off of a fork?

**Comment by hamidzr** [comment]
> @hamidzr Ah, so this is because @thiagodallacqua-hpe was working off of a fork?

yes as a security feature some tests only run on jobs submitted directly from a branch on this repo to avoid. these tests don't run for all changes.

**Pull request closed without merging**
