### PR TITLE
chore: refactor and test RBAC config policies work [CM-530]

### PR DESCRIPTION
**Pull request by amandavialva01**
## Ticket
[CM-530]

## Description
- Remove "modify globaly config policies" permission from `WorkspaceAdmin` role
- Classify global config policy permissions as `global_only`
- Add RBAC tests for config policies and refactor existing tests
- Move config policies RBAC work into the `configpolicy` package and add configpolicy-specific logging

## Test Plan
CI passes (automated testing).

## Checklist

- [ ] Changes have been manually QA'd
- [ ] New features have been approved by the corresponding PM
- [ ] User-facing API changes have the "User-facing API Change" label
- [ ] Release notes have been added as a separate file under `docs/release-notes/`
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses have been included for new code which was copied and/or modified from any external code

[CM-530]: https://hpe-aiatscale.atlassian.net/browse/CM-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by kkunapuli — APPROVED** [review]
LGTM. I am not familiar with the RBAC code, though, so you are welcome to get a second review from someone who is more familiar if you'd like.

**Review by salonig23 — APPROVED** [review]
LGTM! But one minor comment: why not move global config policy rbac to the configpolicy subfolder as well?

**Comment by amandavialva01** [comment]
> LGTM! But one minor comment: why not move global config policy rbac to the configpolicy subfolder as well?

Great idea! I'll move that over

**Review by carolinaecalderon — APPROVED** [review]
LGTM

**Pull request merged**
