### PR TITLE
chore: use ExitStack to fight indents

### PR DESCRIPTION
**Pull request by rb-determined-ai**
Don't let harness.py become an "indentured" servant.

## Description

We have a bunch of new context managers that are on their way into harness.py and worker_process.py (https://github.com/determined-ai/determined/pull/1482, https://github.com/determined-ai/determined/pull/1403).  Since harness.py and worker_process.py are effectively the "injector" of our dependency injection strategy, they tend to have the property that all context managers are exited at the same time.

We can make writing these files easier to extend (without code churn) by using `contextlib.ExitStack`, which will let you append a context manager to the current list of opened context managers, which will all be closed when the `ExitStack` exits.  No new indent is necessary.

The resulting code does not have `with` statements, but since every context manager we open in the injector code (harness.py and worker_process.py) remains open until the process exits, the `with` statements communicated very little to begin with.

### CODE REVIEW

**Comment by rb-determined-ai** [comment]
I assigned @armandmcqueen because he currently has a PR open that would use this.

But I also requested reviews from @aaron276h @shiyuann and @dzhu (explicitly, not as code owners) because while I think this is a good idea, I have a tingling sense that this is more confusing than it is beneficial.  Please review and lmwyt.

**Review by shiyuann — COMMENTED** [review]
It looks like we used to be static on chaining the contexts but now we transition to a dynamic chain just because we don't like the indents. This seems to make the code harder to read since you have no idea in which order the contexts are without putting very much mental effort. Although you may claim that we always are very careful about where we add a context, I think still it is abusing Python.

**Comment by rb-determined-ai** [comment]
> you have no idea in which order the contexts are without putting very much mental effort

@shiyuann Is this really true?  Does the extra indentation actually make the code clearer in either `harness.py` or `worker_process.py`?

I would claim that in those two files, we actually care very little about the order of the context managers.  And I am not proposing using this object in any other files whatsoever... it would be very unhelpful in most places.

**Comment by shiyuann** [comment]
@shiyuann Is this really true? Does the extra indentation actually make the code clearer in either harness.py or worker_process.py?

Yes. Because when people look at `with` and the indentation, they know it's a context manager and the range it covers. Now, I don't see them at all. I don't think the code is clearer. It's just horizontally shorter.

> I would claim that in those two files, we actually care very little about the order of the context managers. And I am not proposing using this object in any other files whatsoever... it would be very unhelpful in most places.

If you just don't know the 3-level indentation, why not just move the use of context managers out to be separate functions?
Or you could just manually create them rather than using `with` and manually call the `close()` of them when the program exits.

**Comment by rb-determined-ai** [comment]
> Or you could just manually create them rather than using with and manually call the close() of them when the program exits

To do that you'd have to use `try/finally`, which would still result in an equal number of indents.

> Because when people look at with and the indentation, they know it's a context manager and the range it covers

But the point is the literally all exit at the very end... it's not useful information.

> why not just move the use of context managers out to be separate functions

I think this would be *significantly* harder to read, because right now the entire dependency injection happens in a single function, which is wonderful.  If you remember, we used to have the architecture of the harness spread over many files.  I much prefer keeping the dependency injection all together.

**Review by dzhu — COMMENTED** [review]
I've never used [`contextlib.ExitStack`](https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack), but it looks like it might do the same thing as `ContextChain`. Could you check if that's the case?

As for the overall change, I'm currently ambivalent about whether I like the looks of the new way or not. Reducing indentation can be nice when it really gets to be too much, but I don't think anywhere was deep enough to really matter (and my guess would be that there's not that much potential for future deepening). I'd need to stare at it more to get a more concrete feeling.

I think I agree that it should come down to either this or the old way and that the other proposed alternatives are not as good.

**Comment by rb-determined-ai** [comment]
@dzhu absolutely, `ExitStack` is exactly what I want.

Ok, this changes my stance to "I am not sure this is a good idea but there are some real benefits to this strategy" to "this is the right time to use this ExitStack tool from the standard library".

> my guess would be that there's not that much potential for future deepening

I actually think this is not accurate.  #1403 introduces two (a `ProfilingLayer`, and a `stack_dump_thread`), and #1482 introduces another.

In #1403 the indentation was already getting to be too much, and I broke up the dependency injection function into two functions, but I really did not like it.  Seeing @armandmcqueen also was about to add more indentation is what caused me to investigate specialty solutions for what is effectively a specialty usage of `with()` statements.  Normally they denote some block of code that falls inside a context (`with lock:` or `with open() as f:`) but in these functions we just use them as a pythonic way to write cleanup code, and we always exit all context managers when the function exits; we never do anything after some-but-not-all managers have exited.

Another thing I realized from the `ExitStack` docs is that the `maybe_load_checkpoint` context manager does not have to exist at all, since `ExitStack` is perfectly capable of handling variable numbers of context managers (which is not true of `with`).

**Comment by shiyuann** [comment]
talked offline with @rb-determined-ai : 

[`contextlib.ExitStack`](https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack) has such doc:

> A context manager that is designed to make it easy to programmatically combine other context managers and cleanup functions, **especially those that are optional or otherwise driven by input data**.

I think the latter case obviously doesn't apply here. So if we will have many more optional context managers, it makes sense to use this functionality to reduce the complexity of code.  Otherwise, we would be abusing `ExitStack`. 

I am told that we might have 3 more context managers added in the near future and all of the context managers exit at the same place so the indentation will look very bad. Although I think the approach in this PR reduces readability, I am not opposed to it since it affects a very limited range of code.

**Comment by armandmcqueen** [comment]
@shiyuann Can you clarify which option you are endorsing?

I think `ExitStack` is what we are looking for here.

**Comment by shiyuann** [comment]
@armandmcqueen I mean we should wait until we have more context managers.

**Comment by armandmcqueen** [comment]
Gotcha. I don't have a strong preference between 'do nothing' or use `ExitStack`

**Comment by rb-determined-ai** [comment]
I am fine with closing this PR, letting the "pain" build up, and then using `ExitStack`, since I think it will be an obvious improvement at that time.

**Pull request closed without merging**
