### PR TITLE
fix: Button icon spacing

### PR DESCRIPTION
**Pull request by johnkim-det**
## Description

Spacing between icon and text in some buttons is too small. 

Before:
Screen Shot 2023-08-04 at 4 13 40 PM

After: 
Screen Shot 2023-08-04 at 4 14 29 PM

## Test Plan

On new Experiment List page and DesignKit page, make sure all buttons have spacing between icon and text.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

WEB-1472
WEB-1511

### CODE REVIEW

**Comment by julian-determined-ai** [comment]
It looks like "full width" buttons no longer have the text centered inside the button?

Button in this PR:
Screen Shot 2023-08-07 at 12 43 29 PM

Button in current design kit:
Screen Shot 2023-08-07 at 12 44 36 PM

@johnkim-det

**Comment by johnkim-det** [comment]
> It looks like "full width" buttons no longer have the text centered inside the button?
> 
> Button in this PR: Screen Shot 2023-08-07 at 12 43 29 PM
> 
> Button in current design kit: Screen Shot 2023-08-07 at 12 44 36 PM
> 
> @johnkim-det

@julian-determined-ai thanks, should be fixed

**Comment by julian-determined-ai** [comment]
Screen Shot 2023-08-07 at 1 38 17 PM

@johnkim-det it looks like the `Fork` and `TensorBoard` buttons might not look the way we want?

**Comment by johnkim-det** [comment]
@julian-determined-ai updated w fix

**Review by julian-determined-ai — APPROVED** [review]

**Pull request merged**
