### PR TITLE
chore: track dead code [WEB-258]

### PR DESCRIPTION
**Pull request by EmilyBonar**
## Description
Unimported files should be printed to console by running `npm run unimported`. This PR does not remove the dead code, just report it.

Current results:
```
       summary               unimported v1.29.2 (node)
────────────────────────────────────────────────────────
       entry file 1        : src/index.tsx
       entry file 2        : design/index.tsx

       unresolved imports  : 0
       unused dependencies : 2
       unimported files    : 30


─────┬──────────────────────────────────────────────────
     │ 2 unused dependencies
─────┼──────────────────────────────────────────────────
   1 │ fuse.js
   2 │ smoothscroll-polyfill
─────┴──────────────────────────────────────────────────


─────┬──────────────────────────────────────────────────
     │ 30 unimported files
─────┼──────────────────────────────────────────────────
   1 │ src/__mocks__/router.tsx
   2 │ src/components/ActionDropdown/index.ts
   3 │ src/components/AvatarCard/AvatarCard.tsx
   4 │ src/components/AvatarCard/index.ts
   5 │ src/components/ExperimentIcons/Loader.tsx
   6 │ src/components/kit/__mocks__/Tooltip.tsx
   7 │ src/components/kit/internal/UPlot/UPlotChart/drawPointsPlugin.ts
   8 │ src/components/kit/internal/UPlot/UPlotChart/trackAxis.ts
   9 │ src/components/LoadingWrapper.tsx
  10 │ src/components/Markdown.tsx
  11 │ src/components/Table/TableBulkActions.tsx
  12 │ src/components/TextEditorModal.tsx
  13 │ src/components/types.ts
  14 │ src/declarations.d.ts
  15 │ src/e2e/fixtures/auth.fixture.ts
  16 │ src/e2e/fixtures/dev.fixture.ts
  17 │ src/e2e/global-fixtures.ts
  18 │ src/hooks/usePermissions.common.tsx
  19 │ src/hooks/useScroll.ts
  20 │ src/omnibar/Omnibar.tsx
  21 │ src/pages/Cluster/ClusterOverview.table.tsx
  22 │ src/pages/ExperimentDetails/ExperimentDetails.test.mock.ts
  23 │ src/pages/F_ExpList/glide-table/icons.tsx
  24 │ src/quarantineTests.ts
  25 │ src/react-app-env.d.ts
  26 │ src/react-svg.d.ts
  27 │ src/services/api-ts-sdk/custom.d.ts
  28 │ src/setupTests.ts
  29 │ src/utils/set.ts
  30 │ src/vendor/notebook/notebook.js
```

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by ClaireNeveu** [comment]
Why is this needed after https://github.com/determined-ai/determined/commit/32fac33439bf22623c9b7c4b93943438459c98d9?

**Comment by EmilyBonar** [comment]
@ClaireNeveu Ah, I missed that PR. The ticket talked about banning relative imports and I neglected to check that it hadn't already been done. This PR also bans imports like this `./[filename]` which weren't removed before and we might want to get rid of, but I just checked and the unimported command runs fine without doing that. I can go ahead and revert those changes if you don't think they're needed.

I also just found that unimported breaks the build if it finds any unused files, which might be good to turn on eventually, but maybe not right away, so I'm going to remove it from the build step and just have it as a separate npm command.

**Review by hkang1 — COMMENTED** [review]
100% agree that `../` relative paths are horrible because they just make your head spin trying to figure out where they are located (which is solved by [PR 7637](https://github.com/determined-ai/determined/pull/7637) as @ClaireNeveu  pointed out.  I do think that the `./` relative paths are valuable to have because they are references to CSS files and test files that **should** get moved along with the component if if ever gets moved and the paths will still be relevant. Also the `./` path is straight forward as to where the file is actually located, unlike `../`.

**Review by hkang1 — COMMENTED** [review]
The report generated is nice!

I ran `npm run unimported` and here is the report I got:
```
─────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     │ 2 unused dependencies
─────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ fuse.js
   2 │ smoothscroll-polyfill
─────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


─────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     │ 30 unimported files
─────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ src/__mocks__/router.tsx
   2 │ src/components/ActionDropdown/index.ts
   3 │ src/components/AvatarCard/AvatarCard.tsx
   4 │ src/components/AvatarCard/index.ts
   5 │ src/components/ExperimentIcons/Loader.tsx
   6 │ src/components/kit/__mocks__/Tooltip.tsx
   7 │ src/components/kit/internal/UPlot/UPlotChart/drawPointsPlugin.ts
   8 │ src/components/kit/internal/UPlot/UPlotChart/trackAxis.ts
   9 │ src/components/LoadingWrapper.tsx
  10 │ src/components/Markdown.tsx
  11 │ src/components/Table/TableBulkActions.tsx
  12 │ src/components/TextEditorModal.tsx
  13 │ src/components/types.ts
  14 │ src/declarations.d.ts
  15 │ src/e2e/fixtures/auth.fixture.ts
  16 │ src/e2e/fixtures/dev.fixture.ts
  17 │ src/e2e/global-fixtures.ts
  18 │ src/hooks/usePermissions.common.tsx
  19 │ src/hooks/useScroll.ts
  20 │ src/omnibar/Omnibar.tsx
  21 │ src/pages/Cluster/ClusterOverview.table.tsx
  22 │ src/pages/ExperimentDetails/ExperimentDetails.test.mock.ts
  23 │ src/pages/F_ExpList/glide-table/icons.tsx
  24 │ src/quarantineTests.ts
  25 │ src/react-app-env.d.ts
  26 │ src/react-svg.d.ts
  27 │ src/services/api-ts-sdk/custom.d.ts
  28 │ src/setupTests.ts
  29 │ src/utils/set.ts
  30 │ src/vendor/notebook/notebook.js
─────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

So some things might need a bit of tweaking. `fuse.js` looks like it is used by the `omnibar`. `smoothscroll-polyfill` is used by `useScroll` hook.

the UPlot plugins such as `src/components/kit/internal/UPlot/UPlotChart/trackAxis.ts` are actually imported by `TrialChart`, etc.

There are a bunch of `*.d.ts` that should probably just be ignored because they are used directly by Typescript and not imports.

**Comment by EmilyBonar** [comment]
@hkang1 

- You're right, though useScroll isn't actually imported anywhere, so the latter does go unused. For some reason it's not finding that Omnibar is being imported.
- If you look closely you'll see that TrialChart is actually importing the plugins from `components/UPlot/UPlotChart/`, while unimported is complaining about `components/kit/internal/UPlot/UPlotChart/`. The copies in the kit internals are indeed unused.
- Fixed.

**Comment by EmilyBonar** [comment]
I had to special case a few files/directories because of false positives, but I believe that everything reported now is genuinely unused.

**Review by hkang1 — APPROVED** [review]
Sweet the report looks much better thanks!

**Pull request merged**
