### PR TITLE
chore: update cloud AMIs.

### PR DESCRIPTION
**Pull request by neilconway**
This pulls in the recent update to the Nvidia drivers in the AMIs.

### CODE REVIEW

**Comment by neilconway** [comment]
@aaron276h Looks like the E2E test effectively passed (just blocked on the dev-deploy thing which I didn't do).

**Comment by neilconway** [comment]
Will do. For curiosity's sake, why do we need to bump the taskenvs? This change shouldn't change what's in the taskenv images. Or is that just out of an abundance of caution?

**Comment by aaron276h** [comment]
@neilconway Abundance of caution that it won't try to pull down new container images, which are baked into the AMIs. Also keeping it consistent helps avoid issues down the line when we need to bump them again in the future.

**Comment by neilconway** [comment]
Ugh, whoops -- my bad.

**Pull request merged**
