### PR TITLE
docs: port slurm deployment to oss docs

### PR DESCRIPTION
**Pull request by gh-determined-ai**
## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [ ] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gh-determined-ai** [comment]
@jerryharrow @stoksc  Created this so it doesn't get lost. You'll need to review if things work the same way in the OSS environment.

**Comment by stoksc** [comment]
thanks @gh-determined-ai !

**Review by jerryharrow — COMMENTED** [review]
Looks good, but there are a few more changes that need to be pulled as well.

- https://github.com/determined-ai/determined-ee/pull/356 (fix a doc link that changed from oss)
- https://github.com/determined-ai/determined-ee/pull/361 (Add podman)
- https://github.com/determined-ai/determined-ee/pull/366 (fix image tags)

**Comment by gh-determined-ai** [comment]
@jerryharrow  I've incorporated your latest updates and made some minor wording changes.

**Comment by gh-determined-ai** [comment]
@jerryharrow @stoksc I need a stamp or feedback on this fairly quickly. Thanks.

**Review by stoksc — APPROVED** [review]
lgtm

**Pull request merged**
