### PR TITLE
fix: hook inside useMemo warning

### PR DESCRIPTION
**Pull request by gt2345**
## Description

image (2)

## Test Plan

Navigate to task/experiment list, open the console, should not be any error

## Checklist

- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by keita-determined — COMMENTED** [review]
i still see the warnings

image

**Comment by keita-determined** [comment]
also, should we remove `UserRenderer` if we wouldnt use it?

**Comment by gt2345** [comment]
> also, should we remove `UserRenderer` if we wouldnt use it?

@keita-determined  Thank you for catching this. `UserRenderer` was still used in job queue, but now it's removed.

**Review by keita-determined — APPROVED** [review]
LGTM
Thanks for the fix

**Pull request merged**
