### PR TITLE
docs: bumping K8s version to 1.19 for EKS

### PR DESCRIPTION
**Pull request by mluyo3414**
## Description

Bumping K8s version to 1.19 for EKS as 1.15 is not supported anymore.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by hoanghphan — APPROVED** [review]

**Comment by eecsliu** [comment]
I'm still attempting to verify that 1.19 and 1.20 work - but EKS is being troublesome

**Review by eecsliu — APPROVED** [review]
Finally got EKS running and successful - works as advertised!

**Comment by vishnu2kmohan** [comment]
Given https://github.com/determined-ai/determined/pull/2887 landed, do we still need this PR @mluyo3414?

**Comment by vishnu2kmohan** [comment]
Ping @mluyo3414 :point_up: 

cc @varlogtim

**Comment by mluyo3414** [comment]
Covered in #2887 . Closing.

**Pull request closed without merging**
