### PR TITLE
chore: rearrange log level constants

### PR DESCRIPTION
**Pull request by phillip-gaisford**
## Description

Constants in the model package cannot be referenced in pkg/archive as it would create a disallowed import cycle.

Remedy: pull out the log level definitions to a seperate package that can be used by both model & archive.

Keeping the definitions in the model package in place for now as it lowers the changed line count.

## Checklist

- [ ] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by stoksc — APPROVED** [review]
fine with me. something we may move around later but works for now.

**Comment by stoksc** [comment]
maybe more idiomatic go to put them in a package called like.. `tasklog` or something. and we could move the other models there too but, honestly, this works just fine.

**Review by jerryharrow — COMMENTED** [review]
Note that this will break -ee on merge due to the other references there in the agent, and in experiment.go (I'm surprised that one isn't in OSS).

**Comment by stoksc** [comment]
there is a diff in experiment.go? 🙃 shouldn't be there..

**Review by jerryharrow — APPROVED** [review]

**Comment by stoksc** [comment]
> All this effort for share symbolic names that are still not checked since they are not enums :-)

yeah, lack of enums and unions in Go is my #1 gripe, now that we are finally getting iterators.

**Pull request merged**
