### PR TITLE
refactor: customize-cra to craco [DET-5441]

### PR DESCRIPTION
**Pull request by hkang1**
## Description

Previously, [customize-cra](https://github.com/arackaf/customize-cra) was used, but due the customize-cra project seemingly inactive (over 2 years since last update) and CRACO being more well rounded in terms of overriding capability, we decided to migrate over to the active project of CRACO.

We use [CRACO](https://github.com/gsoft-inc/craco) to modify the default webpack config generated by create-react-app. With the config files `craco.config.js` and `jest.config.js` the webpack configuration can be overriden. Ant Design, Monaco Editor and injecting a global SASS style files in our CSS module are some of the reasons why config customization is necessary.

## Test Plan

- [ ] check to make sure all the existing package.json scripts work. e.g. `npm start`, `npm run build`, `npm run test`, `npm run storybook`, `npm run storybook:build` etc.
- [ ] run through the WebUI and check to make sure everything still runs properly with no broken build or issues due to a different webpack config.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by hamidzr — APPROVED** [review]
looks good to me just one potential caveat if we wanna upgrade to v16 sometime. 

building storybook fails on node 16 which is not the version we're supporting (14)
building storybook on node v16 works on master.

```
ERR! Error: Found an unhandled loader in the development webpack config: /home/hmd/projects/da/determined/webui/react/node_modules/mini-css-extract-plugin/dist/loader.js
ERR!
ERR! This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:
ERR!
ERR!    $ yarn upgrade craco-less
ERR!
ERR! Or:
ERR!
ERR!    $ npm update craco-less
ERR!
ERR! If that doesn't work, craco-less needs to be fixed to support the latest version.
ERR! Please check to see if there's already an issue in the DocSpring/craco-less repo:
ERR!
ERR!    * https://github.com/DocSpring/craco-less/issues?q=is%3Aissue+webpack+unknown+rule
ERR!
```
I followed the suggestion here but it didn't help.
but it seems to work fine on 14. 
https://520605-253846879-gh.circle-artifacts.com/0/webui/react/build-storybook/index.html?path=/story/taskcard--default-experiment

**Comment by hamidzr** [comment]
nvm v16 fails on master as well but just at a later stage.

**Comment by hkang1** [comment]
Interesting thing about the Node 16 issue. I'm also linking a related issue of `node 16/npm 7` not being supported due to [npm peer resolution](https://github.com/determined-ai/determined/pull/3108#issue-1032960137).

**Comment by hkang1** [comment]
> looks good to me just one potential caveat if we wanna upgrade to v16 sometime.
> 
> building storybook fails on node 16 which is not the version we're supporting (14) building storybook on node v16 works on master.
> 
> ```
> ERR! Error: Found an unhandled loader in the development webpack config: /home/hmd/projects/da/determined/webui/react/node_modules/mini-css-extract-plugin/dist/loader.js
> ERR!
> ERR! This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:
> ERR!
> ERR!    $ yarn upgrade craco-less
> ERR!
> ERR! Or:
> ERR!
> ERR!    $ npm update craco-less
> ERR!
> ERR! If that doesn't work, craco-less needs to be fixed to support the latest version.
> ERR! Please check to see if there's already an issue in the DocSpring/craco-less repo:
> ERR!
> ERR!    * https://github.com/DocSpring/craco-less/issues?q=is%3Aissue+webpack+unknown+rule
> ERR!
> ```
> 
> I followed the suggestion here but it didn't help. but it seems to work fine on 14. https://520605-253846879-gh.circle-artifacts.com/0/webui/react/build-storybook/index.html?path=/story/taskcard--default-experiment

I just realized looking at `craco-less`'s package.json, [it contains `peerDependencies`](https://github.com/DocSpring/craco-less/blob/master/package.json#L43) which `node v16/npm v7` doesn't handle the same way that `npm v6` does. This is a known issue with `node v16`. Until packages such as `craco-less` (and we had a few others like `io-ts`) upgrade their setup to support `npm v7`'s method of resolving peer dependencies, we can't quite upgrade yet.

**Pull request merged**
