### PR TITLE
docs: Added Profiling to the Benefits table in the intro

### PR DESCRIPTION
**Pull request by KevinMusgrave**
## Description

Added Profiling to this table: https://docs.determined.ai/latest/architecture/introduction.html#benefits

Looks like this:
Screenshot 2023-08-07 at 5 28 43 PM

### CODE REVIEW

**Review by tara-det-ai — APPROVED** [review]
LGTM

**Comment by stoksc** [comment]
hey, this was merged but lint docs was failing. can you stamp https://github.com/determined-ai/determined/pull/7586 please?

**Comment by KevinMusgrave** [comment]
Sorry about that! I reviewed #7586 now

**Comment by stoksc** [comment]
np. i think you must've admin merged, it really shouldn't have let you merge this, so make sure to avoid that. i'm not entirely sure why everyone has permission to do that, maybe something we should take up with #eng-det-infra

**Comment by KevinMusgrave** [comment]
Ah ok, I won't merge PRs in the future

**Comment by stoksc** [comment]
You can merge PRs, just don't admin merge, meaning overriding CI. It should've been a little checkbox.

**Comment by stoksc** [comment]
I you _didn't_ click a checkbox to merge, it is not impossible there was a bug with CI reporting green when it actually wasn't.

**Comment by KevinMusgrave** [comment]
Yeah I may have clicked a checkbox.

**Pull request merged**
