### PR TITLE
fix: webui table horizontal scroll [DET-4660]

### PR DESCRIPTION
**Pull request by apizzini**
## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by apizzini** [comment]
@hkang1 this fix is enabling ant-table scrolling only if needed.

There was a 1st call where `resize.width = 0`, followed by a 2nd call with `resize.width` properly populated, we should wait for that 2nd call to make the calculation.

There's still an edge case that I was not able to fix: if you resize the window from small (with table resize enabled) to large (resize no more needed) I have not found a way to turn off ant-table scrolling. Looking at [their doc](https://ant.design/components/table/#scroll), there's no way to turn that off?

To me that looks to be an edge case that can be skipped, but lmk if you want me to look into that (can prob set a state var and manually remove some css classes from the table when not needed, or simply re-init the table).

**Comment by hkang1** [comment]
> @hkang1 this fix is enabling ant-table scrolling only if needed.
> 
sweet!

> There was a 1st call where `resize.width = 0`, followed by a 2nd call with `resize.width` properly populated, we should wait for that 2nd call to make the calculation.
> 
nice, makes sense!

> There's still an edge case that I was not able to fix: if you resize the window from small (with table resize enabled) to large (resize no more needed) I have not found a way to turn off ant-table scrolling. Looking at [their doc](https://ant.design/components/table/#scroll), there's no way to turn that off?
> 
> To me that looks to be an edge case that can be skipped, but lmk if you want me to look into that (can prob set a state var and manually remove some css classes from the table when not needed, or simply re-init the table).
>
Hmm the one that comes to mind is when the nav side bar is expanded and then collapsed, causing the table to grow. Let me try it out and see but it's probably not a big deal.

**Comment by hkang1** [comment]
@apizzini Hey I did a bit of poking around in the `antd` docs and I think this fix will work with dynamic sizing.
```
    setTableScroll({
      x: rect.width > resize.width ? rect.width : 'max-content',
      y: scroll?.y,
    });
```
Note the `max-content` setting.

**Review by hkang1 — COMMENTED** [review]
@apizzini Hey I did a bit of poking around in the `antd` docs and I think this fix will work with dynamic sizing.
```
    setTableScroll({
      x: rect.width > resize.width ? rect.width : 'max-content',
      y: scroll?.y,
    });
```
Note the `max-content` setting.

This would be in conjunction with the resize.width check you are doing.

**Comment by apizzini** [comment]
max-content worked perfectly, I'm unsure how I lost it from the doc :/

**Review by hkang1 — APPROVED** [review]
LGTM!

**Comment by hkang1** [comment]
> max-content worked perfectly, I'm unsure how I lost it from the doc :/

It could've been a recent change or something. They're constantly adding new features, which has been great

**Pull request merged**
