### PR TITLE
fix: import missing time module

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
## Description

I noticed that the `docs/deploy/upload.py` uses `time.time_ns()` on line [148](https://github.com/determined-ai/determined/blob/bc3b2a6cdbe45ad41d98507f1ea50b8bcf016d68/docs/deploy/upload.py#L148C21-L148C35) which requires an import, otherwise we are getting an exception. This PR imports this missing module.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] New features have been approved by the corresponding PM
- [ ] User-facing API changes have the "User-facing API Change" label
- [ ] Release notes have been added as a separate file under `docs/release-notes/`
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses have been included for new code which was copied and/or modified from any external code

[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sirredbeard** [comment]
@cla-bot[bot] check

**Comment by sirredbeard** [comment]
CLA signed, authorizing tests.

**Review by tara-det-ai — APPROVED** [review]
LGTM

**Comment by ioga** [comment]
@emmanuel-ferdman thank you for your PR! which automated or AI tool did you use to catch this issue?

**Pull request merged**
