### PR TITLE
chore: port EE changes to e2e_tests/

### PR DESCRIPTION
**Pull request by rb-determined-ai**
Changes were extracted programmatically.

I don't plan on landing this pr; I plan on just pushing it to master after review + passing tests, so that github doesn't do anything funny with the git history I so carefully extracted.

```sh
#!/bin/sh

set -e

commit () {
    git log --format=%H -n 1 "$@"
}

date () {
    git log -n 1 --format=%aD "$@"
}

message () {
    git log --format=%B -n 1 "$@" | sed -e '$d'
}

author () {
    git log --format="%aN <%ae>" -n 1 "$@"
}

changed_dirs () {
    # no -r means you only get the toplevel changes
    git diff-tree --no-commit-id --name-only "$1"
}

## script start

if [[ -n "$(git status --porcelain)" ]]; then
    echo "untracked or dirty files are not allowed; this script will sometimes"
    echo '`rm -rf && git checkout`, which would discard your untracked files,'
    echo 'and then you would be really sad.'
    exit 1
fi


eebase="$(git merge-base upstream/main oss/main)"

git checkout "$eebase"

eecommits=""
osscommits=""

allcommits="$(git log --reverse --format=%H $eebase..upstream/main)"
for c in $allcommits ; do
    git cherry-pick $c
    changes="$(changed_dirs HEAD)"
    if [ "$changes" = "e2e_tests" ] ; then
        # e2e only; goes to oss
        osscommits="$(printf "%s\n%s" "$osscommits" $c)"
    elif ! echo "$changes" | grep -q e2e_tests ; then
        # non-e2e only; stays in ee
        eecommits="$(printf "%s\n%s" "$eecommits" $c)"
    else
        # mixed changes; needs a breakup
        base="$(commit HEAD~)"
        auth="$(author $c)"
        msg="$(message $c)"
        dt="$(date $c)"
        eemsg="$(printf "%s\n\n[excluding e2e_tests changes]" "$msg")"
        ossmsg="$(printf "%s\n\n[e2e_tests changes only]" "$msg")"
        # build the ee commit
        rm -rf e2e_tests
        git checkout $base e2e_tests
        git commit -a --amend --no-edit -m "$eemsg" --date "$dt" --author "$auth"
        eecommits="$(printf "%s\n%s" "$eecommits" "$(commit HEAD)")"
        # build the oss commit
        rm -rf e2e_tests
        git checkout $c e2e_tests
        git commit -m "$ossmsg" --date "$dt" --author "$auth"
        osscommits="$(printf "%s\n%s" "$osscommits" "$(commit HEAD)")"
    fi
done

# save a temp-start branch
git checkout -B temp-start

# build a temp-ee branch
git checkout $eebase
git checkout -B temp-ee
for c in $eecommits ; do
    git cherry-pick $c
done

# build a temp-oss branch
git checkout $eebase
git checkout -B temp-oss
for c in $osscommits ; do
    git cherry-pick $c
done

# build a temp-both branch
git checkout -B temp-both
git rebase --onto temp-ee $eebase temp-both

# sanity check: make sure temp-both matches upstream/main
different="$(git diff --name-only upstream/main..temp-both)"
if [ -n "$different" ] ; then
    echo "sanity check failed!"
    echo "Found differences in the following files:"
    echo "$different"
    exit 7
fi
```

### CODE REVIEW

**Comment by MikhailKardash** [comment]
These rebase issues come from `ee` and `oss` tests being described in the same files and sharing the same methods. I think this requires a higher-level solution.

Maybe decorators are not the correct method to use when sharing a test between repos. If someone adds more decorators on the `ee` side in the future, won't this just become an issue again?

Hot take: maybe tests shouldn't be shared across the two repos in the first place.

**Comment by rb-determined-ai** [comment]
@MikhailKardash and I discussed offline, the strategy here meets the needs in an acceptable way, and also mimizes the scope of what is in EE, which is a good idea.

**Comment by stoksc** [comment]
let's make sure the contents or the commits and messages are ok to merge to oss, just incase.

**Comment by rb-determined-ai** [comment]
> let's make sure the contents or the commits and messages are ok to merge to oss, just incase.

done

**Comment by rb-determined-ai** [comment]
CI finished; everything passed except `test_mnist_pytorch_distributed` which timed out during image pull.  I think that's as good as it gets for the nightly test suite.

I'll be landing this by pushing it directly to main now.

**Pull request merged**
