### PR TITLE
fix: remove error text in continue trial modal

### PR DESCRIPTION
**Pull request by keita-determined**
## Description
[ET-32] [ET-58]

## Test Plan
- Check if error text doesnt break UI layout in continue trial modal when error occurs
- Check if page doesnt crash when yaml config is empty in the full config page

## Checklist

- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

[ET-32]: https://hpe-aiatscale.atlassian.net/browse/ET-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-58]: https://hpe-aiatscale.atlassian.net/browse/ET-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by johnkim-det — COMMENTED** [review]
I know that in grooming we said this should just remove the `Message`. But I'm realizing that this ideally would be shown as red status text for the Input element, using form validation logic, without making an API request at all. It does make the border red so I think it should be possible, not sure why the message isn't displayed.

Do you mind looking into that? If it seems like a big task I think we can keep this solution for this ticket and create a new one for fixing form validation.

**Comment by keita-determined** [comment]
will take a look

**Comment by keita-determined** [comment]
@johnkim-det i used `Alert` component instead of form because code view is not a part of form component. to check the code config format, it errors out without API call in the advanced mode. in the normal mode, it shows API errors in Alert component.

**Comment by keita-determined** [comment]
@johnkim-det  `parsing continue experiment request: invalid resource configuration: rpc error: code = InvalidArgument desc = resource pool compute-pool does not exist or is not available to workspace id 1` error comes from backend even though it sounds like yaml format issue from web. YAML check and other validations work fine in the simple/full config. 

Disabled submit button in full config page when error occurs. in the simple config page already has the functionality to disable submit button.

**Comment by johnkim-det** [comment]
Issues I'm seeing:
- Simple Config modal does not validate the form initially, so the submit button is not disabled even though the default state does not have a value for Max batches. 
- Simple Config shows red outline for errors, but should include the error message that says what the error is
- Full Config can display an error and still allow submit: 
Screenshot 2024-03-11 at 11 14 03 AM

also FYI created https://hpe-aiatscale.atlassian.net/browse/ET-65

**Comment by keita-determined** [comment]
> * Simple Config modal does not validate the form initially, so the submit button is not disabled even though the default state does not have a value for Max batches.

I made a change like this but not quite working well. Do you have suggested code? 

```diff
diff --git a/webui/react/src/components/ExperimentContinueModal.tsx b/webui/react/src/components/ExperimentContinueModal.tsx
index d0d0c29b2..6c66c127f 100644
--- a/webui/react/src/components/ExperimentContinueModal.tsx
+++ b/webui/react/src/components/ExperimentContinueModal.tsx
@@ -11,7 +11,7 @@ import { Body } from 'hew/Typography';
 import { Loaded } from 'hew/utils/loadable';
 import yaml from 'js-yaml';
 import _ from 'lodash';
-import React, { useCallback, useEffect, useId, useState } from 'react';
+import React, { useCallback, useEffect, useId, useMemo, useState } from 'react';
 
 import { paths } from 'routes/utils';
 import { continueExperiment, createExperiment } from 'services/api';
@@ -92,10 +92,12 @@ const ExperimentContinueModalComponent = ({
   const [disabled, setDisabled] = useState<boolean>(true);
   const [originalConfig, setOriginalConfig] = useState(experiment.configRaw);
   const isReactivate = type === ContinueExperimentType.Reactivate;
+  const hideSimpleConfig = isReactivate && experiment.state !== RunState.Completed;
+  const modalIsInAdvancedMode = modalState.isAdvancedMode || hideSimpleConfig;
 
   useEffect(() => setOriginalConfig(experiment.configRaw), [experiment]);
 
-  const requiredFields = [EXPERIMENT_NAME, MAX_LENGTH];
+  const requiredFields = useMemo(() => [EXPERIMENT_NAME, MAX_LENGTH], []);
 
   const handleModalClose = () => {
     setModalState(DEFAULT_MODAL_STATE);
@@ -381,15 +383,19 @@ const ExperimentContinueModalComponent = ({
       };
       return _.isEqual(prev, newModalState) ? prev : newModalState;
     });
-    setDisabled(!experiment.name); // initial disabled state set here, gets updated later in handleFieldsChange
-  }, [experiment, trial, type, isReactivate, form]);
+    const missingRequiredFields =
+      !modalIsInAdvancedMode &&
+      Object.entries(form.getFieldsValue()).some(([key, value]) => {
+        return requiredFields.includes(key) && !value;
+      });
+    setDisabled(missingRequiredFields); // initial disabled state set here, gets updated later in handleFieldsChange
+    getMaxLengthValue(experiment.configRaw);
+  }, [experiment, trial, type, isReactivate, form, requiredFields, modalIsInAdvancedMode]);
 
   if (!experiment || (!isReactivate && !trial)) return <></>;
 
-  const hideSimpleConfig = isReactivate && experiment.state !== RunState.Completed;
-
   const maxLengthType = capitalizeWord(getMaxLengthType(modalState.config) || 'batches');
-  const modalIsInAdvancedMode = modalState.isAdvancedMode || hideSimpleConfig;
+
   return (
     <Modal
       cancel

```

> * Simple Config shows red outline for errors, but should include the error message that says what the error is

This is Hew form component issue. Error messages are set for input components, but hew form doesnt show it like antd form after error occured
made a ticket for it: https://hpe-aiatscale.atlassian.net/browse/ET-70

> * Full Config can display an error and still allow submit:

How can I reproduce it? I dont see the case.

**Comment by johnkim-det** [comment]
I think you can just replace the `setDisabled(!experiment.name);` in `useEffect` with `form.validateFields()`. Looks like `setDisabled(hasError || missingRequiredFields)` in `handleFieldsChange` will get called after that .

As for the Full Config error, I think the problem is that it doesn't change disabled state from Simple Config, so it might also stay disabled if it was disabled in Simple Config. In the case I captured in my screenshot, changing `drop_capabilities` from valid to invalid doesn't update the button disabled state. Don't think it matters which experiment.
I think it needs a `setDisabled` call in `handleEditorChange` (and probably also `toggleMode` for when the modal is first changed to Full Config mode).

Also would double-check that `ExperimentCreateModal` also works correctly, seems like it has a lot of similar code.

Thanks for looking into this -- I know it's more than the original ticket but I think it makes sense to address as much of this as possible here and create separate tickets as necessary.

**Comment by keita-determined** [comment]
i forgot about `form.validateFields()`. fixed the issue with it.

---

the submit button issue in the Full config should be fixed

https://github.com/determined-ai/determined/assets/109113616/109c081a-2646-4427-86bb-c0cbbbbf3319

---

applied changes in `ExperimentCreateModal` too. 

Let me know if there's something to fix.

**Review by johnkim-det — APPROVED** [review]
LGTM thanks!

**Pull request merged**
