### PR TITLE
chore: bumpenvs 24.0

### PR DESCRIPTION
**Pull request by MikhailKardash**
## Description

Bumpenvs for environments version 0.24.0

## Test Plan

CI must pass.

## Checklist

- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket
None

### CODE REVIEW

**Review by mpkouznetsov — APPROVED** [review]
Trivial and sensible. :shipit:

**Comment by jerryharrow** [comment]
@MikhailKardash would you be able to cherry-pick this to a determined-ee PR for testing?
We had to revert the last bumpenvs because it changed the nsswitch.conf file which caused a Slurm/PBS regression.
https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1690470713385069
Easier if we detect the problem before the submit then merge to -ee.

We have an e2e_test that catches this case now (test_start_and_verify_hpc_home).

**Review by carolinaecalderon — APPROVED** [review]
LGTM

**Comment by MikhailKardash** [comment]
> test_start_and_verify_hpc_home

I just rebased my branch onto main, here's the run. https://app.circleci.com/pipelines/github/determined-ai/determined-ee/8650/workflows/650ff20c-fdb6-4ede-aa6b-6dc59a1f1a20/jobs/380101

**Pull request merged**
