### PR TITLE
perf: update proto_checkpoint_view to use index

### PR DESCRIPTION
**Pull request by NicholasBlaskey**
## Description

```proto_checkpoint_view``` was casting ```checkpoints_v2.uuid``` to a text meaning we couldn't use the index on ```checkpoints_v2.uuid``` so model queries were full scanning checkpoints.

## Test Plan

```TestCheckpointReturned``` should have this covered well

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by stoksc** [comment]
@NicholasBlaskey can you post the new plan?

**Comment by NicholasBlaskey** [comment]
new query
```
                                                                                       QUERY PLAN                                                                                       
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=13.11..64.55 rows=1 width=266) (actual time=2.409..2.434 rows=1 loops=1)
   ->  Nested Loop Left Join  (cost=2.73..54.09 rows=1 width=2461) (actual time=1.778..1.784 rows=1 loops=1)
         ->  Nested Loop Left Join  (cost=2.15..45.76 rows=1 width=1947) (actual time=1.741..1.745 rows=1 loops=1)
               ->  Nested Loop Left Join  (cost=1.71..37.74 rows=1 width=1730) (actual time=1.646..1.649 rows=1 loops=1)
                     ->  Nested Loop Left Join  (cost=1.42..29.91 rows=1 width=1555) (actual time=1.206..1.209 rows=1 loops=1)
                           ->  Nested Loop Left Join  (cost=1.00..21.94 rows=1 width=839) (actual time=1.191..1.194 rows=1 loops=1)
                                 ->  Nested Loop  (cost=0.57..17.73 rows=1 width=835) (actual time=1.160..1.162 rows=1 loops=1)
                                       ->  Nested Loop Left Join  (cost=0.14..9.28 rows=1 width=218) (actual time=0.014..0.016 rows=1 loops=1)
                                             ->  Seq Scan on model_versions  (cost=0.00..1.05 rows=1 width=204) (actual time=0.006..0.007 rows=1 loops=1)
                                                   Filter: (model_id = 1)
                                                   Rows Removed by Filter: 3
                                             ->  Index Scan using users_pkey on users  (cost=0.14..8.16 rows=1 width=18) (actual time=0.006..0.006 rows=1 loops=1)
                                                   Index Cond: (id = model_versions.user_id)
                                       ->  Index Scan using checkpoints_v2_uuid_key on checkpoints_v2 c  (cost=0.43..8.45 rows=1 width=633) (actual time=1.144..1.144 rows=1 loops=1)
                                             Index Cond: (uuid = model_versions.checkpoint_uuid)
                                 ->  Index Only Scan using idx_checkpoint_id_run_id on run_checkpoints rc  (cost=0.43..4.21 rows=1 width=20) (actual time=0.014..0.015 rows=1 loops=1)
                                       Index Cond: (checkpoint_id = c.uuid)
                                       Heap Fetches: 0
                           ->  Index Scan using trials_pkey on runs r  (cost=0.42..7.97 rows=1 width=720) (actual time=0.014..0.014 rows=1 loops=1)
                                 Index Cond: (id = rc.run_id)
                     ->  Index Scan using experiments_pkey on experiments e  (cost=0.29..7.83 rows=1 width=179) (actual time=0.439..0.439 rows=1 loops=1)
                           Index Cond: (id = r.experiment_id)
               ->  Index Scan using validations_trial_id_total_batches_run_id_unique on raw_validations v  (cost=0.44..8.01 rows=1 width=225) (actual time=0.012..0.013 rows=1 loops=1)
                     Index Cond: ((trial_id = r.id) AND (total_batches = ((c.metadata ->> 'steps_completed'::text))::integer))
                     Filter: (NOT archived)
         ->  Index Scan using steps_trial_id_total_batches_run_id_unique on raw_steps s  (cost=0.57..8.31 rows=1 width=522) (actual time=0.010..0.011 rows=1 loops=1)
               Index Cond: ((trial_id = r.id) AND (total_batches = ((c.metadata ->> 'steps_completed'::text))::integer))
               Filter: (NOT archived)
   ->  Subquery Scan on m  (cost=10.38..10.41 rows=1 width=191) (actual time=0.057..0.059 rows=1 loops=1)
         ->  GroupAggregate  (cost=10.38..10.40 rows=1 width=211) (actual time=0.048..0.049 rows=1 loops=1)
               Group Key: m_1.id, u.id
               ->  Sort  (cost=10.38..10.38 rows=1 width=207) (actual time=0.043..0.044 rows=1 loops=1)
                     Sort Key: u.id
                     Sort Method: quicksort  Memory: 25kB
                     ->  Nested Loop Left Join  (cost=0.14..10.37 rows=1 width=207) (actual time=0.011..0.014 rows=1 loops=1)
                           Join Filter: (mv.model_id = m_1.id)
                           ->  Nested Loop  (cost=0.14..9.31 rows=1 width=203) (actual time=0.008..0.010 rows=1 loops=1)
                                 ->  Seq Scan on models m_1  (cost=0.00..1.07 rows=1 width=185) (actual time=0.004..0.005 rows=1 loops=1)
                                       Filter: (id = 1)
                                       Rows Removed by Filter: 5
                                 ->  Index Scan using users_pkey on users u  (cost=0.14..8.16 rows=1 width=18) (actual time=0.003..0.003 rows=1 loops=1)
                                       Index Cond: (id = m_1.user_id)
                           ->  Seq Scan on model_versions mv  (cost=0.00..1.05 rows=1 width=8) (actual time=0.002..0.003 rows=1 loops=1)
                                 Filter: (model_id = 1)
                                 Rows Removed by Filter: 3
 Planning Time: 4.010 ms
 Execution Time: 2.714 ms
(47 rows)


```

**Review by stoksc — APPROVED** [review]
lgtm, checked it out locally and hit some apis to make sure there wasn't some random thing using that view that was untested.

**Review by stoksc — APPROVED** [review]
lgtm, checked it out locally and hit some apis to make sure there wasn't some random thing using that view that was untested.

**Pull request merged**
