### PR TITLE
chore: take out job summary caching [DET-6695]

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

changes how we provide job summary for individual experiments from an opportunistic and incomprehensive "push when we have updates" to pull when asked.

## Commentary (optional)

DET-6918

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by eecsliu — APPROVED** [review]
Makes a lot of sense to me. I am curious how the new error handling in api_experiment.go holds up.

**Comment by hamidzr** [comment]
> Makes a lot of sense to me. I am curious how the new error handling in api_experiment.go holds up.

yeah I believe I had thought through the error handling scenario and the rollback seemed safe but it's been a few days and I can't remember that anymore. I'll check it agian

**Comment by hamidzr** [comment]
> Makes a lot of sense to me. I am curious how the new error handling in api_experiment.go holds up.

I was ignoring the "job not found" error ad jobs actor level when you reviewed which I don't think was good. I corrected that so the actor msg to getJobSummary fails if the job is missing but I put back the provision to ignore that type of error for get_experiment request.

**Review by gh-determined-ai — CHANGES_REQUESTED** [review]
The release note needs to be more descriptive. Usually, providing the context from the Jira issue 'Description' field is sufficient.
See RN guidelines: https://github.com/determined-ai/determined/tree/master/docs/release-notes/README.md

**Comment by hamidzr** [comment]
py ci jobs are flaking https://determined-ai.slack.com/archives/CT01QS70Q/p1649968507348409

**Review by gh-determined-ai — APPROVED** [review]

**Comment by hamidzr** [comment]
blocking on https://github.com/determined-ai/determined/pull/3943 to land

**Pull request merged**
