### PR TITLE
ci: new semantic pull request check.

### PR DESCRIPTION
**Pull request by ioga**
## Description

Move to a new semantic pull request title check based on github actions.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hkang1** [comment]
@ioga guessing this PR has to land before the changes take affect? Like it won't work for this specific PR :D

**Comment by ioga** [comment]
you have to set it to `pull_request` instead of `pull_request_target` for the current PR to work here. but that's not a good idea for the repo proper.

if you see previous `wip` version, the check is there.

**Comment by ioga** [comment]
Screen Shot 2022-04-20 at 11 43 02

**Review by hkang1 — APPROVED** [review]
looked at the [options](https://github.com/amannn/action-semantic-pull-request) the config looks good! thanks for unblocking us!

**Pull request merged**
