### PR TITLE
fix: checkpoint gc job should close

### PR DESCRIPTION
**Pull request by stoksc**
## Description
This change updates the checkpoint GC actor to properly exit when it is finished.

## Test Plan
- [x] ensure experiment delete works.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hamidzr** [comment]
👍🏼  I'll pull this into https://github.com/determined-ai/determined/pull/3936 just to verify

**Comment by stoksc** [comment]
sgtm, worked locally for me

**Comment by hamidzr** [comment]
could the bug have had user-facing consequences? when I was examining tests I saw experiments stuck at deleting and entering deleting_failed state if the server stopped during this period.

**Review by hamidzr — APPROVED** [review]
lgtm. do we need release notes?

**Review by gh-determined-ai — APPROVED** [review]

**Pull request merged**
