### PR TITLE
feat: Add workspace column to global model registry page [WEB-804]

### PR DESCRIPTION
**Pull request by julian-determined-ai**
## Description

Adds a filterable and sortable `workspace` column to the Model Registry page. 

## Test Plan

1. Navigate to the `Model Registry` page. 
2. Ensure that a `Workspace` column is shown that shows the workspace avatar.
3. Click the sorting buttons on the workspace column and ensure the table is sorted alphanumerically by workspace name.
4.  Click the filter button on the workspace column and ensure that the table is correctly filtered by the chosen workspaces. 
5. Click the `Clear Filters` button and ensure the filter in (4) is removed. 
 

## Checklist

- [x] Changes have been manually QA'd
~- [ ] User-facing API changes need the "User-facing API Change" label.~
~- [ ] Release notes should be added as a separate file under `docs/release-notes/`.~
  ~See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.~
~- [ ] Licenses should be included for new code which was copied and/or modified from any external code.~

## Ticket

WEB-804

### CODE REVIEW

**Review by gt2345 — COMMENTED** [review]
I wonder have we considered sorting and filtering through backend, like other attributes in table

**Comment by julian-determined-ai** [comment]
@gt2345 I did wonder the same, I see that we do the same on the `tasks` page where all the filters on the front end. I can reach out to backend and see if there is some limitation as to why we cannot or did not filter by workspace on the backend.

**Comment by julian-determined-ai** [comment]
@gt2345 Updated to perform all filtering and sorting on the backend.

**Comment by gt2345** [comment]
Clicking on Workspace column header seems to sort by unspecific instead of workspace. 

https://user-images.githubusercontent.com/40620519/217736983-6d70fb8d-1bd1-44e6-a6e7-cc9a414fc8d3.mov

**Comment by julian-determined-ai** [comment]
> Clicking on Workspace column header seems to sort by unspecific instead of workspace.
> 
>  Screen.Recording.2023-02-09.at.12.37.57.AM.mov

@gt2345 I cannot reproduce this locally or on Netlify I will reach out to you about it.

**Review by gt2345 — APPROVED** [review]
LGTM

**Pull request merged**
