### PR TITLE
feat: exclude `Array` type columns

### PR DESCRIPTION
**Pull request by keita-determined**
## Ticket

[ET-654]

## Description

excluding ARRAY type columns from filter and sort

### How to Add Metadata❓

If you wanna add metadata, look at [this comment ](https://github.com/determined-ai/determined/pull/9808#issuecomment-2278391220)

## Test Plan

- Make a metadata with array type
- Check if the metadata cannot be filtered or sorted
- Check if Array type column shows data as array like `[1, 2, 3, [2, 4]]`

## Checklist

- [x] Changes have been manually QA'd
- [ ] New features have been approved by the corresponding PM
- [ ] User-facing API changes have the "User-facing API Change" label
- [ ] Release notes have been added as a separate file under `docs/release-notes/`
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses have been included for new code which was copied and/or modified from any external code

[ET-654]: https://hpe-aiatscale.atlassian.net/browse/ET-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by EmilyBonar** [comment]
@keita-determined How do I add metadata to a run/create a run with metadata?

**Comment by keita-determined** [comment]
i ususually use [this API](http://latest-main.determined.ai:8080/docs/rest-api/#/Internal/PostRunMetadata)

**Review by EmilyBonar — APPROVED** [review]
Works, though it displays arrays like this `[1,2,3,[2,4]]` with all the spaces removed, which looks a little cramped.

**Comment by keita-determined** [comment]
> Works, though it displays arrays like this `[1,2,3,[2,4]]` with all the spaces removed, which looks a little cramped.

yep `JSON.stringify` remove the spaces. Even if i set [the space arg](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#space) it wouldnt look like what we want. I also considered making a function, but i might be complicated to handle the edge cases. I'll leave it as it is for now.

**Pull request merged**
