### PR TITLE
fix: allow moving jobs to top without assuming the full job list [DET-8015]

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

issues: 
- move to top
- move job to position number N

cause: computing how to move a job to an arbitrary position requires the full list of jobs. previously this was fine as the ui was always working with full list of jobs but we started breaking down the jobs and didn't see this issue.

## Test Plan

- TODO repro with release cluster

## Commentary (optional)

watch out for https://github.com/determined-ai/determined/pull/4756 . the changes here are set in a way that allow that pr to go through without having to build additional endpoints for now

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [ ] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gt2345 — COMMENTED** [review]
Not sure if I had data set up correctly locally, but did encounter a master error when click `Move to Top` on Queued tab, then switch to Active tab.

https://user-images.githubusercontent.com/40620519/184408801-105f3f3a-e5cc-4e77-bebd-fc3257d7500b.mov

**Comment by hamidzr** [comment]
> Not sure if I had data set up correctly locally, but did encounter a master error when click `Move to Top` on Queued tab, then switch to Active tab.
> 
>  Screen.Recording.2022-08-12.at.12.06.14.PM.mov

hmm this could certainly happen looking at the code https://github.com/hamidzr/determined/blob/c6579efc53a10c87cd558b2161f1cb1406838f67/master/internal/rm/agent_resource_manager.go#L603 but I'm not sure why or if it's directly related to the changes here 🤔

**Comment by hamidzr** [comment]
> Not sure if I had data set up correctly locally, but did encounter a master error when click `Move to Top` on Queued tab, then switch to Active tab.
> 
>  Screen.Recording.2022-08-12.at.12.06.14.PM.mov

to figure out if the two are related:
did the move to top the action take effect as you expected? can you reproduce the error on master as well?

**Comment by hamidzr** [comment]
I was able to reproduce the bug on master https://determinedai.atlassian.net/browse/DET-8214

**Review by gt2345 — APPROVED** [review]
Works great!

**Comment by hamidzr** [comment]
the failing test is a known issue.

**Pull request merged**
