### PR TITLE
docs: add rest API to list of references [DET-4381]

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

We use a hacky way to include an external link in Sphinx toctree described
https://stackoverflow.com/questions/27979803/external-relative-link-in-sphinx-toctree-directive

## Test Plan

Screen Capture_select-area_20201112140025

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by neilconway** [comment]
This renders as a link to `file:///Users/neilconway/det/docs/site/html/rest-api/index.html#http://`, which does not work.

**Comment by hamidzr** [comment]
> This renders as a link to `file:///Users/neilconway/det/docs/site/html/rest-api/index.html#http://`, which does not work.

file protocol 

> This renders as a link to `file:///Users/neilconway/det/docs/site/html/rest-api/index.html#http://`, which does not work.

I think when you're using the `file://` protocol the browser matches the path differently and the trailing #xyz becomes a problem. can you try loading through the cluster  as in SERVER:8080/docs ? 

or even https://198901-253846879-gh.circle-artifacts.com/0/docs/site/html/reference/index.html . here the swagger UI wouldn't load fully because it expects to be served through an active cluster.

**Comment by hamidzr** [comment]
also what do you mean by doesn't work? if it's this, it's expected
Screen Capture_select-area_20201112151100

**Comment by neilconway** [comment]
Ah, got it. Yeah, I guess this is good enough. Thanks!

**Review by neilconway — APPROVED** [review]

**Comment by hamidzr** [comment]
@cla-bot check

**Pull request merged**
