### PR TITLE
chore: code refactoring to allow addition of tests for new types of managed devclusters

### PR DESCRIPTION
**Pull request by jagadeesh545**
## Description

chore: code refactoring to allow the addition of tests for new types of managed devclusters
This PR includes a subset of changes taken from PR #5584. 

The changes in this PR are as follows:

1. Move the _now_ts() method to utils.py and rename it to now_ts().
2. Reduce code redundancy by creating a new method set_master_port() (within utils.py) that reads the config from the given path and sets the master port.
3. Move the abstract class, `Cluster`, to a separate file `abstract_cluster.py`, and update the reference/imports in `managed_cluster.py`, `managed_cluster_k8s.py`, and `test_master_restart.py`.

## Test Plan

Tested locally and as part of CircleCI workflow `test-e2e-managed-devcluster`.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by ioga** [comment]
my concern is that this means all test "functions" (around the wrapper) will need to be duplicated for each new cluster type and/or mark.

**Comment by jagadeesh545** [comment]
Yes, you are right. We have to write a wrapper function for each style of devcluster. I did try to do implement this with just the pytest markers. But, when I used multiple markers, it was impossible to make pytest use the correct type of devcluster based on the flag passed at CLI. Thus, we need a new wrapper function for each devcluster instance so that we can pass the correct fixture for the test.

**Review by stoksc — COMMENTED** [review]
lgtm, unless @ioga has any final comments (btw, nick took the same approach in the k8s restart tests)

**Comment by jagadeesh545** [comment]
Update: Now that #5584 is merged, This PR is just some code refactoring changes needed in one of the EE PRs.

**Review by stoksc — APPROVED** [review]

**Pull request merged**
