### PR TITLE
fix: adjust tooltip background color

### PR DESCRIPTION
**Pull request by keita-determined**
## Description
[WEB-887]

## Test Plan
- Check if Tooltip color matches the theme color (system, light, dark)
- Check if other tooltips looks the same as before (system, light, dark)

## Checklist

- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

[WEB-887]: https://determinedai.atlassian.net/browse/WEB-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hkang1** [comment]
Should the text change too? It seems like the tooltip bg changes but the text remains white, regardless of the theme. Example of tooltip in light theme.

[Screen Shot 2023-02-08 at 2 50 28 PM
](url)

**Comment by mapmeld** [comment]
Similarly I'm confused why this tooltip exists over the New Tag button , like I said in the ticket.  Now that I see the text, it does not look useful.
 
Screen Shot 2023-02-08 at 4 59 40 PM

**Comment by keita-determined** [comment]
> Similarly I'm confused why this tooltip exists over the New Tag button , like I said in the ticket. Now that I see the text, it does not look useful.
> 
> Screen Shot 2023-02-08 at 4 59 40 PM

This has been there for several months. I think this should be a different ticket.

**Comment by mapmeld** [comment]
I hope it is a small fix to turn off tooltips there (no tooltip is available in normal use of the component). If the fix is more complex, then please document the problem before passing it to a new ticket.

**Comment by keita-determined** [comment]
> I hope it is a small fix to turn off tooltips there (no tooltip is available in normal use of the component). If the fix is more complex, then please document the problem before passing it to a new ticket.

the reason why there's tooltip is that user cannot horizontally scroll the tags if there are many tags. Thats why.
but i agree to rethink about this

also, if text is too long, tooltip is helpful

image

**Comment by keita-determined** [comment]
> Should the text change too? It seems like the tooltip bg changes but the text remains white, regardless of the theme. Example of tooltip in light theme.
> 
> [Screen Shot 2023-02-08 at 2 50 28 PM ](url)

fixed

**Comment by hkang1** [comment]
> > Should the text change too? It seems like the tooltip bg changes but the text remains white, regardless of the theme. Example of tooltip in light theme.
> > [Screen Shot 2023-02-08 at 2 50 28 PM ](url)
> 
> fixed

nice, can confirm it looks good on the preview!

**Review by hkang1 — APPROVED** [review]
LGTM!

**Pull request merged**
