### PR TITLE
fix: add endTime to metric workloads [DET-4743]

### PR DESCRIPTION
**Pull request by hkang1**
## Description

add the missing `endTime` property for metric based workloads (training and validation)

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by hamidzr** [comment]
@hkang1  could you base your commit and fix off of where we cut the release branch off of? Just to make sure there wouldn't be any conflicts or unexpected results

**Comment by hamidzr** [comment]
somewhere before 0015ebb0c270d29f0a3355639e1955a48154bf2c

**Comment by hkang1** [comment]
> @hkang1 could you base your commit and fix off of where we cut the release branch off of? Just to make sure there wouldn't be any conflicts or unexpected results

@hamidzr how does it look now?

**Review by hamidzr — APPROVED** [review]
LGTM

**Comment by hkang1** [comment]
@hamidzr thanks for the speedy review

**Pull request merged**
