### PR TITLE
build: Updates Python used in CircleCI to 3.8.16

### PR DESCRIPTION
**Pull request by wes-turner**
[MLG-359]

This PR consists of two changes:

1. A couple patches in `model_hub` that set typing such that mypy==0.910 passes under Python 3.8. This likely means `make check` will fail on these files under Python 3.7.

2. A change to the docker image used in CircleCI making CI checks run using Python 3.8 instead of 3.7.

Release will progress in the following steps:

1. A new cimg-base will be built from https://github.com/determined-ai/determined-ci-images/pull/9. It will be pushed to dockerhub with the tag 'py38'.

2. This build will run its CI tests using `determinedai/cimg-base:py38'

3. Assuming pre-commit tests are green, this PR will be merged.

4. If post-commit tests are green, a `cimg-base` with the tag `latest` will be built from the determined-ai/determined-ci-images PR https://github.com/determined-ai/determined-ci-images/pull/9.

5. We'll create a new PR in `deterimend-ai/determined` that moves the default docker-image in CircleCI's config.yml back to `latest`.

## Test Plan

* `make check` succeeds in a Python 3.8 dev environment
* `lint` tests are green in CircleCI

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

[MLG-359]: https://hpe-aiatscale.atlassian.net/browse/MLG-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rb-determined-ai** [comment]
plan looks good

**Review by loksonarius — APPROVED** [review]

**Comment by wes-turner** [comment]
Per Ryan's suggestion, opened https://github.com/determined-ai/determined/pull/6444 as a temporary PR to force `e2e_longrunning` test execution.

**Comment by wes-turner** [comment]
Once upon a time you'd asked if I was updating all test pipelines with this workflow to run off Python 3.8 and I was like, "Yup, think so! Well, except for the test-cli ones." Well... that was because I didn't understand how the [machine-image](https://github.com/determined-ai/determined/blob/527ce2a63b970869c27335a7e6ff02edab8aaa80/.circleci/config.yml#L31) variable was used. I guess I still don't. But one thing now seems likely -- some workflows depend on the deploy-image, and some on the machine-image. Those seem to be the more complicated integrationy tests.

Before this patch, docker-image was on 3.7.11 and machine-image on 3.7.16. If this is merged, docker-image will be 3.8.16 and machine-image (and machine-image-gpu) on 3.7.16.

I don't love that they're different minor versions. But I also kind of want to get this pushed.

I'd _prefer_ to keep following the plan here and then cut a ticket to update the machine-image image to 3.8.16, too (wherever that happens). Or to run all the tests from a similar starting package.

And so if your argument is that minor version mismatch brings us to a worse spot than we were before, push both updates in tandem or don't push any, I think that's a pretty good, defensible argument. If that's what you'd like, I'll accept that and hold onto this PR until I can bump that image, too.

**Review by rb-determined-ai — APPROVED** [review]
honestly, if all we do is lint against 3.8, and tests run against 3.7, that would be an improvement for devs imo.

If we support 3.8 and 3.7 then ci should pass in either case.

If upstream ci passes here, I'm fine with this.  We'll fix it when 3.7 goes eol which isn't so far away.

**Comment by wes-turner** [comment]
I'd like to get a list of which pythons were run in which tests. Some of the longer tests are 3.7.16, some are 3.8.16, and since each job has a `python --version` step, it's possible to tell which is which.

Spot checking a few jobs within these workflows, it looks like `test-e2e` uses 3.7.16 throughout and , `test-e2e-longrunning` uses 3.8.16. There were a lot of failures in the `test-e2e-longrunning` workflow, but our tests aren't particularly stable right now, so I'm going to wait a little while and try again later. Lots of timeouts.

CircleCI has a REST API that lets you query "job artifacts", but unless we tee output to an artifact, there's no way to programmatically fetch the output, so short of manually clicking through webpages (or parsing our complicated `config.yaml`) I can't generate a definitive list of what uses what.

**Review by loksonarius — APPROVED** [review]

**Comment by wes-turner** [comment]
> honestly, if all we do is lint against 3.8, and tests run against 3.7, that would be an improvement for devs imo.
> 
> If we support 3.8 and 3.7 then ci should pass in either case.
> 
> If upstream ci passes here, I'm fine with this. We'll fix it when 3.7 goes eol which isn't so far away.

Postcommit tests pass: https://github.com/determined-ai/determined/pull/6444

**Comment by wes-turner** [comment]
`check-rebaseable` is red, but it's failing for other PRs, too. Committing per the "check rebaseable" playbook and continuing with the deployment strategy in the commit notes.

Next step:
4. If post-commit tests are green, a cimg-base with the tag latest will be built from the determined-ai/determined-ci-images PR https://github.com/determined-ai/determined-ci-images/pull/9.

**Pull request merged**
