### PR TITLE
fix: use bash in bash script

### PR DESCRIPTION
**Pull request by dannysauer**
## Description

bashisms would break on Debian/Ubuntu/etc where /bin/sh is dash

## Test Plan

I ran this locally and it worked.  I'd be shocked if it failed for other people (even when bash is "really" in `/usr/bin`, I've never seen a system without a symlink in `/bin`).

## Checklist
- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by rb-determined-ai** [comment]
What are the bashisms in question?  I try pretty hard to avoid them (though I'm often still surprised when I run dash).

**Comment by dannysauer** [comment]
> What are the bashisms in question? I try pretty hard to avoid them (though I'm often still surprised when I run dash).

The first command.
```plain
sauer@fabulinus:~$ dash -c 'set -o pipefail'
dash: 1: set: Illegal option -o pipefail
```

**Review by rb-determined-ai — APPROVED** [review]
ah, TIL.

Well probably I've hit that one before and forgot.

But I'd rather have pipefail than sh.

**Comment by dannysauer** [comment]
Technically, it's a "not-in-dashism"; it's not Bash-specific.  It's actually even in POSIX very recently, AFAICT.
https://www.austingroupbugs.net/view.php?id=789

Probably why this works:
```plain
sauer@fabulinus:~$ bash --posix -n ~/determined/determined/tools/k8s/fetch-creds.sh && echo ok
ok
```

But it's still not in /bin/sh when /bin/sh is dash, and Debian is traditionally pretty slow to update things like that in the stable branch.  So we'll probably see it in Ubuntu 36.04. :p

**Pull request merged**
