### PR TITLE
fix: model deital bugs

### PR DESCRIPTION
**Pull request by keita-determined**
## Description
[DET-7888] [DET-7848]

## Test Plan
- Check if we can update name, node, metadata, and description. Even after refresh the page, the updated data should be there.  Also, we can route to the version page property

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [ ] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

[DET-7888]: https://determinedai.atlassian.net/browse/DET-7888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-7848]: https://determinedai.atlassian.net/browse/DET-7848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mapmeld** [comment]
I think that these are good changes, but they only update links... did we find and fix the original ticket problem?

**Comment by mapmeld** [comment]
OK on review we actually do want the model paths to use `record.id` and not the name, because it's a more permanent link (name can be changed).

**Comment by keita-determined** [comment]
> I think that these are good changes, but they only update links... did we find and fix the original ticket problem?

[patchModel](https://github.com/determined-ai/determined/blob/master/webui/react/src/pages/ModelDetails.tsx#L282) requires modelName as a parameter. Currently, link is used ID instead of name. That's why its not working with the ticket problem. But I'll find a way to keep the permalink

**Comment by mapmeld** [comment]
`patchModel` should be able to see the ID is a number and adjust accordingly (`a.ModelFromIdentifier`)

**Comment by keita-determined** [comment]
> `patchModel` should be able to see the ID is a number and adjust accordingly on the server (`a.ModelFromIdentifier`)

But somehow it doesn't work right now, and when I used model name, it worked

**Comment by keita-determined** [comment]
It is not related but [this line](https://github.com/determined-ai/determined/pull/4640/commits/6a8018043c445e709e4ee11bcf32ffa840bd4539#diff-84ae63ef8b3a9d76b21ba552e425e32d39ed953241892423070ef0c13e721438R179) should be `id` instead of `name`?

**Review by mapmeld — APPROVED** [review]
Thanks for going through the changes, LGTM :+1:

**Pull request merged**
