### PR TITLE
fix: font and layout fix in project card

### PR DESCRIPTION
**Pull request by keita-determined**
## Description
[WEB-1044]

### Before

image

### After 

image

## Test Plan
- Check if project name font size is `13px`
- Check if workspace icon's width and heights are `20px`
- Check if layout doesnt get messy with various project name length

## Checklist

- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

[WEB-1044]: https://determinedai.atlassian.net/browse/WEB-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by EmilyBonar — COMMENTED** [review]
This works, in that it reduces the font size, but switching to grid and using template areas and some magic values seems like it's outside the scope of the ticket. I've asked Michiel to take another look at the design and we can move forward from there.

**Comment by keita-determined** [comment]
ok i removed magic values. 
if Michiel disagree with the grid layout change, i'll revert it

**Comment by ClaireNeveu** [comment]
Looks fine but we're not focused on being pixel-perfect right now because we still have a lot of inconsistencies.

**Review by johnkim-det — COMMENTED** [review]
looks like the tooltip for the workspace icon is now centered within the card instead of being aligned with the icon.

**Comment by keita-determined** [comment]
> looks like the tooltip for the workspace icon is now centered within the card instead of being aligned with the icon.

thanks for the UI bug report. i pushed the fix

**Review by johnkim-det — APPROVED** [review]

**Pull request merged**
