### PR TITLE
fix: system metric chart fix to support milliseconds [DET-5348]

### PR DESCRIPTION
**Pull request by apizzini**
## Description

Fixing this chart as per uPlot documentation instructions: https://github.com/leeoniya/uPlot/tree/master/docs#data-format

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by hkang1 — APPROVED** [review]
the code looks good, but I wasn't able to turn on system metrics for experiments. Is there a documented way of enabling this feature?

**Comment by apizzini** [comment]
Thanks for checking @armandmcqueen.

The zooming change is not really coming from this PR but from another one we merged some days ago.

I agree that the prev zooming was more intuitive on charts that are displaying time series data.

@hkang1 what do you think about adding a chart option to be able to select if a chart should have (or not) Y zooming enabled? (while keeping X axis zoom always enabled).

**Comment by armandmcqueen** [comment]
Ah in that case this PR is approved, but it would definitely be nice to have that chart zoom mode as an option.

**Comment by hkang1** [comment]
> @hkang1 what do you think about adding a chart option to be able to select if a chart should have (or not) Y zooming enabled? (while keeping X axis zoom always enabled).

Ah I see, that makes sense for this case. 👍

**Comment by apizzini** [comment]
@armandmcqueen, @hkang1: I've created [a separated issue for the zooming fix](https://determinedai.atlassian.net/browse/DET-5395). Merging this.

**Pull request merged**
