### PR TITLE
feat: master config option to enable notebook timeouts by default.

### PR DESCRIPTION
**Pull request by ioga**
## Description

- Add master config option for a global default notebook timeout setting.
- Support it in `det deploy aws` and enable it on latest-master.
- Refactor `det deploy aws` code a bit because I was tired of duplication.
- Refactor `IdleTimeoutWatcher` to have its config as embedded struct instead of field duplication.

## Test Plan

- Deploy a cluster with this option and check an idle notebook terminates as expected (which is pretty convoluted depending on `notebook_idle_type`, to be fair).
- `latest-master` should have less stale notebooks from all the people who don't terminate them.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by stoksc — APPROVED** [review]

**Review by garrett361 — COMMENTED** [review]
Very minor initial nits/questions:
* Why is only the `aws` code changed and not the `gcp` code?
* Is it a huge pain to change the time units from second to minutes? Seems unnecessarily precise, and a little annoying, to need to specify in terms of seconds?

**Comment by ioga** [comment]
>     * Why is only the `aws` code changed and not the `gcp` code?

Primarily because I need it on `aws` to make it work on latest-master. do you need this on gcp?

>     * Is it a huge pain to change the time units from second to minutes? Seems unnecessarily precise, and a little annoying, to need to specify in terms of seconds.

this is mostly a consistency problem. `tensorboard_timeout` any many other fixed unit values are also using seconds. 

ideally we'd use `model.Duration` for that, like expconf tends to do, but IIRC last time I tried to do this I run into some parsing oddities in master config.

**Comment by garrett361** [comment]
> do you need this on gcp?
I would expect any features available on aws to also work on gcp, especially since the docs don't list the feature as being platform-dependent

No problem about the units, only a minor inconvenience.

**Comment by ioga** [comment]
> I would expect any features available on aws to also work on gcp, especially since the docs don't list the feature as being platform-dependent. I'd expect it available on all other deployment options, similarly.
> 
> Is it way out of scope to request the above?
> 
> No problem about the units, only a minor inconvenience.

feature parity is a great doctrine, but I am also hesitant to add features which would have zero users (because no one would care enough to pass that option on their cluster creation). Maybe I can make this a spin-up ticket in the backlog which some new hire would pick up as day 2 work.

**Comment by garrett361** [comment]
>Maybe I can make this a spin-up ticket in the backlog which some new hire would pick up as day 2 work.

Sounds good to me. I'll approve and you can either merge and put in a ticket for the rest, or leave it all for the ticket? Up to you.

**Review by garrett361 — APPROVED** [review]
Approved with the understanding left in the comments.

**Pull request merged**
