### PR TITLE
chore: tighten to_json advertised type

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

we've been advertising to_json output on generated `Class` types as `Any` where we could use a stronger type
we change that here.
- address unmasked issues
- fix an index issue on an empty list of roles

## Commentary (optional)

TODO:
- [x] address linter complaints

could we soft-intro
https://mypy.readthedocs.io/en/stable/command_line.html#disallow-dynamic-typing

## Checklist
- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by hamidzr** [comment]
there shouldn't be any webui chanegs in here. master isn't the right state.

**Comment by hamidzr** [comment]
>           assert len(trials1[0].workloads) == len(trials2[0].workloads) == 7
> E           assert 7 == 8

**Review by nrajanee — APPROVED** [review]
lgtm

**Comment by hamidzr** [comment]
thanks for the review

**Pull request merged**
