### PR TITLE
feat: remove webhooks feature flag [WEB-560]

### PR DESCRIPTION
**Pull request by julian-determined-ai**
## Description

feat: remove webhooks feature flag [WEB-560]

Enables Webhooks in Determined by removing the feature flag that is gating the behavior.

## Test Plan

1. Log into Determined as an admin and ensure that the link in the navigation sidebar to the Webhooks listing page is visible.
2. Log into Determined as a non admin and ensure that the link in the navigation sidebar to the Webhooks listing page is not visible.

## Checklist
- [x] Changes have been manually QA'd
~- [ ] User-facing API changes need the "User-facing API Change" label.~
~- [ ] Release notes should be added as a separate file under `docs/release-notes/`.~
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
~- [ ] Licenses should be included for new code which was copied and/or modified from any external code.~

[WEB-560]: https://determinedai.atlassian.net/browse/WEB-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ClaireNeveu** [comment]
Before merging this can you do some e2e testing to ensure webhooks are good to go in latest master?

**Comment by mapmeld** [comment]
You can also remove 'webhooks' as an option in `src/hooks/useFeature.ts`

**Review by mapmeld — APPROVED** [review]
LGTM ✅

**Comment by julian-determined-ai** [comment]
After testing I am happy with how this is performing in latest master. I have spawned experiments and verified slack and default payloads. 

You can review updates that have been made here: https://github.com/determined-ai/determined/pull/5353 as well as testing directions. 

I am going to merge this in. 

The only functionality I have not tested in latest-master is including links to projects/workspaces/experiments in Slack messages because it is not really possible to set config values in latest master ad-hoc I have a PR to change this here: https://github.com/determined-ai/determined/pull/5354

**Pull request merged**
