### PR TITLE
test: increase timeouts for tensorboard test in test_task_logs

### PR DESCRIPTION
**Pull request by CanmingCobble**
## Description

This test has been very flaky:

tests/cluster/test_logging.py::test_task_logs[tensorboard-task_config3-^.*TensorBoard .* at .*$] - Failed: Timeout >300.0s

The default tensorboard idle time-out value is 5 minutes. If the tensorboard job has to download and build an image, it will hit the service idle timeout value before the expected log entry can appear in the logs. Increase the tensorboard idle timeout to 10 minutes should help.

The timeout value for test_task_logs should be greater than the tensorboard timeout value because it has to run an experiment to complete before starting tensorboard. The time to run the experiment is about 2-3 minutes.  

This happened in test-e2e-slurm-agent-singularity-znode on determined-ee main branch after increased test timeout to 10 minutes without increasing tensorboard idle_timeout.

```
tests/cluster/test_logging.py:119: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

log_regex = re.compile('^.*TensorBoard .* at .*$')
log_fn = functools.partial(<function task_logs at 0x7fc18d9b5dc0>, <determined.common.api._session.Session object at 0x7fc150492df0>, 'e194dd68-4346-4680-bbbc-60c18eccd22c')
log_fields_fn = functools.partial(<function get_TaskLogsFields at 0x7fc18d9ab3a0>, <determined.common.api._session.Session object at 0x7fc150492df0>, taskId='e194dd68-4346-4680-bbbc-60c18eccd22c')

    def check_logs(
        log_regex: Any,
        log_fn: Callable[..., Iterable[Log]],
        log_fields_fn: Callable[..., Iterable[LogFields]],
    ) -> None:
        # This is also testing that follow terminates. If we timeout here, that's it.
        for log in log_fn(follow=True):
            if log_regex.match(log.message):
                break
        else:
            for log in log_fn(follow=True):
                print(log.message)
>           pytest.fail("ran out of logs without a match")
E           Failed: ran out of logs without a match

tests/cluster/test_logging.py:143: Failed
---------------------------- Captured stdout setup -----------------------------
starting at 2023-08-07 16:26:33
----------------------------- Captured stdout call -----------------------------
[2023-08-07T21:26:49.899485Z]          || INFO: Scheduling TensorBoard (remarkably-rare-hound) (id: e194dd68-4346-4680-bbbc-60c18eccd22c.1)

[2023-08-07T21:26:49.976656Z]          || INFO: TensorBoard (remarkably-rare-hound) was assigned to an agent

[2023-08-07T21:26:49.976395Z] 94a42c23 || DEBUG: container requested network virtualization, but network creation isn't allowed; overriding to host networking

[2023-08-07T21:26:49.977121Z] 94a42c23 || WARNING: archive file /run/determined/etc/passwd has user 0:0 but agent can only write as 1002:10300, writing anyway

[2023-08-07T21:26:49.977171Z] 94a42c23 || WARNING: archive file /run/determined/etc/shadow has user 0:0 but agent can only write as 1002:10300, writing anyway

[2023-08-07T21:26:49.977187Z] 94a42c23 || WARNING: archive file /run/determined/etc/group has user 0:0 but agent can only write as 1002:10300, writing anyway

[2023-08-07T21:26:49.977410Z] 94a42c23 || DEBUG: singularity run \
	--writable-tmpfs \
	--pwd /run/determined/workdir \
	--env-file /tmp/determined-launcher-znode51/1890160161-94a42c23-e594-453b-a8b8-727468838036/envfile \
	--bind /tmp/determined-launcher-znode51/1890160161-94a42c23-e594-453b-a8b8-727468838036/archives/opt/determined:/opt/determined \
	--bind /tmp/determined-launcher-znode51/1890160161-94a42c23-e594-453b-a8b8-727468838036/archives/run/determined:/run/determined \
	--bind /tmp:/determined_shared_fs docker://determinedai/environments:py-3.8-pytorch-1.12-tf-2.11-cpu-6eceaca /run/determined/singularity-entrypoint-wrapper.sh /run/determined/tensorboard/tensorboard-entrypoint.sh /run/determined/tensorboard/storage_config.json /determined_shared_fs/determined-integration-checkpoints/8553db5d-4f89-42e2-bafd-c1d75b57f994/tensorboard/experiment/2/

[2023-08-07T21:26:49.978511Z] 94a42c23 || INFO: Resources for TensorBoard (remarkably-rare-hound) have started

[2023-08-07T21:26:50.493330Z] 94a42c23 || INFO: Converting OCI blobs to SIF format

[2023-08-07T21:26:50.539626Z] 94a42c23 || INFO: Starting build...

[2023-08-07T21:26:57.125387Z] 94a42c23 || INFO: 2023/08/07 16:26:57  info unpack layer: sha256:ca1778b6935686ad781c27472c4668fc61ec3aeb85494f72deb1921892b9d39e

[2023-08-07T21:26:57.967104Z] 94a42c23 || INFO: 2023/08/07 16:26:57  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1

[2023-08-07T21:26:57.969638Z] 94a42c23 || INFO: 2023/08/07 16:26:57  info unpack layer: sha256:db77652ffcca281bdaa9532302e6c10817e02593bc308eb964687e54716c34cc

[2023-08-07T21:26:57.970008Z] 94a42c23 || INFO: 2023/08/07 16:26:57  info unpack layer: sha256:692fd6a4452047970a6e0e98af70c736b8398c947a48b60cf7754dc734093834

[2023-08-07T21:27:02.270156Z] 94a42c23 || INFO: 2023/08/07 16:27:02  info unpack layer: sha256:18886ba58f6cc5768178af31973b351f829c6aca107cc11538efa47c5e827e8d

[2023-08-07T21:27:02.275155Z] 94a42c23 || INFO: 2023/08/07 16:27:02  info unpack layer: sha256:4708d7c4c7bdc352bc37db3b86acc7c4f3a38e93f6923ed466b2535739ce598d

[2023-08-07T21:27:04.540982Z] 94a42c23 || INFO: 2023/08/07 16:27:04  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1

[2023-08-07T21:27:04.543106Z] 94a42c23 || INFO: 2023/08/07 16:27:04  info unpack layer: sha256:10c64726101c6c510124196fe6f91411fde8a31356858ceab0bcee64d18c3dd8

[2023-08-07T21:27:07.262037Z] 94a42c23 || INFO: 2023/08/07 16:27:07  info unpack layer: sha256:c815ecc44925594c6df8284cd9b5a2d94d4df86971e9b9974d1949613ec7ab76

[2023-08-07T21:27:09.265468Z] 94a42c23 || INFO: 2023/08/07 16:27:09  info unpack layer: sha256:d88f8532744301388da9b6ff1642776d046875cfcedda2ad04b7c65302aae54c

[2023-08-07T21:27:09.334691Z] 94a42c23 || INFO: 2023/08/07 16:27:09  info unpack layer: sha256:eb4e4099396eb73120484a648f37b626fe7d5a88835c005a8e76f98175d0d802

[2023-08-07T21:27:09.336180Z] 94a42c23 || INFO: 2023/08/07 16:27:09  info unpack layer: sha256:0535c0f0db99406acffc57fff0607f2d710feee5bda3f7fd60a421aa526cd312

[2023-08-07T21:27:09.339369Z] 94a42c23 || INFO: 2023/08/07 16:27:09  info unpack layer: sha256:2fbe3f6ffbd8a3a322405bd35b8b8cc7dd078bb24292a4ea5fcc02dfdcd62d75

[2023-08-07T21:27:09.345021Z] 94a42c23 || INFO: 2023/08/07 16:27:09  info unpack layer: sha256:861b927e5834b35602973dff5748b630848097edc756d2dc1d645b01a19f4dd1

[2023-08-07T21:27:19.342236Z] 94a42c23 || INFO: 2023/08/07 16:27:19  info unpack layer: sha256:9927354308d51e2f489e80da2602d5cad1318b71d4d084b21a24d38f4171489e

[2023-08-07T21:27:27.732291Z] 94a42c23 || INFO: 2023/08/07 16:27:27  info unpack layer: sha256:405bd058c5163f60f080aea4cddcdc140e40c6e5b3db806bce0281a17615e1f7

[2023-08-07T21:27:34.082351Z] 94a42c23 || INFO: 2023/08/07 16:27:34  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1

[2023-08-07T21:27:34.085595Z] 94a42c23 || INFO: 2023/08/07 16:27:34  info unpack layer: sha256:87e3d73178175b143833e728ecc746ab3d2eb93d4223b22f5bd7d5bc2c83e722

[2023-08-07T21:27:34.846346Z] 94a42c23 || INFO: 2023/08/07 16:27:34  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1

[2023-08-07T21:27:34.847867Z] 94a42c23 || INFO: 2023/08/07 16:27:34  info unpack layer: sha256:0000e585f2138264bd7cbc4908f2d6986388568a9c462422d8fe900b1e82467e

[2023-08-07T21:27:35.643555Z] 94a42c23 || INFO: 2023/08/07 16:27:35  info unpack layer: sha256:2ae20846eba7150a52ec23cb0182633516b1fad617a1b5555aad9a4dabe8e6ce

[2023-08-07T21:27:36.709439Z] 94a42c23 || INFO: 2023/08/07 16:27:36  info unpack layer: sha256:83ce7e5dbb97692cc78c41a6caf104f0c4a90a1dba9e5552ebe8476b1a09b8d6

[2023-08-07T21:27:38.040550Z] 94a42c23 || INFO: 2023/08/07 16:27:38  info unpack layer: sha256:5553b558f399f9f32a2d6b88d413ee9dbb0a8adbdbec50e508f40a7aa20eb6b4

[2023-08-07T21:27:38.078307Z] 94a42c23 || INFO: Creating SIF file...

[2023-08-07T21:31:54.964696Z]          || INFO: forcibly killing allocation's remaining resources (reason: idle for more than 5m0s: service is inactive)

[2023-08-07T21:31:54.966121Z] 94a42c23 || INFO: killed: resources failed with non-zero exit code: request for action on unknown container: container is gone on reattachment

[2023-08-07T21:31:54.967404Z]          || INFO: TensorBoard (remarkably-rare-hound) was terminated: allocation killed after all resources exited: resources were killed
```

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by jerryharrow — APPROVED** [review]

**Review by stoksc — APPROVED** [review]

**Comment by stoksc** [comment]
idle timeout shouldn't start ticking until the thing first reports in, so something else is up here.

**Comment by stoksc** [comment]
@CanmingCobble can we hold off landing this? i'm worried this is a legitimate regression

**Comment by CanmingCobble** [comment]
> @CanmingCobble can we hold off landing this? i'm worried this is a legitimate regression

Okay

**Comment by stoksc** [comment]
Ok, so, this is kinda an unintended consequence of the pull actually happening after `RunContainer` returns in `agent/internal/container/container.go`. Ideally, we would wait to call `registerProxies`, which begins the idle timeout, until the singularity container has actually started. Or just make `RunContainer` block until we notice image pull is done. Either change is fairly involved though. So if we could file a ticket describing this, imo, unfortunate behavior, that would be sufficient.

**Comment by CanmingCobble** [comment]
Something had changed and this test now passes with only 36.48s runtime, seems too fast:

https://app.circleci.com/pipelines/github/determined-ai/determined-ee/8691/workflows/d9b53c7e-8581-41f7-a50f-c88cad1c2a59/jobs/383111

36.48s call     tests/cluster/test_logging.py::test_task_logs[tensorboard-task_config3-^.*TensorBoard .* at .*$]

**Comment by jerryharrow** [comment]
> Ok, so, this is kinda an unintended consequence of the pull actually happening after `RunContainer` returns in `agent/internal/container/container.go`. Ideally, we would wait to call `registerProxies`, which begins the idle timeout, until the singularity container has actually started. Or just make `RunContainer` block until we notice image pull is done. Either change is fairly involved though. So if we could file a ticket describing this, imo, unfortunate behavior, that would be sufficient.

So that explains the need for it the slurm+agent+singularity case, but I thought there were instances of a timeout even in the determined oss tests -- or wasn't that the case?

**Comment by jerryharrow** [comment]
> Something had changed and this test now passes with only 36.48s runtime, seems too fast:
> 
> https://app.circleci.com/pipelines/github/determined-ai/determined-ee/8691/workflows/d9b53c7e-8581-41f7-a50f-c88cad1c2a59/jobs/383111
> 
> 36.48s call tests/cluster/test_logging.py::test_task_logs[tensorboard-task_config3-^._TensorBoard ._ at .*$]

For some reason it is not needing to pull the image and therefore is launching quickly.   Perhaps this is the first non-cuda image in the test so after a version bump it needs to pull the new container and it ends up hitting in this test?

Here is the agent log for the test.   It looks like the ERRO is on termination and therefore expected?

```
TRAC[2023-08-10T00:49:36-05:00] requested image: determinedai/environments:py-3.8-pytorch-1.12-tf-2.11-cpu-2b7e2a1  component=singularity
TRAC[2023-08-10T00:49:36-05:00] singularity run \
	--writable-tmpfs \
	--pwd /run/determined/workdir \
	--env-file /tmp/determined-launcher-znode50/4058064507-7410f2a4-2997-4c09-9540-9d5592e0e77b/envfile \
	--bind /tmp/determined-launcher-znode50/4058064507-7410f2a4-2997-4c09-9540-9d5592e0e77b/archives/opt/determined:/opt/determined \
	--bind /tmp/determined-launcher-znode50/4058064507-7410f2a4-2997-4c09-9540-9d5592e0e77b/archives/run/determined:/run/determined \
	--bind /tmp:/determined_shared_fs docker://determinedai/environments:py-3.8-pytorch-1.12-tf-2.11-cpu-2b7e2a1 /run/determined/singularity-entrypoint-wrapper.sh /run/determined/tensorboard/tensorboard-entrypoint.sh /run/determined/tensorboard/storage_config.json /determined_shared_fs/determined-integration-checkpoints/5e578ffc-3d10-44cd-aaf6-8c73b7cad3c9/tensorboard/experiment/2/  component=singularity
TRAC[2023-08-10T00:49:36-05:00] Checking for supplied credentials             component=singularity
INFO[2023-08-10T00:49:36-05:00] started container 7410f2a4-2997-4c09-9540-9d5592e0e77b with pid 4002888  component=singularity
TRAC[2023-08-10T00:49:36-05:00] signal-to-context shimmer exited              component=container cproto-id=7410f2a4-2997-4c09-9540-9d5592e0e77b
TRAC[2023-08-10T00:49:36-05:00] transitioning to running state                component=container cproto-id=7410f2a4-2997-4c09-9540-9d5592e0e77b
INFO[2023-08-10T00:49:36-05:00] transitioning state from STARTING to RUNNING  component=container cproto-id=7410f2a4-2997-4c09-9540-9d5592e0e77b stop="<nil>"
TRAC[2023-08-10T00:49:36-05:00] in monitoring loop                            component=container cproto-id=7410f2a4-2997-4c09-9540-9d5592e0e77b
TRAC[2023-08-10T00:49:55-05:00] container signaled: killed                    component=container cproto-id=7410f2a4-2997-4c09-9540-9d5592e0e77b
ERRO[2023-08-10T00:49:55-05:00] failed to signal 4002888 with killed          component=container cproto-id=7410f2a4-2997-4c09-9540-9d5592e0e77b error="request for action on unknown container: container is gone on reattachment"
TRAC[2023-08-10T00:49:55-05:00] finalizing container exit                     component=container cproto-id=7410f2a4-2997-4c09-9540-9d5592e0e77b
INFO[2023-08-10T00:49:55-05:00] transitioning state from RUNNING to TERMINATED  component=container cproto-id=7410f2a4-2997-4c09-9540-9d5592e0e77b stop="container failed with non-zero exit code: request for action on unknown container: container is gone on reattachment"
TRAC[2023-08-10T00:49:55-05:00] proc 4002888 for container 7410f2a4-2997-4c09-9540-9d5592e0e77b exited with -1  component=singularity
TRAC[2023-08-10T00:49:55-05:00] forgetting completed container: 7410f2a4-2997-4c09-9540-9d5592e0e77b  component=singularity

```

**Comment by CanmingCobble** [comment]
That is probably expected, after checking the logs, the task was killed:
 
   finally:
        command._kill(master_url, task_type, task_id)

Unless you focus on this ERRO itself:
ERRO[2023-08-10T00:52:17-05:00] failed to signal 4005966 with killed          component=container cproto-id=6895b688-144c-4dd3-82f9-d14e9d16b382 error="request for action on unknown container: container is gone on reattachment"

**Comment by CanmingCobble** [comment]
>tests/cluster/test_logging.py::test_task_logs[tensorboard-task_config3-^.TensorBoard . at .*$]

Test passed in nightly.

**Pull request closed without merging**
