### PR TITLE
chore: enable mask closable by default for drawers

### PR DESCRIPTION
**Pull request by hkang1**
## Description

Allow mask/overlay click to dismiss the drawer.

## Test Plan

- [x] open user settings drawer
- [x] click on the mask/overlay (right hand side)
- [x] verify the drawer closes

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket
WEB-1572

### CODE REVIEW

**Review by hugcyrill — APPROVED** [review]
works as expected! drawer closes when clicking outside of it.

**Review by johnkim-det — APPROVED** [review]
LGTM

**Comment by keita-determined** [comment]
question: according to [this comment](https://github.com/determined-ai/determined/pull/7151#pullrequestreview-1482043350), the original drawer shouldnt close if the overlay is clicked. Are we sure we wanna change it?

**Comment by hkang1** [comment]
> question: according to [this comment](https://github.com/determined-ai/determined/pull/7151#pullrequestreview-1482043350), the original drawer design requirement was that it shouldnt close if the overlay is clicked. Are we sure we wanna change it?

Yeah it was the original spec, but after it was live and in use, I think it solicited enough complaints about it. Also posted in design to get their thoughts and they agree with the overlay dismissal.

**Pull request merged**
