### PR TITLE
chore: upgrade mockery to latest

### PR DESCRIPTION
**Pull request by stoksc**
## Description
Since mockery parses source code, it tends to be extra sensitive to new versions of Go, so it makes sense to keep it up to date. Specifically though, mockery is hitting a strange error in some cases in determined ee and this upgrade fixes it.

## Test Plan
- [x] make sure build that failed was passing in slurm branch

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ioga** [comment]
I recall I had to pin mockery to a specific version because it'd drift away from go.mod / go.sum and cause the CI to fail
Maybe we should pin it to the current latest version number instead?

**Comment by stoksc** [comment]
@ioga maybe previously, but now we just use the tool. mockery isn't in the go.mod/go.sum anymore.

**Comment by stoksc** [comment]
but, sure, I changed it.

**Review by jerryharrow — APPROVED** [review]

**Comment by stoksc** [comment]
@ioga bump re-review?

**Review by ioga — APPROVED** [review]
lgtm

**Pull request merged**
