### PR TITLE
fix: update column order in ExperimentTrials table

### PR DESCRIPTION
**Pull request by johnkim-det**
## Description

Allow columns to be reordered by drag-and-drop on the Trials tab for a multi-trial experiment.

## Test Plan

On the Experiment Details page for a multi-trial experiment:
- [ ] Open the "Trials" tab
- [ ] Drag and drop a column to change the order
- [ ] Order should change appropriately

## Commentary (optional)

This was previously changed on purpose to always show `DEFAULT_COLUMNS` no matter what in https://github.com/determined-ai/determined/pull/5634.

I'm not reproducing the issue that caused that change, so I think reverting it should suffice here.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

WEB-1179

### CODE REVIEW

**Comment by ClaireNeveu** [comment]
It looks like you're just undoing this earlier fix: https://github.com/determined-ai/determined/pull/5634

**Comment by johnkim-det** [comment]
> It looks like you're just undoing this earlier fix: #5634

Saw that and called it out above -- unless I'm misunderstanding the issue, I don't think I'm reproducing the reason for that fix. Guessing that subsequent changes around settings may have addressed that problem. @mapmeld worked on the previous fix so I'm hoping he can verify as part of this review.

**Comment by ClaireNeveu** [comment]
The previous issue only occurred if you had bad data in your DB which is not something we can fix since we're self-install. The issue is that you can _omit_ columns with the code you reverted to. You should rewrite it to preserve order without  opening the possibility of omitting columns.

**Review by mapmeld — APPROVED** [review]
Approving with comments

My understanding of UseSettings bugs circa December was that once a user ever stored malformed settings into their system, they would continue seeing that problem unless there's an easy way to customize the table and store new settings. At that time [we also used "`experiment-trials-list`"](https://github.com/mapmeld/determined/blob/9841b588dff18d855458149ed8e5afea20a04919/webui/react/src/pages/ExperimentDetails/ExperimentTrials.settings.ts) as the storagePath which shared any bad settings across experiments

Now that we have an experiment-specific storagePath for these settings, I would think this user would no longer be reviving their old settings.

**Pull request merged**
