### PR TITLE
fix: upload helm chart to GitHub release artifacts [INFENG-93]

### PR DESCRIPTION
**Pull request by asnelling**
## Description

[INFENG-93]

## Test Plan

I haven't found a good way to test without sweeping changes to the CI config. Will try to come up with something doable.

## Checklist
- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [ ] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

## Title

fix: upload helm chart to GitHub release artifacts

[INFENG-93]: https://determinedai.atlassian.net/browse/INFENG-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by asnelling** [comment]
For testing, I had to:
1. Create a separate repo
2. In `./.circleci/config.yml`:
    - comment out the `login-helm` step under the `publish-helm` job
    - comment out all `workflows` except for `release`
3. put a tag name in `./VERSION`
4. comment out in `./helm/Makefile` under the `release` target:
    - `helm repo add ...`
    - `helm cm-push ...`
5. set `GITHUB_TOKEN` environment variable in CircleCI
6. Create a release tag, e.g. `0.19.4`
7. push above changes and tag to the separate repo

**Comment by dannysauer** [comment]
> For testing, I had to:

What were the results of this test? :)

**Comment by asnelling** [comment]
The test run created this release with linked helm chart:
https://github.com/asnelling/determined/releases/tag/0.19.3-helm9

Here's the full set of changes for the test:
https://github.com/asnelling/determined/compare/master..0.19.3-helm9

**Review by dannysauer — APPROVED** [review]
LGTM

**Comment by dannysauer** [comment]
I think I would've liked to make another symlink and install goreleaser in the makefile so the process would work outside of CircleCI, but this works. So maybe call it tech debt for later. 🤷‍♂️

**Comment by asnelling** [comment]
It worked... but it published a release (with helm chart) for 0.19.4-rc0. Started a fix in https://github.com/asnelling/determined/commits/helm-release-gh
Current status with testing:

**release test:** no `-rc#` suffix
- `publish-helm-gh` runs
- https://app.circleci.com/pipelines/github/asnelling/determined/53/workflows/8a95e11f-8a9e-4a97-b83e-fb60db1a0401
- Just need to fix up the syntax here and that should do it:
https://github.com/asnelling/determined/blob/cb59496d7712c8e77015ec213386f942898d4df9/helm/Makefile#L34

**rc test:** with `-rc#` suffix
- `publish-helm-gh` is not scheduled
- https://app.circleci.com/pipelines/github/asnelling/determined/49/workflows/3f93156b-8f88-4682-9315-346fe6a5dd51

**Pull request merged**
