### PR TITLE
build: switch old -o json usage to --json

### PR DESCRIPTION
**Pull request by hamidzr**
followup to https://github.com/determined-ai/determined/pull/3387

## Test Plan

`ag det -C 10 | grep config -C 3 | ag -C 2 -- '(-o|--output|--json)' | less`
- run post merge tests

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hamidzr** [comment]
@ioga do you know of any spots I might have missed? I'll request all the tests to run

**Review by ioga — APPROVED** [review]
no, I am not aware of any

**Comment by hamidzr** [comment]
partly related: potentially something we want to do later https://github.com/determined-ai/determined/pull/3480 to move the tests to not go through cli

**Comment by ioga** [comment]
why?

we could test it "directly" through the API, but we don't have any users for the API (while we do have them for CLI).
so, from a certain perspective, using CLI in tests instead of API allows us to test it alongside the backend.

**Comment by hamidzr** [comment]
all tests passed except the deploy test. it seems like that's due to the [s3 bucket name size limit ](https://determined-ai.slack.com/archives/C9LFPNA3Y/p1643756294331409?thread_ts=1643744755.627349&cid=C9LFPNA3Y)

**Comment by hamidzr** [comment]
I haven't given it too much thoughts but testing through the cli seems better than no cli test all but separate cli test seems easier to diagnose, run, etc

**Comment by hamidzr** [comment]
> why?
> 
> we could test it "directly" through the API, but we don't have any users for the API (while we do have them for CLI). so, from a certain perspective, using CLI in tests instead of API allows us to test it alongside the backend.

I haven't given it too much thoughts but testing through the cli seems better than no cli test all but separate cli test seems easier to diagnose, run, etc

**Pull request merged**
