### PR TITLE
fix: word break in description

### PR DESCRIPTION
**Pull request by keita-determined**
## Description
I found that sentences in description are sometimes invisible when width is narrow and sentences are long.
Sentences should be always visible 

### Before

https://user-images.githubusercontent.com/109113616/182296754-9b0c0136-1909-4903-860d-3d43cc76d876.mov

### After

https://user-images.githubusercontent.com/109113616/182296648-db2b52db-377c-4efa-895b-829aceb29481.mov

## Test Plan
- Check if sentences are visible in any length and type of sentences and description width

## Commentary (optional)
Description in experiment detail has 500 letters limit but the one in experiment list doesnt. Should we add one?

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [ ] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by trentwatt** [comment]
can you add screen shots of experiment details and experiment list pages before and after?

> Description in experiment detail has 500 letters limit but the one in experiment list doesnt. Should we add one? 
sgtm.

**Comment by keita-determined** [comment]
> can you add screen shots of experiment details and experiment list pages before and after?

I added them in description

**Review by trentwatt — APPROVED** [review]
Looks like this just affects when single word is really long?  looks good to me.

**Comment by keita-determined** [comment]
> Looks like this just affects when single word is really long? looks good to me.

Yes. Someone might put a link in description, so i think we should handle it

**Pull request merged**
