### PR TITLE
ci: alternate mechanism for running nightly tests

### PR DESCRIPTION
**Pull request by dannysauer**
## Description

Switch logic for on-demand nightly test execution to use dynamic config so parameters can be injected at "runtime".  Also move to github-read context instead of github-write, since we really only need read-only access to get PR labels.

## Test Plan

1. Run regular PR with no labels.  See if nightly is skipped and it doesn't return failure.
2. Add the ci-run-nightly label.  See if the nightly tests run.
3. ???
4. Profit

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by dannysauer** [comment]
Test results:

- https://app.circleci.com/pipelines/github/determined-ai/determined/46936
  - without label (no nightly run; everything else _seems_ ok)
- https://app.circleci.com/pipelines/github/determined-ai/determined/46938
  - with label (includes nightly and nightly_quarentine; also _seems_ ok)

**Comment by dannysauer** [comment]
I've tried a few ways, and there's no good way to make git realize that the file was renamed and changed.  The problem is renaming the file and then adding a new file with the old filename just confuses git.  I've broken it up into three commits in this PR so there's some chance of actual successful review if you go commit by commit.  The only way to make this something which rebases cleanly would be to do two or three separate PRs with broken CircleCI in between, and that just feels like it'd be almost as annoying as simply resolving the conflicts later.  Git sucks. :rofl:

**Review by loksonarius — APPROVED** [review]
Godspeed

**Review by erikwilson — APPROVED** [review]
I like the idea of breaking out the config into smaller configs, it would make the test setup a lot easier to read.

my one unimportant nit is that some name other than real_config.yml might be good, perhaps something like all_tests.yml

**Review by dzhu — APPROVED** [review]
Another unimportant proposal/note for the future: We could also go back to having nightly runs not run non-nightly tests, which was lost when this changed recently.

I can't claim to have looked at the wrapper too closely, but if it appears to do the right thing, I say ship it!

**Pull request merged**
