### PR TITLE
test: ensure make unslurmcluster always runs in CI

### PR DESCRIPTION
**Pull request by stoksc**
## Description
When cluster creation fails halfway, `pkill determined-mast` will exit with 1. CircleCI runs these inline script with `set -e`, so that failure causes `make unslurmcluster` to no run, leaving stray TF resources behind.

## Test Plan

Is a test.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by stoksc** [comment]
Added you as a reviewer @dannysauer since I told you I'd do this on a thread yesterday.

**Review by dannysauer — APPROVED** [review]
Still gon' leave resources around if the job is interrupted by a second PR or otherwise canceled (because CircleCI has no finalizer), but this is an improvement either way. :)

**Comment by stoksc** [comment]
Yeah, I agree, this probably needs to get added to the terminator script at some point. But this at least fixes the specific issue that caused us to have an explosion of vpcs.

**Comment by stoksc** [comment]
merging over some unrelated failures

**Pull request merged**
