### PR TITLE
feat: add SAML Config to OSS with new fields to autoprovision SAML users

### PR DESCRIPTION
**Pull request by salonig23**
## Description

Added SAML Config to OSS and added fields related to auto-provisioning and syncing user data and groups to the config

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by carolinaecalderon — APPROVED** [review]
Interesting that this hasn't been back-ported to OSS before. 
My original reaction was that this PR wasn't needed because the SAML config is pretty well contained in EE -- however I see that we include similar files for OIDC in OSS. @NicholasBlaskey any context here?
As long as `master/internal/config/saml_config.go` is literally a copy of what's in EE, then given the OIDC precedent, we're good to merge.

**Review by stoksc — APPROVED** [review]

**Comment by stoksc** [comment]
yeah, this is fine with me; nothing really should be using it but we needed OIDC in OSS for part of saloni's other pr. i saw put everything in oss we can get away with, configs are in public docs anyway.

**Comment by stoksc** [comment]
or, i guess we never did actually end up using the OIDC config.. hmm. the only second thought i have with putting the config here is a saml/oidc change because 2 changes and requires a rebase, and folks may forget it. wdyt @carolinaecalderon? since we didn't end up using it, we could put it back.

**Comment by carolinaecalderon** [comment]
> or, i guess we never did actually end up using the OIDC config.. hmm. the only second thought i have with putting the config here is a saml/oidc change because 2 changes and requires a rebase, and folks may forget it. wdyt @carolinaecalderon? since we didn't end up using it, we could put it back.

I am leaning towards keeping all OIDC/SAML files in EE only. I think it's better practice to keep all related files contained in the same repo. Otherwise, when future developers want to make changes it's confusing to split them up into two PRs just because the OSS repo contains 1/2 the files they might touch. If Saloni's other PR doesn't need the OIDC config then we should move it all back to EE.

**Comment by stoksc** [comment]
I'm ok with that, let's do it.

**Pull request closed without merging**
