### PR TITLE
fix: modify user session token set for external session

### PR DESCRIPTION
**Pull request by cjmanna**
## Description
Modify user session token set in task launch so that external sessions have the correct token set.

## Test Plan
Open a jupyter notebook on an externally-managed cluster and try using the `det` CLI.

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

DET-8777

### CODE REVIEW

**Review by mackrorysd — COMMENTED** [review]
So I don't see anything *wrong* with this, but I am concerned that we don't know why it's necessary. Regardless of the way the token gets interpreted by master, whether as a regular session token that maps to a row in the database vs. a true JWT, it is always provided as a bearer token, and then assigned to taskSpec.UserSessionToken. Everything being done here seems like what should have been happening before. So why does it work for regular tokens already? Can we find an answer for that just to be sure?

**Comment by cjmanna** [comment]
> So I don't see anything _wrong_ with this, but I am concerned that we don't know why it's necessary. Regardless of the way the token gets interpreted by master, whether as a regular session token that maps to a row in the database vs. a true JWT, it is always provided as a bearer token, and then assigned to taskSpec.UserSessionToken. Everything being done here seems like what should have been happening before. So why does it work for regular tokens already? Can we find an answer for that just to be sure?

I'm not sure I fully understand the question. Regular tokens already work because as a part of the task creation flow, a session token is generated and signed by the user's private key and then assigned to `taskSpec.UserSessionToken`. Now, task creation checks to see if the cluster is externally-managed, and if so, assigns the externally-managed token to the field instead. If the question is why the external token is required to run `det` CLI on the cluster, I was hoping you would know the answer to that 😅 if not, agreed, we should find out why that is

**Comment by mackrorysd** [comment]
> I'm not sure I fully understand the question. Regular tokens already work because as a part of the task creation flow, a session token is generated and signed by the user's private key and then assigned to `taskSpec.UserSessionToken`. Now, task creation checks to see if the cluster is externally-managed, and if so, assigns the externally-managed token to the field instead. If the question is why the external token is required to run `det` CLI on the cluster, I was hoping you would know the answer to that sweat_smile if not, agreed, we should find out why that is

The question is: since both kinds of token are provided to the service as bearer tokens in the Authorization header, why was one passed to the container but not the other? In any case: I don't see risks to this change and it fixes real problems, so I think we should proceed before the release tomorrow regardless.

**Comment by cjmanna** [comment]
> The question is: since both kinds of token are provided to the service as bearer tokens in the Authorization header, why was one passed to the container but not the other? In any case: I don't see risks to this change and it fixes real problems, so I think we should proceed before the release tomorrow regardless.

ah I understand. I'm not sure why the task token is separated from the one sent with the request, maybe we can get someone on backend to weigh in? cc @NicholasBlaskey @stoksc

**Comment by NicholasBlaskey** [comment]
> > The question is: since both kinds of token are provided to the service as bearer tokens in the Authorization header, why was one passed to the container but not the other? In any case: I don't see risks to this change and it fixes real problems, so I think we should proceed before the release tomorrow regardless.
> 
> ah I understand. I'm not sure why the task token is separated from the one sent with the request, maybe we can get someone on backend to weigh in? cc @NicholasBlaskey @stoksc

I'm not sure if I am following correctly.

The task token is separate from the one sent with the request because we delete the task token when the task completes, so if you run a notebook and complete the notebook you don't get unexpectedly logged out of the CLI / webui. 

Conversely, if you log out of the CLI we delete the token, which would cause you to unexpectedly log out of any running notebook sessions.

**Pull request merged**
