### PR TITLE
fix: update icon codes

### PR DESCRIPTION
**Pull request by julian-determined-ai**
## Description

New font files were generated recently, and a subset of the icon codes that we use and are referenced changed but were not updated. This PR updates our `icons.scss` file with the correct codes. 

The codes come from `icomoon`, a snippet of the codes are show below. 

Screen Shot 2022-09-09 at 1 26 33 PM

## Test Plan
1. Navigate through the WebUI and ensure that the icons expected are shown.
2. Alternatively, go to `IcoMoon`, click `Generate Font`, and double check that all the codes and icons match up.

## Checklist
- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [ ] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

### CODE REVIEW

**Review by mapmeld — APPROVED** [review]
icons look right on local build

**Review by keita-determined — APPROVED** [review]
LGTM. Thanks for the fix

**Comment by keita-determined** [comment]
@julian-determined-ai 
You need to make a PR as upstream (not from forked) to pass `downstream` test

**Comment by julian-determined-ai** [comment]
Opened https://github.com/determined-ai/determined/pull/5002 which is a duplicate of this PR.

**Pull request closed without merging**
