### PR TITLE
fix: consistent total slot calculation for cluster overview [DET-7182]

### PR DESCRIPTION
**Pull request by hamidzr**
## Test Plan

before: 
Screen Shot 2022-05-04 at 14 52 49

after: 
Screen Shot 2022-05-05 at 08 59 31

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by EmilyBonar — APPROVED** [review]
LGTM, though do you need to make this change in `pages/Clusters` as well?

**Comment by hamidzr** [comment]
ah I didn't consider the /clusters page. is that unreleased for now? we might wanna move this new totalSlot calculation into STore 🤔

**Comment by hamidzr** [comment]
I won't get to change the unreleased page today. if this ends up blocking the release feel free to land as this change on its own should be a net improvement for user experience.

**Comment by hamidzr** [comment]
I updated the dev clusters page as well. there was a number of related duplicated code as well which I cleaned up. (hopefully without any mistakes) https://github.com/determined-ai/determined/pull/4080/commits/fd9ac7041838eff20fa1b1e538b8ec4a96b5c300

**Pull request merged**
