### PR TITLE
chore: remove max agents count in resource pool card's header

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

We've gone back and forth on how to convey this information in a sentence. The idea here is that `x/y connected` implies that we have agents running that are not connected.

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Review by davetroiano — APPROVED** [review]
lgtm!

**Review by hkang1 — APPROVED** [review]
Thanks for the quick update!

**Comment by hamidzr** [comment]
aah forgot to wait for @shiyuann. let me know if you have any comments and I can add it to another pr.

**Comment by shiyuann** [comment]
@hamidzr looks good to me!

**Pull request merged**
