### PR TITLE
fix: SearchDetails Pivot bug [ET-632]

### PR DESCRIPTION
**Pull request by johnkim-det**
## Ticket

ET-632

## Description

Refreshing Search Details page displays Pivot options with an incorrect left offset:
Screenshot 2024-07-15 at 3 16 33 PM

## Test Plan

Refresh a Search Details page. Should display all Pivot options in correct position, without cutting off or obscuring any of them:

Screenshot 2024-07-15 at 3 16 40 PM

## Checklist

- [ ] Changes have been manually QA'd
- [ ] New features have been approved by the corresponding PM
- [ ] User-facing API changes have the "User-facing API Change" label
- [ ] Release notes have been added as a separate file under `docs/release-notes/`
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses have been included for new code which was copied and/or modified from any external code

[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by keita-determined — APPROVED** [review]
\o/

**Comment by keita-determined** [comment]
the unit test failed

**Comment by keita-determined** [comment]
probably its a good idea to write the reason why removing the test file.

**Comment by johnkim-det** [comment]
fixing this bug revealed that the test cases were only passing in a situation where there was no experiment fetched. When we do have an experiment, tests then need to correctly render `FlatRuns`, `ExperimentCodeViewer`, `Notes`, `Page`, and `ExperimentDetailsHeader`, in addition to, of course, `Pivot`, which is the only thing really being tested by the existing test case. There are errors for several of those components, which *could* be addressed in `SearchDetails.test.tsx`... But it feels like making sure all of that works together is best handled by an e2e test? And also that unit tests for the components used by the pages would be more appropriate than trying to "unit test" the entire page.

created ET-634 and ET-635 to capture additional unit testing.

**Pull request merged**
