### PR TITLE
fix: update resource pool job queues to paginate properly

### PR DESCRIPTION
**Pull request by hkang1**
## Description

UPDATE: There is a separate issue of the pagination happening on the backend but the filtering happening on the frontend. This will be addressed separately.

The table pagination buttons and page size picker on the resource pool job queue tabs do not work.

https://user-images.githubusercontent.com/220971/179803401-2d1721cb-0f93-4e2e-888c-8d21c8f07d8d.mov

Also related, the user settings hook is making calls to the use settings API but not currently handling errors.

Screen Shot 2022-07-19 at 9 55 50 AM

## Test Plan

- [ ] check that the table pagination and the page size picker works for resource pool queue tabs
- [ ] check on dev that the user setting update failures don't trigger the react error breaks

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hkang1** [comment]
@gt2345 can you take a look at the user settings portion and see if that's reasonable?

**Comment by hamidzr** [comment]
how do you generate or mock the jobs to tests? 

```
diff --git a/webui/react/src/services/apiConfig.ts b/webui/react/src/services/apiConfig.ts
index fd27fca33..c6d013164 100644
--- a/webui/react/src/services/apiConfig.ts
+++ b/webui/react/src/services/apiConfig.ts
@@ -5,6 +5,7 @@ import { serverAddress } from 'routes/utils';
 import * as Api from 'services/api-ts-sdk';
 import * as decoder from 'services/decoder';
 import * as Service from 'services/types';
+import { generateAlphaNumeric } from 'shared/utils/string';
 import * as Type from 'types';
 
 import { DetApi, EmptyParams, RawJson, SingleEntityParams } from '../shared/types';
@@ -1094,6 +1095,31 @@ export const getJobQueue: DetApi<
   name: 'getJobQ',
   postProcess: (response) => {
     response.jobs = response.jobs.filter((job) => !!job.summary);
+    if (response.jobs[0]?.summary?.state)
+      response.jobs[0].summary.state = Type.JobState.QUEUED;
+    response.jobs = [
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+      ...response.jobs,
+    ];
+    response.jobs.forEach((j) => j.jobId = generateAlphaNumeric(10));
     // we don't work with jobs without a summary in the ui yet
     return response as Service.GetJobsResponse;
   },
```
doesn't lead to a functional UI

**Comment by hkang1** [comment]
> thanks for working on this. how do you generate or mock the jobs to tests? or do we already have a cluster?
> 
> ```
> diff --git a/webui/react/src/services/apiConfig.ts b/webui/react/src/services/apiConfig.ts
> index fd27fca33..c6d013164 100644
> --- a/webui/react/src/services/apiConfig.ts
> +++ b/webui/react/src/services/apiConfig.ts
> @@ -5,6 +5,7 @@ import { serverAddress } from 'routes/utils';
>  import * as Api from 'services/api-ts-sdk';
>  import * as decoder from 'services/decoder';
>  import * as Service from 'services/types';
> +import { generateAlphaNumeric } from 'shared/utils/string';
>  import * as Type from 'types';
>  
>  import { DetApi, EmptyParams, RawJson, SingleEntityParams } from '../shared/types';
> @@ -1094,6 +1095,31 @@ export const getJobQueue: DetApi<
>    name: 'getJobQ',
>    postProcess: (response) => {
>      response.jobs = response.jobs.filter((job) => !!job.summary);
> +    if (response.jobs[0]?.summary?.state)
> +      response.jobs[0].summary.state = Type.JobState.QUEUED;
> +    response.jobs = [
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +      ...response.jobs,
> +    ];
> +    response.jobs.forEach((j) => j.jobId = generateAlphaNumeric(10));
>      // we don't work with jobs without a summary in the ui yet
>      return response as Service.GetJobsResponse;
>    },
> ```
> 
> doesn't lead to a functional UI

The pagination is driven by the `pagination` field from the API response, rather than the actual payload. Specifically the `total` count that gets returned.

**Review by hamidzr — APPROVED** [review]
lgtm. I tested by submitting many jobs:

```
for i in $(seq 1 50); do det e create ./examples/tutorials/mnist_pytorch/const.yaml ./examples/tutorials/mnist_pytorch &
done
```
I saw an endpoint failing in the background but that could be the proxy I was using `scripts/proxy..`
/tasks/count

**Comment by hkang1** [comment]
> lgtm. I tested by submitting many jobs:
> 
> ```
> for i in $(seq 1 50); do det e create ./examples/tutorials/mnist_pytorch/const.yaml ./examples/tutorials/mnist_pytorch &
> done
> ```
> 
> I saw an endpoint failing in the background but that could be the proxy I was using `scripts/proxy..` /tasks/count

Thanks @hamidzr 🙏

**Pull request merged**
