### PR TITLE
chore: TrialsComparisonModal style fixes [WEB-1919] [WEB-1909]

### PR DESCRIPTION
**Pull request by mapmeld**
## Description

Addresses an Antd / UI Kit  ticket, plus a bug ticket, around the `TrialsComparisonModal`

- Replaces `antd.Tag` with `Row` containing `Label` and close icon button
- Updates `colSpan` to cover multiple experiments or multiple trialIds (+1 to include original column)

As used in multi-trial experiment trials table:

Screen Shot 2024-01-10 at 5 03 44 PM

-

As used in the experiments Glide Table:

Screen Shot 2024-01-10 at 5 03 32 PM

## Test Plan

Open a multi-trial experiment such as `/det/experiments/1290/trials`. Check to select multiple trial rows. In the action menu, select Compare trials to open the modal

Open a project such as `/det/projects/1/experiments`. Check multiple successful / completed experiments which can be compared.
Open the Compare section using the button at top right of the table.
In the Compare section, click the Details tab to see the table as used here

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by keita-determined — COMMENTED** [review]
minor bug
the `x` button's z-index value looks incorrect

https://github.com/determined-ai/determined/assets/109113616/b50a58aa-9144-44a1-b998-555638d38820

**Comment by mapmeld** [comment]
@keita-determined good catch! I selected more experiments in Uncategorized so that the issue would be visible. Then I added a z-index css rule to the top-left table header (adding z-index to the button did not help)

**Review by keita-determined — COMMENTED** [review]
one more little thing: header z-index should be bigger than dropdown

https://github.com/determined-ai/determined/assets/109113616/bbf88694-5101-48b7-b12e-a63f2f53ad4d

---

also `X` button in the header doesnt do anything.

**Comment by mapmeld** [comment]
I think this new z-index gives us the right order of z-index es

The left column cannot be visible in the top left unless we made a special case for dropdowns

Screen Shot 2024-01-16 at 1 40 44 PM

**Review by keita-determined — APPROVED** [review]
LGTM

**Pull request merged**
