### PR TITLE
feat: WebUI expand workspace configuration [WEB-33]

### PR DESCRIPTION
**Pull request by gt2345**
## Description

Add Web UI allowing user to:

Configure optional agent uid, gid, username, and groupname on workspace level. This will enable workspace-level ownership of files for shared_fs checkpoint storage.

Sanity check: agent uid and username must be either null or not null together, agent gid and groupname also must be null or not null together.

This is referred to as “AgentUserGroup” in the code. Docs: [User Accounts - Determined AI Documentation](https://docs.determined.ai/latest/cluster-setup-guide/users.html?highlight=agent%20user#run-tasks-as-specific-agent-users).

This feature is referring to posix users and groups, not determined user and group concepts.

Configure [checkpoint storage](https://docs.determined.ai/latest/reference/reference-training/experiment-config-reference.html#checkpoint-storage), including cloud credentials on workspace level. This will enable shared workspace-level checkpoint storage config and credentials, meaning the user won’t have to specify these on per-experiment (inconvenient) or cluster-wide (security issue) basis.

Sanity checks: checkpoint storage is in yaml format in front end, and it’ll be validated on the backend by expconf validation.

RBAC access control:

Create/Update: 
Use PERMISSION_TYPE_SET_WORKSPACE_AGENT_USER_GROUP permission to check whether the user has access to modify agent user group.  
Use PERMISSION_TYPE_SET_WORKSPACE_CHECKPOINT_STORAGE_CONFIG permission to check whether the user has access to modify checkpoint storage.  

OSS access control:

Administrators only.

Screen shots:
Screen Shot 2022-11-08 at 11 20 58 AM

## Test Plan

On OSS
Log in as admin
Click plus sign on nav bar or navigate to workspace list page and click "New Workspace"
Create a workspace with agent user group information and checkpoint storage config
(note that checkpoint storage config is only validate as YAML at front end, it's content is validated on the backend)
At the top left, click "Edit" to verify all fields show up as entered.
Select to random workspace and click "Edit"
Edit agent user group information and checkpoint storage config
Click "Edit" again or inspect the Network tab to verify edit has took effect.
Log in as non-admin user
When creating/editing workspace, can only config workspace name.

On RBAC
Log in with "ClusterAdmin" role assigned
Repeat test steps as admin in OSS
Log in with "WorkspaceAdmin" role assigned
Repeat test steps as admin in OSS except that agent user group would not be visible

## Commentary (optional)

Workspace edit modal has been removed because with new added functions of workspace configuration, it would be too much of duplication if create modal and edit modal kept separate.

## Checklist
- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by julian-determined-ai** [comment]
Looks like the `Edit` workspace form does not correctly show the right information, it continues to show the first workspace that was loaded: 


https://user-images.githubusercontent.com/103522725/200659167-38f3a794-1f72-4355-98dc-2f2ecf7df6e4.mov

**Comment by gt2345** [comment]
> Looks like the `Edit` workspace form does not correctly show the right information, it continues to show the first workspace that was loaded:
> 
>  79BEED42-E3FF-4486-AE8B-1F0348EECF97.mov

@julian-determined-ai  Thank you for catching this, it should work now~

**Review by julian-determined-ai — APPROVED** [review]
Approving the changes from a FE standpoint. One minor nit, when a user enters invalid YAML we simply show a long and unhelpful error message from the backend 

`bad StructValue: json: cannot unmarshal string into Go value of type map[string]json.RawMessage`

it would be nice to show something like "invalid yaml" or similar instead to the user which is more clear and actionable.

**Review by ioga — APPROVED** [review]
lgtm

**Pull request merged**
