### PR TITLE
fix: Add theme to TableFilterDropdown [WEB-1952]

### PR DESCRIPTION
**Pull request by julian-determined-ai**
## Description

For some reason the `TableFilterDropdown` components lost their styling. These components open in a portal outside of the application root components, and were not being wrapped in the `themeClass` therefore they did not have the correct styling applied. 

This fixes the theming issue by adding the `themeClass` the the dropdowns.

## Test Plan
1. Visit pages with Tables in the application, for example the Tasks or Model Registry page. 
2. Click the filters on the table and ensure that styling is correctly applied to the dropdown component. 

## Checklist

- [x] Changes have been manually QA'd
- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket
WEB-1952

### CODE REVIEW

**Comment by johnkim-det** [comment]
still appearing themeless on netlify preview?

**Comment by julian-determined-ai** [comment]
@johnkim-det I can't reproduce the bug locally now hmmm looks like I need to investigate more

**Review by ashtonG — COMMENTED** [review]
can we fix this at `Table`/`ResponsiveTable` so this doesn't come up again?

**Comment by johnkim-det** [comment]
Notes: 
- Went ahead and added `themeClass` to the antd `Table` in `ResponsiveTable`. However, it looks like the dropdowns are not actually descendants of the Table component. I think this is why the custom dropdown components we pass to the antd `Table` column config still need the `themeClass` applied.
- `themeClass` added to `TableFilterDropdown` works fine in general (border-radius for Task state badges looks right, for example). The only issue is that font-family is not applied correctly in prod mode. Addressing this for now by explicitly making `TableFilterDropdown` use the `--theme-font-family` variable. Still not sure why this is only an issue in prod mode, but this fix should address it for release.

**Pull request merged**
