### PR TITLE
feat: add buf breaking change detection [DET-4209]

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

add breaking change check and a make target to update the baseline.

docs from buf https://buf.build/docs/breaking-usage

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Review by stoksc — APPROVED** [review]
lgtm

**Comment by stoksc** [comment]
@hamidzr should we let this sit a couple days incase we have any last minute changes?

**Comment by hamidzr** [comment]
we would have more changes coming but then we just use the update target to update the baseline and that way we get more chances to practice that as well.

**Comment by hamidzr** [comment]
@stoksc does that sg?

**Comment by stoksc** [comment]
sgtm @hamidzr

**Pull request merged**
