### PR TITLE
chore: update linter and templates for squash-and-merge compatibility

### PR DESCRIPTION
**Pull request by justin-determined-ai**
## Description

[this space intentionally left blank]

## Test Plan

Using this PR as a test to see what breaks!

## Commentary (optional)

Went with comments in Markdown so folks don't have to delete the instructions for every PR. Also, yes I broke my own rules by not including a Jira ticket...

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by justin-determined-ai** [comment]
Okay, as it turns out, the linter is going to check each commit (duh). I think that's okay for now, lemme fix this branch to pass though...

**Comment by brain-good** [comment]
Easy to solve! Delete the linter ;)

**Comment by brain-good** [comment]
we can use this to maintain linting on the PR titles: https://github.com/zeke/semantic-pull-requests

**Comment by dzhu** [comment]
With a small GitHub Actions config, we can even use our current linter (which has some checks that that appears not to) and also do our own checks on the body (though nothing along those lines is currently implemented): [dzhu@`check-prs`](https://github.com/dzhu/determined/commit/check-prs).

**Comment by brain-good** [comment]
I would rather not build this ourselves here @dzhu, we can look into contributing to the project since it is open source if we think there are checks in there that are important

**Comment by justin-determined-ai** [comment]
Thanks for the suggestions Danny and Brian! Given that we don't have our own checks on the body just yet, let's hold off on maintaining that code path for the moment.

**Pull request merged**
