### PR TITLE
chore: Recommend git clone --recursive for submodules

### PR DESCRIPTION
**Pull request by mapmeld**
## Description

Update our docs where we `git clone` to include the new submodules with `git clone --recursive`

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by hamidzr** [comment]
thanks for updating the docs. don't we want this one instead? `--recursive` doesn't show up in `git clone --help`

```
--recurse-submodules[=<pathspec>]
             After the clone is created, initialize and clone
             submodules within based on the provided pathspec. If no
             pathspec is provided, all submodules are initialized
             and cloned. This option can be given multiple times for
             pathspecs consisting of multiple entries. The resulting
             clone has submodule.active set to the provided
             pathspec, or "." (meaning all submodules) if no
             pathspec is provided.

             Submodules are initialized and cloned using their
             default settings. This is equivalent to running git
             submodule update --init --recursive <pathspec>
             immediately after the clone is finished. This option is
             ignored if the cloned repository does not have a
             worktree/checkout (i.e. if any of --no-checkout/-n,
             --bare, or --mirror is given)

```

**Review by hamidzr — COMMENTED** [review]
thanks for updating the docs. what does --recursive do? we might want this one  instead `--recursive` doesn't show up in `git clone --help`

```
--recurse-submodules[=<pathspec>]
             After the clone is created, initialize and clone
             submodules within based on the provided pathspec. If no
             pathspec is provided, all submodules are initialized
             and cloned. This option can be given multiple times for
             pathspecs consisting of multiple entries. The resulting
             clone has submodule.active set to the provided
             pathspec, or "." (meaning all submodules) if no
             pathspec is provided.

             Submodules are initialized and cloned using their
             default settings. This is equivalent to running git
             submodule update --init --recursive <pathspec>
             immediately after the clone is finished. This option is
             ignored if the cloned repository does not have a
             worktree/checkout (i.e. if any of --no-checkout/-n,
             --bare, or --mirror is given)

```

**Comment by hamidzr** [comment]
I'm considering whether we want to add a `git submodule update` to our `get-deps` step.

**Comment by mapmeld** [comment]
oh I had used `--recursive` before, it looks like it's only an alias https://explainshell.com/explain?cmd=git+clone+--recursive

I'll update this PR and then if you think it should combine in the `git submodule update` I can look it up

**Comment by hamidzr** [comment]
thanks.
re 
> I'll update this PR and then if you think it should combine in the git submodule update I can look it up

i'll try this in saas and see how that works out first.

**Review by hamidzr — APPROVED** [review]

**Pull request merged**
