### PR TITLE
fix: fix shim for stateless searchers (grid, single, etc..)

### PR DESCRIPTION
**Pull request by stoksc**
## Description
Let's try this again..

## Test Plan
- [x] run adaptive, pbt, etc on 0.14.1, upgrade to 0.14.3dev so shim occurs and validate experiments complete as expected.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by rb-determined-ai** [comment]
Can we include the name of the searcher in the searcher state?  Or at least pass it in from the experiment actor or something?   Seems like this information would eliminate the bugs we have hit.

**Comment by shiyuann** [comment]
Since you are working on this, maybe also include the shim for "cached_checkpoint".

**Comment by stoksc** [comment]
@rb-determined-ai I don't want to add that state on the grounds that to shim it you need the experiment config since single, random and grid are stateless and can't be differentiated from their state alone and so to figure it out you need the experiment config and I don't want to tie their states together like that.. if I could add it without giving shims an experiment config (that _wouldn't_ be the version from which they are shimming) I'd be onboard. I get it would be useful to have.. I'm just not exactly sure how to get it without make things worse lol.

also I think the answer here is to probably make the next eng that writes a shim right a test for it.

**Review by rb-determined-ai — APPROVED** [review]
Looks good.  Hopefully this will be much easier next time

**Pull request merged**
