### PR TITLE
chore: add back the symlink to webui/react

### PR DESCRIPTION
**Pull request by hamidzr**
this was unintentionally removed in
85f72ede774d5974a48cfffa8fe8477d2abf61df

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.
- [ ] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by gt2345 — APPROVED** [review]

**Comment by hamidzr** [comment]
@trentwatt https://github.com/determined-ai/determined/pull/4635/commits/ed7de37ba0c00a737f820bf042016e4a30787712 seems to do the job for the duplicate files concern in IDEs

**Comment by trentwatt** [comment]
> @trentwatt [ed7de37](https://github.com/determined-ai/determined/commit/ed7de37ba0c00a737f820bf042016e4a30787712) seems to do the job for the duplicate files concern in IDEs

idk, i still feel like the symlink is more messy/annoying than useful:

image

image

**Comment by trentwatt** [comment]
to me the main advantage of `mv webui/react web` is that the directory structure of the repo is simpler and easier for new people to understand, and this is kinda going in the opposite direction

**Comment by hamidzr** [comment]
closing for now until we pick this back up later

**Pull request closed without merging**
