### PR TITLE
feat: catch if DistributeConfig is set for Estimator [DET-3887]

### PR DESCRIPTION
**Pull request by armandmcqueen**
## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Review by aaron276h — COMMENTED** [review]
Looks good. One questions I have is what coverage are we getting from these newly added tests?

**Comment by armandmcqueen** [comment]
@aaron276h What exactly do you mean by coverage here? The tests exist to confirm that this feature was implemented correctly - setting MirroredStrategy leads to error and having an empty DistributeConfig should not have an impact. Most of the value of these tests were in confirming that this PR was implemented correctly - at this point they don't have a ton of value and if we want to avoid accumulating tests, we can remove them.

**Comment by aaron276h** [comment]
@armandmcqueen Yeah i think it makes sense to remove it since `test_estimator_fails_when_train_distribute_is_set` should fail whether or not we have the fix right? and `test_estimator_succeeds_when_train_distribute_is_empty` is mostly a duplicate of other test cases. If we want to keep them, we should move the model_def to `e2e_tests/tests/fixtures`.

**Comment by armandmcqueen** [comment]
Removed tests

**Review by aaron276h — APPROVED** [review]

**Pull request merged**
