### PR TITLE
chore: check and format examples

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

add `black` and `isort` checks to python examples

## Commentary (optional)

follow up on 
https://determined-ai.slack.com/archives/C02T7L0593K/p1669237099714399 and #5392 

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by garrett361** [comment]
Why no `isort`, also? I didn't think `isort` would lead to any issues that would need manual intervention, but maybe that's wrong.

**Review by garrett361 — APPROVED** [review]
Looks good to me, apart from maybe my comment about also including `isort` unless we expect that to lead to specific headaches?

**Comment by hamidzr** [comment]
> Why no `isort`, also? I didn't think `isort` would lead to any issues that would need manual intervention, but maybe that's wrong.

There was some manual intervention needed as they were not totally agreeing and I  didn't want to really look into why. [This change](https://github.com/determined-ai/determined/pull/5587/commits/c4ad5329dc55aa76770222f7820c26e331bfa26b) lets them agree.

**Comment by hamidzr** [comment]
something's up with CI 
image

**Comment by keita-determined** [comment]
@hamidzr CI issue is fixed.

**Pull request merged**
