### PR TITLE
chore: quiet grpc log levels down [DET-4224]

### PR DESCRIPTION
**Pull request by rb-determined-ai**
Fun fact: this jira ticket number is a palindrome.

### CODE REVIEW

**Review by stoksc — APPROVED** [review]
lgtm

**Review by hamidzr — COMMENTED** [review]
overall looks good to me. I have a question on what level do we want surface errors in API calls for example:

codes.NotFound, OutOfRange, and Unknown, do we want these to show up as either warn or error or lower?

**Comment by hamidzr** [comment]
is the idea that errors that are caused by the user and foreseen shouldn't show up as error or warn level logs?

**Comment by rb-determined-ai** [comment]
> is the idea that errors that are caused by the user and are expected shouldn't show up as error or warn level logs

Yes, exactly.  The observable behavior in case of e.g. a 404 should be a 404 in the browser, not an error line in the master logs.  Errors in the master log should require attention from the sysadmin.

**Review by hamidzr — APPROVED** [review]

**Pull request merged**
