### PR TITLE
docs: root user usage for HPC

### PR DESCRIPTION
**Pull request by phillip-gaisford**
## Description
Elaboration on usage of the root user  for
Slurm/PBS clusters

Looks like: 
Screen Shot 2023-02-14 at 2 14 33 PM

and:
Screen Shot 2023-02-14 at 2 13 36 PM

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by jerryharrow** [comment]
That is good, but can you also add a similar note in step #7 of https://hpe-mlde.determined.ai/latest/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.html

image

It is unlikely for a customer to find that reference and allowing users to run as root is likely not something most HPC administrators want to do -- so important that it is clear.

**Comment by rcorujo** [comment]
In your Description, there is a paragraph referencing "/usr/local/determined/etc" as the place to find master.yaml.  

The "Configure and Verify Determined Master on HPC Cluster" section says:

```
 For RPM-based installations, the configuration file is typically the /etc/determined/master.yaml file.
```

I'm not sure why we're mentioning "/usr/local/determined/etc"?  On our clusters, it's always been "/etc/determined/master.yaml".

**Comment by jerryharrow** [comment]
> I'm not sure why we're mentioning "/usr/local/determined/etc"? 

This is not Slurm/PBS-specific doc, it is the general doc for cluster setup (https://hpe-mlde.determined.ai/latest/cluster-setup-guide/users.html?highlight=root#run-tasks-as-specific-agent-users).

I presume the path name comes when using the determined-master in a docker container?

**Comment by jerryharrow** [comment]
We also probably shouldn't be using the wording `For RPM-based installations,` more like `For Linux package-based installations...`?

**Comment by rcorujo** [comment]
> We also probably shouldn't be using the wording `For RPM-based installations,` more like `For Linux package-based installations...`?

Yes, that's correct.

**Comment by phillip-gaisford** [comment]
> That is good, but can you also add a similar note in step #7 of https://hpe-mlde.determined.ai/latest/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.html

Do we want to that, even though the link rendered as 'Run Tasks as Specific Agent Users' does point back to the changed text?

**Review by jerryharrow — APPROVED** [review]

**Pull request merged**
