### PR TITLE
fix: hide description placeholder when archived

### PR DESCRIPTION
**Pull request by keita-determined**
## Description
[DET-7556]

## Test Plan
- Check description placeholder is blank when the item is archived.
- Also check description placeholder is visible when the item is NOT archived.
You can find these placeholders in `Uncategorized` tab, experience in `Workspace` tab and so on...

## Commentary (optional)
I assumed when disable variable is passed to `InlineEditor` component, all placeholder should be blank.
Is it right? @trentwatt 

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-7556]: https://determinedai.atlassian.net/browse/DET-7556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by trentwatt** [comment]
> I assumed when disable variable is passed to InlineEditor component, all placeholder should be blank.
Is it right? @trentwatt

That didn't occur to me but I think it is a pretty good assumption. Thoughts @hkang1 ?

**Comment by hkang1** [comment]
> > I assumed when disable variable is passed to InlineEditor component, all placeholder should be blank.
> > Is it right? @trentwatt
> 
> That didn't occur to me but I think it is a pretty good assumption. Thoughts @hkang1 ?

hmmm it's probably ok. I don't have a good solution but showing a blank (because the border only shows when it's activated?) is a bit misleading too. Wonder if there is a better way to show an empty but disabled state for the inline editor. @alexjdetermined ? :D

**Comment by alexjdetermined** [comment]
> > > I assumed when disable variable is passed to InlineEditor component, all placeholder should be blank.
> > > Is it right? @trentwatt
> > 
> > 
> > That didn't occur to me but I think it is a pretty good assumption. Thoughts @hkang1 ?
> 
> hmmm it's probably ok. I don't have a good solution but showing a blank (because the border only shows when it's activated?) is a bit misleading too. Wonder if there is a better way to show an empty but disabled state for the inline editor. @alexjdetermined ? :D

Can we replace the placeholder when in achived state and null to "No description" from "Add description"?

**Comment by keita-determined** [comment]
> > > > I assumed when disable variable is passed to InlineEditor component, all placeholder should be blank.
> > > > Is it right? @trentwatt
> > > 
> > > 
> > > That didn't occur to me but I think it is a pretty good assumption. Thoughts @hkang1 ?
> > 
> > 
> > hmmm it's probably ok. I don't have a good solution but showing a blank (because the border only shows when it's activated?) is a bit misleading too. Wonder if there is a better way to show an empty but disabled state for the inline editor. @alexjdetermined ? :D
> 
> Can we replace the placeholder when in achived state and null to "No description" from "Add description"?

image
Something like this?

**Comment by alexjdetermined** [comment]
> > > > > I assumed when disable variable is passed to InlineEditor component, all placeholder should be blank.
> > > > > Is it right? @trentwatt
> > > > 
> > > > 
> > > > That didn't occur to me but I think it is a pretty good assumption. Thoughts @hkang1 ?
> > > 
> > > 
> > > hmmm it's probably ok. I don't have a good solution but showing a blank (because the border only shows when it's activated?) is a bit misleading too. Wonder if there is a better way to show an empty but disabled state for the inline editor. @alexjdetermined ? :D
> > 
> > 
> > Can we replace the placeholder when in achived state and null to "No description" from "Add description"?
> 
> image
> 
> Something like this?

Hmm yeah, doesnt work as well there. Maybe using "Archived" is a clearer empth description placeholder message. So users can better understand why they cant edit it. I think its better than "Blank" because users might not immedietly know when they cant edit the description in a blank world.

**Comment by keita-determined** [comment]
> > > > > > I assumed when disable variable is passed to InlineEditor component, all placeholder should be blank.
> > > > > > Is it right? @trentwatt
> > > > > 
> > > > > 
> > > > > That didn't occur to me but I think it is a pretty good assumption. Thoughts @hkang1 ?
> > > > 
> > > > 
> > > > hmmm it's probably ok. I don't have a good solution but showing a blank (because the border only shows when it's activated?) is a bit misleading too. Wonder if there is a better way to show an empty but disabled state for the inline editor. @alexjdetermined ? :D
> > > 
> > > 
> > > Can we replace the placeholder when in achived state and null to "No description" from "Add description"?
> > 
> > 
> > image
> > Something like this?
> 
> Hmm yeah, doesnt work as well there. Maybe using "Archived" is a clearer empth description placeholder message. So users can better understand why they cant edit it. I think its better than "Blank" because users might not immedietly know when they cant edit the description in a blank world.

Probably adding a tooltip on a disabled description would be helpful?

**Comment by trentwatt** [comment]
> Maybe using "Archived" is a clearer empty description placeholder message.

+1

**Comment by keita-determined** [comment]
image
Fixed!

**Review by trentwatt — APPROVED** [review]
Yeah this duplicates things a bit, but better I think than encoding the assumption that disabled is always equivalent to archived at the component level.

**Pull request merged**
