### PR TITLE
chore: remove is_chief calculation for non-horovod distributed training [DET-3338]

### PR DESCRIPTION
**Pull request by shiyuann**
## Description

Remove is_chief calculation for non-horovod distributed training.

## Test Plan

Use CI to run our test suite.

## Commentary (optional)

Nothing here.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by shiyuann** [comment]
@aaron276h because to check is_chief when not using horovod? I am copying the code from https://github.com/determined-ai/determined/blob/ee4ba43dfbbaf4bc2c1041389e4a7cd6219001df/harness/determined/_trial_controller.py#L266

**Comment by aaron276h** [comment]
@shiyuann `self.context.distributed.get_rank()` works correctly in both single and multi-slot trials. The code you are referencing is from before the context object was introduced and hasn't been updated. 

We should try and avoid providing multiple ways to do the same thing in the context object as that may confuse users. If there is a good reason for adding this to the context object it should have a more descriptive name, e.g., `is_chief_rank()`.

**Comment by shiyuann** [comment]
@aaron276h Discussed offline. since we don't have non-Horovod d-train built in the system, the code path of calculating `is_chief` without using Horovod is unused. But to keep the code always right, we decided to keep the logic and renamed it to `_is_chief()` in the context object so that the code follows the previous way of execution when we refactor the Pytorch trial for introducing the new API.

**Comment by rb-determined-ai** [comment]
@shiyuann and I also discussed off line.  In general, the TrialContext is there to provide APIs to the user, not to provide things that we ourselves would call.  So in general, I would prefer not to be adding private methods to any TrialContext object.  In this case, that could look like us just pre-calculating the return values of `DistributedContext.get_rank()` and `DistributedContext.get_size()`, rather than passing the HorovodContext and EnvContext and calculating it as part of the TrialContext.

In this case, I think having `_is_chief()` is not a very big deal, and I'm fine with how it is written up here.

However, I would vote we just remove the non-horovod rank check from our system, since we don't have any roadmap to supporting it at all.  That would also mean that the TrainContext does not need a RendezvousInfo argument right now.  @aaron276h, what are your thoughts there?

**Comment by shiyuann** [comment]
@rb-determined-ai I updated the code per discussion.

**Comment by aaron276h** [comment]
Yeah looks good. In the future, we should initialize this information based on the context object, but it's ok to do this outside this PR.

**Pull request merged**
