### PR TITLE
test: fix resnet50 CI test

### PR DESCRIPTION
**Pull request by aaron276h**

### CODE REVIEW

**Comment by brain-good** [comment]
can you describe how this was tested?

**Comment by aaron276h** [comment]
@brain-good haven't tested. The fix is very obvious based on the error in the nightly tests.

**Comment by brain-good** [comment]
> The fix is very obvious based on the error in the nightly tests.

Do you think it might be worth running a test to verify that there are no other errors that we may run into later in the experiment?

**Comment by aaron276h** [comment]
@brain-good wasn't planning on fixing errors in the model definition but it's our lucky day as there are none. Ran a local experiment to confirm.

**Pull request merged**
