### PR TITLE
feat: multiple metric chart [DET-3927]

### PR DESCRIPTION
**Pull request by hkang1**
## Description

Add support for displaying multiple metric charts on trial detail.

Screen Shot 2020-09-08 at 9 22 30 PM

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by hamidzr** [comment]
could you please rebase to get the dependency you mention in here so the diff becomes accurate?

**Review by hamidzr — COMMENTED** [review]
It's working great. There is one plot feature that we could either embrace more or just call out: the legends allow the user to double click each dataset that is plotted to only display that one and it partly overlaps with this feature but I assume it's less customizable compared to our own picker. could the combination become confusing to people?

- Do we want to persist the selected metrics like we do for the table?

**Comment by hamidzr** [comment]
changing the scale to logarithmic we seem to lose the plotted data but I after you adjust the axis you can see the line. is that a missing data range recalculation?

**Comment by hkang1** [comment]
@hamidzr moved log scale fix to separate [PR 1295](https://github.com/determined-ai/determined/pull/1295)

**Comment by hkang1** [comment]
> * Do we want to persist the selected metrics like we do for the table?

Added a commit to save chart metrics to user preference. (Separate from table metrics picker)

**Review by hamidzr — APPROVED** [review]
LGTM :heavy_check_mark:  this is gonna be a great feature to have

The only remaining comment for me to check is this: cc @vishnu2kmohan 
> There is one plot feature that we could either embrace more or just call out: the legends allow the user to double click each dataset that is plotted to only display that one and it partly overlaps with this feature but I assume it's less customizable compared to our own picker. could the combination become confusing to people?

**Comment by vishnu2kmohan** [comment]
> LGTM  this is gonna be a great feature to have

:heavy_plus_sign:  Definitely a big fan of the this feature; it's been far too long a wait, but I too am glad that it's **finally** here!

> There is one plot feature that we could either embrace more or just call out: the legends allow the user to double click each dataset that is plotted to only display that one and it partly overlaps with this feature but I assume it's less customizable compared to our own picker. could the combination become confusing to people?

Double-Clicking a specific series on the chart legend to only display that is a nice feature to include, and I don't feel it'll be confusing, provided there's an easy way to reset it back to the set of series that was (selected/filtered and) displayed previously.

_Not sure how easily I would have discovered it myself unless you told me that it was possible._

**Comment by hkang1** [comment]
> ow the user to double click each dataset that is plotted to only display that one and it partly overlaps with this feature but I assume it's less customizable compared to our own picker. could the combination become confusing to people?

great catch! was pretty easy to disable the legend click events

**Pull request merged**
