### PR TITLE
style: Update antd to v5

### PR DESCRIPTION
**Pull request by ashtonG**
## Description

This updates antd to v5.

current status:

- [x] Remove build dependencies stemming from the previous version's dependency on momentjs and less.

- [x] Reimplement dark/light style switching

- [x] Categorize and possibly fix style breakages stemming from update

## Test Plan

Major workflows should not be impacted

## Commentary (optional)

The biggest change from antd v4 to v5 is the change in how styles are applied. While v4 used less format stylesheets, v5 switches to a css-in-js approach. While this makes modifying the styles easier and more straightforward, it means a lot of the previous work we did in overriding the styles are now incompatible because the new rules have higher specificity. We should identify and fix particularly problematic changes to the styles as a result of this change.

## Checklist

- [x] Changes have been manually QA'd

## Ticket

WEB-672

### CODE REVIEW

**Comment by ashtonG** [comment]
change: "ghost" buttons (i.e. the launch jupyterlab button) have darker text and hover colors

old: 
image
image


new:
image
image

**Comment by ashtonG** [comment]
change: border radius on inputs have been increased

old:
image
new:
image

**Comment by ashtonG** [comment]
change: border radius on tooltips have been increased

old:
image
new:
image

**Comment by ashtonG** [comment]
breakage: padding removal on hyperparameter search modal is no longer working properly

old:
image
new:
image

**Comment by ashtonG** [comment]
change: background of form controls are now black/white (depending on theme) instead of transparent

old:
image
new:
image

**Comment by ashtonG** [comment]
Change: Font weight and icon colors have been changed on table headers

old:
image

new:
image

**Comment by ClaireNeveu** [comment]
Can you return the border radiuses to their previous state? Other than that the design changes look good.

**Comment by ClaireNeveu** [comment]
Oh actually, just noticed this but it looks like the button and input backgrounds changed and no longer match our dark mode backgrounds? That definitely needs to be fixed.

**Review by keita-determined — CHANGES_REQUESTED** [review]
Thanks for working on it. I found some design issues. 


- [x] done
- [ ] confirmed

<details>
<summary>Notification text color doesnt look right </summary>


https://user-images.githubusercontent.com/109113616/214648887-56d07361-9b70-40d0-a478-8728e2560fef.mov
</details>

---

- [x] done
- [ ] confirmed

<details>
<summary>modal color should match the theme</summary>


https://user-images.githubusercontent.com/109113616/214649224-174031dc-43cb-4663-9e51-61db11b6c450.mov
</details>

---

- [x] done
- [ ] confirmed

<details>
<summary>Button effect isnt centered</summary>

image
</details>

---

- [ ] done
- [ ] confirmed

<details>
<summary>text is not aligned</summary>


image
</details>

---

- [ ] done
- [ ] confirmed

<details>
<summary>nit: button color shouldnt be blue</summary>


https://user-images.githubusercontent.com/109113616/214650844-0eec2d6b-158a-475a-9a49-43c158f11904.mov
</details>

---

- [ ] done
- [ ] confirmed

<details>
<summary>nit: table row color is blue when its hovered</summary>


image
</details>

**Comment by ashtonG** [comment]
@keita-determined can you verify that these were introduced by the antd v5 upgrade?

**Comment by keita-determined** [comment]
> @keita-determined can you verify that these were introduced by the antd v5 upgrade?

yep, these were introduced by the upgrade
This website is helpful to check the current design [here](http://latest-master.determined.ai:8080/)

**Comment by ashtonG** [comment]
@keita-determined I was able to reproduce the color scheme not persisting between reloads on latest master. Could you please verify the others with screenshots?

**Comment by keita-determined** [comment]
> @keita-determined I was able to reproduce the color scheme not persisting between reloads on latest master. Could you please verify the others with screenshots?

my bad, i could repro the color theme issue. sometimes it's working, sometimes not. 
Rest of them are introduced from antd v5

**Comment by julian-determined-ai** [comment]
Wanted to note I see an input color difference in light mode on the login screen.

Screen Shot 2023-01-25 at 2 17 57 PM

**Comment by julian-determined-ai** [comment]
Also the button color on the sign in changes on `hover`
Screen Shot 2023-01-25 at 2 19 05 PM

**Review by julian-determined-ai — COMMENTED** [review]
Wanted to note that I have not found any additional UI issues outside of what has already been identified. Once the issues are fixed then LGTM!

**Review by ClaireNeveu — APPROVED** [review]
Looks great!

**Pull request merged**
