### PR TITLE
chore: change the output format args for master config cli

### PR DESCRIPTION
**Pull request by hamidzr**
## Description
match the output format style of other det cli commands

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ioga — APPROVED** [review]

**Comment by hamidzr** [comment]
update: i'm waiting on me to gather more evidence on what's more common and thus probably more intuitive to users

**Comment by ioga** [comment]
is this about `-o json` vs `--json`?

**Comment by hamidzr** [comment]
> is this about `-o json` vs `--json`?

or some other format yes. I think @vishnu2kmohan  had some thoughts too

**Comment by ioga** [comment]
just do both 😉

**Comment by vishnu2kmohan** [comment]
I agree with @ioga but I have to credit @rb-determined-ai for his exhaustive study:
```
To -o, or not to -o?

1          | gcc test.c -o test
    3      | go test -json
1          | go test -o file
    3      | ip -json addr  # Wow, TIL.
    3      | yq -y/--yaml-output
  2   4    | kubectl get pods --output json
        5  | docker ps --format FORMAT_STRING
        5  | git branch --format=FORMAT_STRING
    3      | git * --porcelain
    3      | packer -machine-readable
1          | terraform plan -out=PLANFILE
           | terraform show -json
      4   6| vault read -format=(table|json|yaml|pretty)
    3      | nomad eval status -json
           | nomad eval status -t FORMAT_STRING
    3      | vagrant --machine-readable


Cases analyzed:

1 = `-o`/`--output` is a file
2 = `-o`/`--output` is not a file
3 = output format is a flag (no arg)
4 = output format is an option
5 = --format is for a format string
6 = --format is for anything else


Conclusions:

Is the word "output" just for files?
 - Kinda, 3 to 1

Is a flag for setting format more common than an option?
 - Yes, 7 to 2.  Notably, none of the 7 supported more than two formats.

Is --format just for format strings?
 - Not clear, 2 to 1.
 ```

**Comment by vishnu2kmohan** [comment]
@rb-determined-ai's recommendation after :point_up::
> After this, I'm inclined to only support a default format and have a --json flag, because that is much more wide-spread than I had realized.

**Comment by hamidzr** [comment]
we use --output elsewhere in our python code. I'll stick with just switching to --json, --yaml if there is explicit ask for the other one and land this as is.

**Pull request merged**
