### PR TITLE
build: Add basic visual regression testing for designkit

### PR DESCRIPTION
**Pull request by ashtonG**
## Description

This adds basic visual regression testing to the design kit. We add a new dev-only (as in not present in production builds) route that shows the design kit, take screenshots of every top-level section, and compare it with the same in master. We then take the results and put together a flat html file to show the results.

## Test Plan

will be tested via ci.

## Commentary (optional)

We may need to break out the standalone designkit stuff so the ci can run properly.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

WEB-1043

### CODE REVIEW

**Comment by ashtonG** [comment]
Hello! DesignKit diffs are available for you to view [here](https://output.circle-artifacts.com/output/job/fbf71a84-57d2-44bc-877a-0c77c1eb3aef/artifacts/0/webui/react/screenshot-summary.html)

**Comment by ClaireNeveu** [comment]
Can we always just show the components with differences? Also, will this only comment if it detects a change?

**Comment by ClaireNeveu** [comment]
Also we're gonna have to refactor the chart section so it has a fixed data set by default.

**Comment by ashtonG** [comment]
Working on just showing changed elements. The job will comment on every run regardless if there were diffs detected, but I'll change that to indicate whether diffs were detected.

**Comment by ClaireNeveu** [comment]
Is it not possible to only comment when there are changes?

**Comment by ashtonG** [comment]
going to close this pr and reopen another one now that the work on isolating designkit has been pulled out and merged successfully.

**Pull request closed without merging**
