### PR TITLE
feat: add per nic net throughput to the profiler

### PR DESCRIPTION
**Pull request by stoksc**
## Description
This change allow users to collect per NIC net throughput metrics through the system metrics profiler.

## Test Plan
- [x] run a job with `profiling.per_nic_net_throughput` both enabled and disable, ensure both work as expected.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by trentwatt** [comment]
what is the unit? for webui

**Comment by stoksc** [comment]
> what is the unit? for webui

same as the other net throughputs. good thought.

**Comment by stoksc** [comment]
we really need the backend to just include a unit and let the web read it from the labels for the series

**Comment by trentwatt** [comment]
we can do that

**Comment by stoksc** [comment]
ok, I'll let mlsys take it from here if that is ok.

**Pull request closed without merging**
