### PR TITLE
feat: Add custom tags to AWSClusterConfig

### PR DESCRIPTION
**Pull request by sean-adler**
## Description

* adds optional `custom_tags` list to `AWSClusterConfig`

## Test Plan

* added check to an existing unit test

## Commentary (optional)

* This is useful for environments with required EC2 tags, i.e. the existence of certain tags is enforced and must be applied to all EC2 instances.

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Review by shiyuann — COMMENTED** [review]
This looks pretty good! Thank you for your contribution. It seems that you'll need to set an email and attach your emails to the commits to pass the checks if you don't mind bothering to do so! @sean-adler

**Comment by sean-adler** [comment]
Thank you @shiyuann. Can you please rerun CI?

**Comment by shiyuann** [comment]
Hi @sean-adler , the CI automatically reruns when you force-push into your own branch. I tried to close and re-open the PR and it made the CI re-run. 

It seems this PR didn't pass the lint check. Before you force-push, could you also run `make -C master fmt check test` in the determined directory so that you would know how to pass the checks and tests?

BTW, we need all the contributors to sign a [Contributor License Agreement](https://determined.ai/cla/) and submit it via email to `cla@determined.ai` you would like to be one.

Thank you!

**Comment by sean-adler** [comment]
Thanks @shiyuann, I think I fixed the linter errors and CLA now passes.

**Comment by shiyuann** [comment]
@sean-adler the e2e tests somehow don't pass. You probably don't have permission to see the logs. I am looking into it.

**Review by shiyuann — APPROVED** [review]

**Pull request merged**
