### PR TITLE
chore: Pass in the allocation ID to releasedResources()

### PR DESCRIPTION
**Pull request by CanmingCobble**
## Description

DET-9466 - https://hpe-aiatscale.atlassian.net/browse/DET-9466

In https://github.com/determined-ai/determined-ee/pull/822  Bradley requested that we pass in the allocationID to the “releasedResources()” function in “dispatcher_resource_manager.go”, rather than get it inside the function from “m.reqList.Allocation()”.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Review by jerryharrow — COMMENTED** [review]
lgtm -- let's let another review also weigh in (and the tests to finish).

**Comment by rcorujo** [comment]
I'm not seeing where we're passing the allocationID to the "resourcesReleased()" function in "dispatcher_resource_manager.go"?

Also, what kind of testing was done?

**Comment by CanmingCobble** [comment]
> Oh, never mind. The passing of the allocationID to "resourcesReleased()" would be done in the separate determined-ee repository.

Yes.

**Comment by CanmingCobble** [comment]
Jerry please merge this for me. I don't have write access.

**Pull request merged**
