### PR TITLE
chore: upgrade to support panoptic segmentation for coco [DET-6945]

### PR DESCRIPTION
**Pull request by liamcli**
## Description
Add support for coco panoptic segmentation dataset and associated mmdetection configs.  Includes following changes:
- upgrade mmcv and mmdet versions
- change file client substitution to include panoptic segmentation loader
- add config for panoptic fpn as an example

## Test Plan
e2e mmdetection tests completed successfully.

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

### CODE REVIEW

**Comment by coreystatendet** [comment]
question: Should we add a panoptic fan test to `e2e_tests/tests/model_hub/test_mmdetection.py` since this is advertising panoptic fun support?

**Review by gh-determined-ai — CHANGES_REQUESTED** [review]
This release note needs to be more descriptive (see Procedure, step 2, for some ideas): https://github.com/determined-ai/determined/tree/master/docs/release-notes
If there's a Jira issue associated with this, it might provide some words for why this change was needed and why it's useful.

**Comment by liamcli** [comment]
> question: Should we add a panoptic fpn test to `e2e_tests/tests/model_hub/test_mmdetection.py` since this is advertising panoptic fpn support?

It's going to take more effort to get panoptic to work with fake data so i'm leaving out of e2e tests for now.

**Review by gh-determined-ai — APPROVED** [review]

**Review by gh-determined-ai — APPROVED** [review]
Release Note:
- Change "Users can now use ..." to "You can now use ..."
- Spell out 'config/configs' where it makes sense; (configuration/s)

**Pull request merged**
