### PR TITLE
fix: remove python 3.10 union-type syntax

### PR DESCRIPTION
**Pull request by rb-determined-ai**
## Description

This removes a [python 3.10-specific syntax](https://peps.python.org/pep-0604/) from the codebase.

I can't figure out how the code in question runs at all.  It must be some sort of runtime optimization that isn't considering types at all, because a simple command like:
```
python -c 'a: int | str = 1'
```
throws an error:
```
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

I was occasionally (but not consistently) seeing mypy errors in make check.

### CODE REVIEW

**Comment by mapmeld** [comment]
I don't have an explanation for that either.
I was trying to add a suggestion ( `Union[A, B]` instead of `Union[A | B]` ) but it was actually a commit, hope that makes sense as the better backwards-compatible way to do it

**Comment by rb-determined-ai** [comment]
I mean, normally I would raise an eyebrow at somebody committing to my PR, but this is fine.  Silly error on my part.

**Review by mapmeld — APPROVED** [review]
Approved with a tiny change. Sorry I could have done the requested change part better.

**Comment by rb-determined-ai** [comment]
no need to be sorry, not a problem at all here

**Pull request merged**
