### PR TITLE
fix: remove limit of length 4 for task id

### PR DESCRIPTION
**Pull request by hkang1**
## Description

The limit should only be applied to task ids that come in the form of UUID and not experiment ids.

Example of experiment id of 10000 truncated to 1000.
image (4)

## Test Plan

- [ ] check that Experiment task cards don't truncate ids
- [ ] check that Task task cards truncate ids to 4 chars

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hamidzr** [comment]
https://deploy-preview-4304--determined-ui.netlify.app/ is down 🤔

**Review by julian-determined-ai — APPROVED** [review]
Functionality looks great!

**Comment by hkang1** [comment]
> https://deploy-preview-4304--determined-ui.netlify.app/ is down 🤔

is our netlify backed with the same cluster as LM?

**Comment by hamidzr** [comment]
> > https://deploy-preview-4304--determined-ui.netlify.app/ is down 🤔
> 
> is our netlify backed with the same cluster as LM?

no but it looked like the netlify host serving the ui assets was down and not the backing det cluster.

**Pull request merged**
