### PR TITLE
fix: fix relative asset paths for swagger-ui [DET-3437]

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

Screen Capture_select-area_20200623130400

## Test Plan

- load the swagger UI from both /swagger-ui and /swagger-ui/

## Commentary (optional)

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Comment by ybt195** [comment]
@justin-determined-ai labstack echo has support for that. Maybe use (https://echo.labstack.com/middleware/static)

**Comment by hamidzr** [comment]
>  Looks great, too bad we have to do this! I know some routing frameworks do like an "optional end slash" operator or something, I assume that ours doesn't have that?

without the / the server properly serves the swagger files just that base path I'm not sure how we can handle it better :thinking:

**Comment by justin-determined-ai** [comment]
My take is that the cost of having this in two places (here and `/docs`) is lower than the cost of adding a new dependency. But I don't feel strongly either way, so I think dealer's choice in this instance.

**Comment by hamidzr** [comment]
looks like we already have that dependency. I'll see if I can just use that

**Comment by hamidzr** [comment]
I added the middleware it does look better and should same of some redirects later on

**Pull request merged**
