### PR TITLE
chore: separate useui store and actions

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

- separate ui store
- introduce a new pattern to update the ui store/state
- remove dependency on the generic store, which is not shared, from shared components

## Test Plan

- [x] flip through some ui pages
- [x] look at the diff to make sure dispatch calls are replaced w/ correct actions.call
- [x] check both mods: dark and light
- [x] storybook

we could write unit tests..

## Checklist
- [x] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hamidzr** [comment]
https://circleci.com/gh/determined-ai/determined/989775 is expected. if we could set it up as an optional test it'd fit the current workflow better. (I added more details to about this https://hpe-my.sharepoint.com/:w:/p/hamid_zare/ERhKXokZB6ZHo6hXMilZ1J4B3fDR3donko-2Utbj9r-leg?e=9n4owz)

**Comment by hamidzr** [comment]
https://app.circleci.com/pipelines/github/determined-ai/determined/29150/workflows/763e230a-3e0d-4c73-9a06-a2cb1a99ee3b/jobs/989805 failed for but seems unrelated cc @determined-ai/infrastructure

**Comment by hamidzr** [comment]
@ClaireNeveu  new changes are separate commits after the squashed one.

**Comment by dannysauer** [comment]
> https://app.circleci.com/pipelines/github/determined-ai/determined/29150/workflows/763e230a-3e0d-4c73-9a06-a2cb1a99ee3b/jobs/989805 failed for but seems unrelated cc @determined-ai/infrastructure

Failed downloading a Go module. Might be something @determined-ai/backend is more helpful with if retrying continues to fail.

**Review by ClaireNeveu — APPROVED** [review]

**Comment by ClaireNeveu** [comment]
This looks good but you are missing one item from your test plan which is switching between dark and light mode

**Comment by dzhu** [comment]
I see `signal: killed`, so maybe OOM?

**Comment by hamidzr** [comment]
checked [integration](https://github.com/determined-ai/saas/pull/441) with Samuel

**Pull request merged**
