### PR TITLE
Simplify Python linting

### PR DESCRIPTION
**Pull request by brain-good**

### CODE REVIEW

**Comment by dzhu** [comment]
I'm not a fan of duplicating every config file five times; can we just make them symlinks to one copy? (Doesn't really work on Windows, but I think that ship has sailed...)

Also, can we get some justification for no longer pinning dependencies? While dealing with pip-tools was occasionally a bit annoying, that seems like a pretty big loss.

**Comment by brain-good** [comment]
> can we just make them symlinks to one copy?

sure! if they drift apart in the future we can always reevaluate

>  Also, can we get some justification for no longer pinning dependencies? While dealing with pip-tools was occasionally a bit annoying, that seems like a pretty big loss.

We actually got rid of it earlier when we split out the Python package into multiple parts, but brought it back after MLFlow introduced a number of conflicting dependencies that needed multiple rounds of dependency resolution from pip-tools to actually determined a satisfiable set of dependencies. Pip-tools does two things, it pins unpinned dependencies and pins the transitive dependencies, but only for our local development environment. Since we are building Python packages not a live service, the pinning of all these dependencies is overkill and leads to a development environment that is not representative of the environment that our Python packages will be installed in (we are and should be striving for Python packages that install into many different environments). Going forward, if we have a dependency that we feel needs to be pinned to a version, then we should pin it. If we have a development dependency we feel needs to be pinned, we should pin that as well.

A majority of our CI has been running without pip-tools generated requirements files to ensure that we are testing our Python wheels in representative settings and it's been stable.

Please lmk if you have any more questions related to this @dzhu

**Comment by ybt195** [comment]
I am more concerned about the symlink approach. They tend to break on a lot (e.g. Docker contexts and bind mounts). I prefer to just copy the files into their respective projects and remove the root ones similar to how we do our go build. This will let us separate out the development process into their respective sub-projects and set specific requirements for each one as needed.

**Comment by brain-good** [comment]
@ybt195 Thanks for bringing up this concern that I hadn't thought of! Think it's best to stick with the approach we had before.

**Comment by dzhu** [comment]
Ah cool, that's good information about the pinning. Makes sense, thanks!

I'm not sure about the issue with symlinking, though. These files are for development only, not being shipped into task containers or anything. In what scenario is somebody taking their local repo, bind mounting one subdirectory (but not the whole repo) into a container, and then running Mypy or Flake8 _in_ the container?

**Comment by ybt195** [comment]
One example of us using docker is our CI. We use docker to run our linters/tests in parts of CI steps.

**Comment by dzhu** [comment]
Yes, I know Docker is involved sometimes, but there are no issues, as far as I know, unless one of the subdirectories is present _but not_ the whole repo. Presumably we don't have any such situations now or things wouldn't've worked before with the single file; would there be anything in particular to be gained by adding such situations? Or is there a concrete scenario where the whole repo is present but symlinks are broken?

**Comment by ybt195** [comment]
The plan currently is to isolate every sub-project so that each sub-project works in its own context. One thing that we would like to do is this, (which may not necessarily break but that leaves us prone to their implementation details):
https://circleci.com/docs/2.0/configuration-reference/#job_name.

More generally though, we would like to not break the philosophy that each sub-project is self-contained.

**Comment by dzhu** [comment]
Okay, if the separation is going to be more of a thing and not just academic, I can go with it.

(I'm not seeing what the CircleCI job name has to do with this, though.)

**Pull request merged**
