### PR TITLE
chore: webui stop polling on experiment terminal state [DET-4305]

### PR DESCRIPTION
**Pull request by apizzini**
## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

**Review by hamidzr — COMMENTED** [review]
This is looking good and it stops experiment polling from sending out requests after it is in a terminal state. I think we might be able to take it a bit further. `usePolling` returns a fn that should allow you to stop polling. 
What do you think about maybe tracking the experiment state and once it is in a terminal state we trigger that? I think we have a `Set` that defines terminal run states.

**Comment by apizzini** [comment]
@hamidzr thanks for the review(s). Made both changes.

**Review by hamidzr — APPROVED** [review]
Looks great. I do see we end up making two queries to the experiment endpoint I'm not sure if there is a short clean way of improving that but I'd say this is good even without that. :rocket:

**Comment by hamidzr** [comment]
I was gonna mention we should do this for trial details as well but I saw the ticket already mentions that. Could we do the same for trial details? the bandwidth savings there would even be bigger.

**Comment by apizzini** [comment]
I've understood the reason of the 2nd polling call even if stop is called before.

Due to `src/hooks/usePolling.ts` line 22:
```javascript
await pollingFn();
```

being sync, and setTimeout being called on line 26.

The result is that stop (the 1st time) is called when timeout is still not defined.

Fix is possible in 2 ways:
- remove await on line 22 (call will be async, setTimeout called before stop).
- do something less simple (a state var, another timer, ...)

Lmk:
- if you want me to fix it, and eventually here or in another MR
- what you think is the best way

@hamidzr @hkang1

**Comment by hamidzr** [comment]
> remove await on line 22 (call will be async, setTimeout called before stop).

we'd need to make sure if it wouldn't have any side-effects :thinking: IMO let's leave that for a separate PR to keep it simple. it's also not a direct ask on this ticket.

**Pull request merged**
